local D, C, L = select(2, ...):unpack()

local GameTooltip = GameTooltip

local DuffedUIHelmCheck = CreateFrame("CheckButton", "DuffedUIHelmCheck", PaperDollFrame, "OptionsCheckButtonTemplate")
DuffedUIHelmCheck:ClearAllPoints()
DuffedUIHelmCheck:SetWidth(22)
DuffedUIHelmCheck:SetHeight(22)
DuffedUIHelmCheck:SetPoint("LEFT", CharacterHeadSlot, "RIGHT", 35, 0)
DuffedUIHelmCheck:SetScript("OnClick", function()
	ShowHelm(not ShowingHelm())
end)
DuffedUIHelmCheck:SetScript("OnEnter", function(self)
	GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
	GameTooltip:SetText(OPTION_TOOLTIP_SHOW_HELM)
end)
DuffedUIHelmCheck:SetScript("OnLeave", function()
	GameTooltip:Hide()
end)
DuffedUIHelmCheck:SetScript("OnEvent", function()
	DuffedUIHelmCheck:SetChecked(ShowingHelm())
end)
DuffedUIHelmCheck:RegisterEvent("UNIT_MODEL_CHANGED")
DuffedUIHelmCheck:SetToplevel(true)

local DuffedUICloakCheck = CreateFrame("CheckButton", "DuffedUICloakCheck", PaperDollFrame, "OptionsCheckButtonTemplate")
DuffedUICloakCheck:ClearAllPoints()
DuffedUICloakCheck:SetWidth(22)
DuffedUICloakCheck:SetHeight(22)
DuffedUICloakCheck:SetPoint("LEFT", CharacterBackSlot, "RIGHT", 35, 0)
DuffedUICloakCheck:SetScript("OnClick", function()
	ShowCloak(not ShowingCloak())
end)
DuffedUICloakCheck:SetScript("OnEnter", function(self)
	GameTooltip:SetOwner(self, "ANCHOR_RIGHT")
	GameTooltip:SetText(OPTION_TOOLTIP_SHOW_CLOAK)
end)
DuffedUICloakCheck:SetScript("OnLeave", function()
	GameTooltip:Hide()
end)
DuffedUICloakCheck:SetScript("OnEvent", function()
	DuffedUICloakCheck:SetChecked(ShowingCloak())
end)
DuffedUICloakCheck:RegisterEvent("UNIT_MODEL_CHANGED")
DuffedUICloakCheck:SetToplevel(true)

DuffedUIHelmCheck:SetChecked(ShowingHelm())
DuffedUICloakCheck:SetChecked(ShowingCloak())

DuffedUIHelmCheck:SetFrameLevel(31)
DuffedUICloakCheck:SetFrameLevel(31)

DuffedUIHelmCheck:SkinCheckBox()
DuffedUICloakCheck:SkinCheckBox()