local D, C, L = unpack(select(2, ...))
if IsAddOnLoaded("AddOnSkins") then return end

local function LoadPremadeSkin()
	--[[Global]]--
	LFGListFrame.CategorySelection.Inset:StripTextures()
	LFGListFrame.CategorySelection.StartGroupButton:StripTextures()
	LFGListFrame.CategorySelection.StartGroupButton:SkinButton()
	LFGListFrame.CategorySelection.FindGroupButton:StripTextures()
	LFGListFrame.CategorySelection.FindGroupButton:SkinButton()

	--[[Create Groups]]--
	LFGListFrame.EntryCreation.Inset:StripTextures()
	LFGListEntryCreationCategoryDropDown:SkinDropDownBoxLong()
	LFGListEntryCreationGroupDropDown:SkinDropDownBox()
	LFGListEntryCreationActivityDropDown:SkinDropDownBox()
	LFGListFrame.EntryCreation.ItemLevel.CheckButton:SkinCheckBox()
	LFGListFrame.EntryCreation.VoiceChat.CheckButton:SkinCheckBox()
	LFGListFrame.EntryCreation.Name:StripTextures()
	LFGListFrame.EntryCreation.Name:SetTemplate()
	LFGListFrame.EntryCreation.ItemLevel.EditBox:SkinEditBox()
	LFGListFrame.EntryCreation.VoiceChat.EditBox:SkinEditBox()
	LFGListEntryCreationDescription:StripTextures()
	LFGListEntryCreationDescription:SkinEditBox()
	LFGListFrame.EntryCreation.CancelButton:StripTextures()
	LFGListFrame.EntryCreation.CancelButton:SkinButton()
	LFGListFrame.EntryCreation.ListGroupButton:StripTextures()
	LFGListFrame.EntryCreation.ListGroupButton:SkinButton()
	LFGListFrame.EntryCreation.ActivityFinder.Dialog:StripTextures()
	LFGListFrame.EntryCreation.ActivityFinder.Dialog:SetTemplate("Transparent")
	LFGListFrame.EntryCreation.ActivityFinder.Dialog.BorderFrame:StripTextures()
	LFGListFrame.EntryCreation.ActivityFinder.Dialog.BorderFrame:SetTemplate()
	LFGListFrame.EntryCreation.ActivityFinder.Dialog.SelectButton:StripTextures()
	LFGListFrame.EntryCreation.ActivityFinder.Dialog.SelectButton:SkinButton()
	LFGListFrame.EntryCreation.ActivityFinder.Dialog.CancelButton:StripTextures()
	LFGListFrame.EntryCreation.ActivityFinder.Dialog.CancelButton:SkinButton()
	LFGListEntryCreationSearchScrollFrame:StripTextures()
	LFGListEntryCreationSearchScrollFrameScrollBar:SkinScrollBar()

	--[[Search Groups]]--
	LFGListFrame.SearchPanel.ResultsInset:StripTextures()
	LFGListFrame.SearchPanel.ResultsInset:SetTemplate()
	LFGListFrame.SearchPanel.RefreshButton:SkinButton()
	LFGListFrame.SearchPanel.SearchBox:SkinEditBox()
	LFGListFrame.SearchPanel.SearchBox:ClearAllPoints()
	LFGListFrame.SearchPanel.SearchBox:Point("TOPLEFT", LFGListSearchPanelScrollFrame, -1, 25)
	LFGListFrame.SearchPanel.SearchBox:SetWidth(LFGListFrame.SearchPanel.SearchBox:GetWidth() - 5)
	LFGListSearchPanelScrollFrame:StripTextures()
	LFGListSearchPanelScrollFrameScrollBar:SkinScrollBar()
	LFGListSearchPanelScrollFrame.StartGroupButton:StripTextures()
	LFGListSearchPanelScrollFrame.StartGroupButton:SkinButton()
	LFGListFrame.SearchPanel.BackButton:StripTextures()
	LFGListFrame.SearchPanel.BackButton:SkinButton()
	LFGListFrame.SearchPanel.BackButton:ClearAllPoints()
	LFGListFrame.SearchPanel.BackButton:Point("TOPLEFT", LFGListFrame.SearchPanel.ResultsInset, "BOTTOMLEFT", 0, -2)
	LFGListFrame.SearchPanel.SignUpButton:StripTextures()
	LFGListFrame.SearchPanel.SignUpButton:SkinButton()
	LFGListFrame.SearchPanel.SignUpButton:ClearAllPoints()
	LFGListFrame.SearchPanel.SignUpButton:Point("TOPRIGHT", LFGListFrame.SearchPanel.ResultsInset, "BOTTOMRIGHT", 0, -2)
end

tinsert(D.SkinFuncs["DuffedUI"], LoadPremadeSkin)