if not (Tukui or AsphyxiaUI or DuffedUI or ShestakUI) then return end

local LSM = LibStub('LibSharedMedia-3.0')
LSM:Register('statusbar', 'Dajova', [[Interface\AddOns\Enhanced_Config\Media\StatusBars\Dajova]])
LSM:Register('statusbar', 'Asphyxia', [[Interface\AddOns\Enhanced_Config\Media\StatusBars\Asphyxia]])
LSM:Register('statusbar', 'Flatt', [[Interface\AddOns\Enhanced_Config\Media\StatusBars\Flatt]])
LSM:Register('statusbar', 'Tukui', [[Interface\AddOns\Enhanced_Config\Media\StatusBars\Tukui]])
LSM:Register('statusbar', 'ElvUI Gloss', [[Interface\AddOns\Enhanced_Config\Media\StatusBars\ElvUI]])

LSM:Register('sound', 'Warning', [[Interface\AddOns\Enhanced_Config\Media\Sounds\Warning.mp3]])

LSM:Register('font', 'Big Noodle Titling', [[Interface\AddOns\Enhanced_Config\Media\Fonts\BigNoodleTitling.ttf]])
LSM:Register('font', 'Dajova', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Dajova.ttf]])
LSM:Register('font', 'Oswald Bold', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Oswald-Bold.ttf]])
LSM:Register('font', 'Oswald Light', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Oswald-Light.ttf]])
LSM:Register('font', 'Oswald Regular', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Oswald-Regular.ttf]])
LSM:Register('font', 'Saarland', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Saarland.ttf]])
LSM:Register('font', 'Samson', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Samson.ttf]])
LSM:Register('font', 'Sony Sketch', [[Interface\AddOns\Enhanced_Config\Media\Fonts\SonySketch.ttf]])
LSM:Register('font', 'PT Sans Narrow Bold', [[Interface\AddOns\Enhanced_Config\Media\Fonts\PTSansNarrow-Bold.ttf]])
LSM:Register('font', 'Diediedie', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Diediedie.ttf]])
LSM:Register('font', 'Visitor TT2 BRK', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Visitor.ttf]])
LSM:Register('font', 'Homespun TT BRK', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Homespun.ttf]])
LSM:Register('font', 'Action Man', [[Interface\AddOns\Enhanced_Config\Media\Fonts\ActionMan.ttf]])
LSM:Register('font', 'Continuum Medium', [[Interface\AddOns\Enhanced_Config\Media\Fonts\ContinuumMedium.ttf]])
LSM:Register('font', 'Arial', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Arial.ttf]])

LSM:Register('font', 'Tukui Pixel', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Visitor.ttf]])
LSM:Register('font', 'Tukui Combat', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Diediedie.ttf]])
LSM:Register('font', 'Tukui UnitFrame', [[Interface\AddOns\Enhanced_Config\Media\Fonts\BigNoodleTitling.ttf]])

LSM:Register('font', 'ElvUI Alt-Combat', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Diediedie.ttf]])
LSM:Register('font', 'ElvUI Alt-Font', [[Interface\AddOns\Enhanced_Config\Media\Fonts\ContinuumMedium.ttf]])
LSM:Register('font', 'ElvUI Combat', [[Interface\AddOns\Enhanced_Config\Media\Fonts\ActionMan.ttf]])
LSM:Register('font', 'ElvUI Font', [[Interface\AddOns\Enhanced_Config\Media\Fonts\PTSansNarrow-Bold.ttf]])
LSM:Register('font', 'ElvUI Pixel', [[Interface\AddOns\Enhanced_Config\Media\Fonts\Homespun.ttf]])