local D, C, L = unpack(select(2, ...))

C['general'] = {
	['autoscale'] = true,
	['uiscale'] = 0.71,
	['backdropcolor'] = {.05, .05, .05},
	['bordercolor'] = {.125, .125, .125},
	['classcolor'] = true,
	['autoaccept'] = true,
	['blizzardreskin'] = true,
	['calendarevent'] = false,
	['4kpp'] = false,
	['moveblizzardframes'] = false,
	['minimapsize'] = 144,
}

C['unitframes'] = {
	['enable'] = true,
	['layout'] = 1,
	['percent'] = true,
	['percentoutside'] = false,
	['showsmooth'] = true,
	['unicolor'] = true,
	['healthbarcolor'] = {.125, .125, .125, 1},
	['deficitcolor'] = {0, 0, 0},
	['ColorGradient'] = true,
	['charportrait'] = true,
	['weakenedsoulbar'] = true,
	['targetauras'] = true,
	['onlyselfdebuffs'] = false,
	['combatfeedback'] = false,
	['healcomm'] = true,
	['playeraggro'] = true,
	['totdebuffs'] = false,
	['totdbsize'] = 20,
	['focusdebuffs'] = true,
	['focusbutton'] = true,
	['buffsize'] = 20,
	['debuffsize'] = 20,
	['classbar'] = true,
	['attached'] = false,
	['oocHide'] = true,
	['EnableAltMana'] = true,
	['grouptext'] = true,
	['showrange'] = true,
}

C['chat'] = {
	['enable'] = true,
	['whispersound'] = true,
	['lbackground'] = true,
	['rbackground'] = true,
	['textright'] = true,
	['fading'] = true,
	['newchatbubbles'] = true,
	['chatbubblesfontsize'] = 13,
}

C['castbar'] = {
	['enable'] = true,
	['petenable'] = true,
	['cblatency'] = true,
	['cbicons'] = true,
	['spark'] = true,
	['classcolor'] = false,
	['color'] = {.31, .45, .63, .5},
	['cbticks'] = true,
	['playerwidth'] = 376,
	['playerheight'] = 21,
	['targetwidth'] = 225,
	['targetheight'] = 18,
	['cbiconwidth'] = 25,
	['cbiconheight'] = 25,
}

C['nameplate'] = {
 	['active'] = true,
	['classcolor'] = true,
	['eliteicon'] = true,
	['floatingct'] = true,
	['floatingst'] = 1.2,
	['floatingan'] = true,
 	['platewidth'] = 110,
 	['plateheight'] = 7,
	['platescale'] = 1.5,
	['questicons'] = true,
	['threat'] = true,
	['pDebuffs'] = true,
	['hidetargetglow'] = false,
	['showperc'] = false,
}

C['actionbar'] = {
	['enable'] = true,
	['rightbarvertical'] = false,
	['rightbarsmouseover'] = false,
	['rightbarDisable'] = false,
	['petbarhorizontal'] = false,
	['petbaralwaysvisible'] = true,
	['verticalshapeshift'] = true,
	['hotkey'] = true,
	['macro'] = false,
	['buttonsize'] = 27,
	['SidebarButtonsize'] = 23,
	['petbuttonsize'] = 29,
	['buttonspacing'] = 4,
	['shapeshiftborder'] = true,
	['shapeshiftmouseover'] = false,
	['borderhighlight'] = false,
	['Leftsidebars'] = false,
	['Rightsidebars'] = false,
	['LeftSideBar'] = false,
	['RightSideBar'] = false,
	['LeftSideBarDisable'] = false,
	['RightSideBarDisable'] = false,
	['hidepanels'] = false,
	['extraquestbutton'] = true,
	['microbar'] = false,
	['microbarmouseover'] = false,
}

C['raid'] = {
	['enable'] = true,
	['showboss'] = true,
	['arena'] = true,
	['maintank'] = true,
	['mainassist'] = false,
	['showrange'] = true,
	['raidalphaoor'] = 0.3,
	['showsymbols'] = true,
	['aggro'] = true,
	['raidunitdebuffwatch'] = true,
	['showraidpets'] = false,
	['showplayerinparty'] = true,
	['framewidth'] = 68,
	['frameheight'] = 35,
	['layout'] = 'heal',
	['aurawatchiconsize'] = 7,
	['aurawatchtexturedicon'] = false,	
}

C['datatext'] = {
	['armor'] = 0,
	['bags'] = 5,
	['battleground'] = true,
	['bfamissions'] = 0,
	['calltoarms'] = 0,
	['crit'] = 0,
	['dur'] = 2,
	['friends'] = 3,
	['garrison'] = 0,
	['gold'] = 6,
	['guild'] = 1,
	['haste'] = 0,
	['honor'] = 0,
	['honorablekills'] = 0,
	['mastery'] = 0,
	['micromenu'] = 0,
	['orderhall'] = 0,
	['power'] = 7,
	['profession'] = 0,
	['quickjoin'] = 0,
	['smf'] = 4,
	['talent'] = 0,
	['versatility'] = 0,
	['wowtime'] = 8,

	['time24'] = true,
	['localtime'] = false,
	['ShowInCombat'] = false,
	['ogf'] = false,
}

C['cooldown'] = {
	['enable'] = true,
	['treshold'] = 8,
	['rcdenable'] = true,
	['rcdraid'] = true,
	['rcdparty'] = false,
	['rcdarena'] = false,
	['scdenable'] = true,
	['scdfsize'] = 12,
	['scdsize'] = 28,
	['scdspacing'] = 10,
	['scdfade'] = 0,
}

C['classtimer'] = {
	['enable'] = true,
	['playercolor'] = {.2, .2, .2, 1 },
	['targetbuffcolor'] = { 70/255, 150/255, 70/255, 1 },
	['targetdebuffcolor'] = { 150/255, 30/255, 30/255, 1 },
	['trinketcolor'] = {75/255, 75/255, 75/255, 1 },
	['height'] = 15,
	['spacing'] = 1,
	['separator'] = true,
	['separatorcolor'] = { 0, 0, 0, .5 },
	['debuffsenable'] = true,
	['targetdebuff'] = false,
}

C['auras'] = {
	['player'] = true,
	['flash'] = false,
	['classictimer'] = true,
	['wrap'] = 18,
}

C['bags'] = {
	['BagColumns'] = 11,
	['BankColumns'] = 11,
	['BindText'] = false,
	['ButtonSize'] = 28,
	['ButtonSpace'] = 4,
	['Enable'] = true,
	['ItemLevel'] = true,
	['ItemLevelThreshold'] = 10,
	['JunkIcon'] = true,
	['ScrapIcon'] = true,
	['PulseNewItem'] = true,
	['ReverseLoot'] = false,
	['SortInverted'] = false,
	["BagBar"] = false,
	["BagBarMouseover"] = false,
}

C['misc'] = {
	['gold'] = true,
	['sesenable'] = true,
	['sesenablegear'] = true,
	['sesgearswap'] = true,
	['sesset1'] = 1,
	['sesset2'] = 2,
	['sesset3'] = 3,
	['sesset4'] = 4,
	['combatanimation'] = true,
	['flightpoint'] = true,
	['ilvlcharacter'] = true,
	['durabilitycharacter'] = true,
	['acm_screen'] = true,
	['AFKCamera'] = true,
	['XPBar'] = true,
	['XPBarWidth'] = 5,
	['XPBarHeight'] = 166,
	['magemenu'] = false,
	['azerite'] = true,
	['azeritewidth'] = 5,
	['azeriteheight'] = 166,
}

C['duffed'] = {
	['dispelannouncement'] = false,
	['drinkannouncement'] = false,
	['sayinterrupt'] = true,
	['announcechannel'] = 'SAY',
	['spellannounce'] = true,
	['errorfilter'] = true,
	['notalkinghead'] = false,
	['autocollapse'] = true,
	filter = {
		[INVENTORY_FULL] = true,
		[ERR_PARTY_LFG_BOOT_COOLDOWN_S] = true,
		[ERR_PARTY_LFG_BOOT_LIMIT] = true,
		[ERR_PETBATTLE_NOT_HERE] = true,
		[ERR_PETBATTLE_NOT_WHILE_IN_COMBAT] = true,
		[ERR_CANT_USE_ITEM] = true,
		[CANT_USE_ITEM] = true,
		[SPELL_FAILED_NOT_FISHABLE] = true,
	},
}

C['loot'] = {
	['lootframe'] = true,
	['rolllootframe'] = true,
}

C['tooltip'] = {
	['AzeriteArmor'] = true,
	['CursorAnchor'] = false,
	['Enable'] = true,
	['GuildRanks'] = true,
	['HealthbarHeight'] = 11,
	['FontSize'] = 11,
	['HealthBarText'] = true,
	['HideInCombat'] = false,
	['Icons'] = true,
	['TargetInfo'] = true,
	['InspectInfo'] = true,
	['ItemQualityBorder'] = true,
	['PlayerTitles'] = true,
	['NpcID'] = false,
	['PlayerRoles'] = true,
	['SpellID'] = false,
	['ShowMount'] = true,
}

C['merchant'] = {
	['sellgrays'] = true,
	['autorepair'] = true,
	['sellmisc'] = true,
	['autoguildrepair'] = false,
}
