if GetLocale() == "zhCN" then
	-- general
	DuffedUIConfigUILocalization.general = "综合"
	DuffedUIConfigUILocalization.generalautoscale = "UI自动缩放"
	DuffedUIConfigUILocalization.generaluiscale = "UI缩放 (仅在UI自动缩放关闭的时候启用)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "设置默认的面板背景色"
	DuffedUIConfigUILocalization.generalbordercolor = "设置默认的面板边框颜色"
	DuffedUIConfigUILocalization.generalclasscolor = "启用文本按职业着色显示设定"

	-- castbar
	DuffedUIConfigUILocalization.castbar = "施法条"
	DuffedUIConfigUILocalization.castbarenable = "启用施法条"
	DuffedUIConfigUILocalization.castbarpetenable = "启用宠物施法条"
	DuffedUIConfigUILocalization.castbarcbicons = "启用施放技能图标"
	DuffedUIConfigUILocalization.castbarcblatency = "启用施法条延迟时间显示"
	DuffedUIConfigUILocalization.castbarspark = "启用施法条闪烁"
	DuffedUIConfigUILocalization.castbarcolor = "设置施法条颜色"
	DuffedUIConfigUILocalization.castbarclasscolor = "启用施法条按职业颜色着色"
	DuffedUIConfigUILocalization.castbarcbticks = "启用施法条取消技能施放提示音"

	-- misc
	DuffedUIConfigUILocalization.misc = "杂项"
	DuffedUIConfigUILocalization.misccombatanimation = "启用进战/脱战动画提示"
	DuffedUIConfigUILocalization.miscflightpoint = "启用飞行点列表"
	DuffedUIConfigUILocalization.miscilvlcharacter = "启用人物面板显示装备等级"
	DuffedUIConfigUILocalization.miscsComboenergybar = "启用sCombo能量条插件"
	DuffedUIConfigUILocalization.miscsesenable = "启用天赋切换插件"
	DuffedUIConfigUILocalization.miscsesenablegear = "启用装备设定按钮（系统装备设定）"
	DuffedUIConfigUILocalization.miscsesgearswap = "启用切换天赋时自动切换装备功能"
	DuffedUIConfigUILocalization.miscsesset1 = "为第一套天赋设置装备序号 (必须是1-10之间的序号)"
	DuffedUIConfigUILocalization.miscsesset2 = "为第二套天赋设置装备序号 (必须是1-10之间的序号)"
	DuffedUIConfigUILocalization.miscgold = "启用聊天框体中获取金钱名称缩写功能."
	DuffedUIConfigUILocalization.misclocation = "启用/禁用顶部地理位置信息栏"
	DuffedUIConfigUILocalization.miscexp_rep = "显示 声望/经验 面板于下方面板"
	DuffedUIConfigUILocalization.miscacm_screen = "启用获取成就自动截图"
	DuffedUIConfigUILocalization.miscclickcast = "启用点击施放法术功能(Click2Cast)"

	-- skins
	DuffedUIConfigUILocalization.skins = "插件美化皮肤"
	DuffedUIConfigUILocalization.skinsblizzardreskin = "美化暴雪默认界面使之搭配DuffedUI"
	DuffedUIConfigUILocalization.skinscalendarevent = "禁用行事历事件的纹理材质"
	DuffedUIConfigUILocalization.miscloc = "禁止动作条<角色失去控制>功能(暴雪5.1添加功能)"

	-- classtimer
	DuffedUIConfigUILocalization.classtimer = "职业法术计时条"
	DuffedUIConfigUILocalization.classtimerenable = "启用职业法术计时条"
	DuffedUIConfigUILocalization.classtimerspark = "启用闪烁"
	DuffedUIConfigUILocalization.classtimertargetdebuffs = "启用目标Debuff计时条"
	DuffedUIConfigUILocalization.classtimerplayercolor = "设置玩家计时条颜色"
	DuffedUIConfigUILocalization.classtimertargetbuffcolor = "设置目标计时条Buff颜色"
	DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "设置目标计时条Debuff颜色"
	DuffedUIConfigUILocalization.classtimertrinketcolor = "设置饰品计时条颜色"
	DuffedUIConfigUILocalization.classtimerheight = "设定职业计时条高度"
	DuffedUIConfigUILocalization.classtimerspacing = "设定职业计时条之间的间隙度"
	DuffedUIConfigUILocalization.classtimerseparator = "启用施放法术分离器"
	DuffedUIConfigUILocalization.classtimerseparatorcolor = "设定分离器颜色"
	DuffedUIConfigUILocalization.classtimertargetdebuffsenable = "Enable / disable debuff bars"

	-- duffed
	DuffedUIConfigUILocalization.duffed = "Duffed"
	DuffedUIConfigUILocalization.duffedbossicons = "在地图上启用数字代替BOSS图标"
	DuffedUIConfigUILocalization.duffeddrinkannouncement = "启用吃喝通告(PVP)"
	DuffedUIConfigUILocalization.duffedsayinterrupt = "启用打断通告"
	DuffedUIConfigUILocalization.duffedannouncechannel = "设置通告频道 (设定值为:|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r or |cffC41F3BINSTANCE_CHAT|r)"
	DuffedUIConfigUILocalization.duffeddispelannouncement = "启用驱散通告"
	DuffedUIConfigUILocalization.duffedspellannounce = "启用光环增益状态通告"

	-- drunes
	DuffedUIConfigUILocalization.runes = "|cffC41F3Bd|rRunes"
	DuffedUIConfigUILocalization.runesenable = "为DK职业启用额外可选的符文计时条"
	DuffedUIConfigUILocalization.runesbarlength = "设定符文计时条长度"
	DuffedUIConfigUILocalization.runesbarthickness = "设定符文计时条宽度"
	DuffedUIConfigUILocalization.runesdisplayrpbar = "启用符文能量条显示于符文条下方"
	DuffedUIConfigUILocalization.runesdisplayrpbartext = "启用符文能量文字显示"
	DuffedUIConfigUILocalization.runesrpbarthickness = "设定符文能量条宽度"
	DuffedUIConfigUILocalization.runeshideooc = "非战斗中隐藏drunes符文插件界面"
	DuffedUIConfigUILocalization.runesgrowthdirection = "设定符文计时条排列方式(输入 VERTICAL 为水平方式 or 输入 HORIZONTAL 为垂直方式)"

	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "姓名版"
	DuffedUIConfigUILocalization.nameplateenable = "开启姓名版"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "启用仇恨着色模式,将会根据你的角色自动改变颜色"
	DuffedUIConfigUILocalization.nameplateshowhealth = "在姓名板上显示生命值"
	DuffedUIConfigUILocalization.nameplatecombat = "仅在战斗中显示姓名板"
	DuffedUIConfigUILocalization.nameplategoodcolor = "安全仇恨值颜色,取决于你是坦克还是治疗者"
	DuffedUIConfigUILocalization.nameplatebadcolor = "危险仇恨值颜色,取决于你是治疗还是输出"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "失去/获得仇恨值颜色"
	DuffedUIConfigUILocalization.nameplatedebuffs = "启用姓名板debuff显示"
	DuffedUIConfigUILocalization.nameplateheight = "设置姓名板高度 (默认 = 7)"
	DuffedUIConfigUILocalization.nameplatewidth = "设置姓名板款度 (默认 = 110)"
	DuffedUIConfigUILocalization.nameplateshowcastbarname = "显示施法条名字"
	DuffedUIConfigUILocalization.nameplatenameabbrev = "显示缩略名"
	DuffedUIConfigUILocalization.nameplateaurassize = "设置光环大小 (默认 = 20)"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "商人"
	DuffedUIConfigUILocalization.merchantsellgrays = "自动售卖灰色物品"
	DuffedUIConfigUILocalization.merchantautorepair = "自动修理物品"
	DuffedUIConfigUILocalization.merchantsellmisc = "自动贩卖特定物品(非灰色等级的指定物品)"
	DuffedUIConfigUILocalization.merchantautoguildrepair = "启用工会修理物品设定"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "背包"
	DuffedUIConfigUILocalization.bagsenable = "开启背包整合"
	DuffedUIConfigUILocalization.bagsbpr = "设定背包每行显示按钮"
	DuffedUIConfigUILocalization.bagsmoveable = "使背包可移动"
	DuffedUIConfigUILocalization.bagsscale = "Set scale of bag & bank frames"
	DuffedUIConfigUILocalization.bagsspacing = "Set  spacing betweens bagslots"
	DuffedUIConfigUILocalization.bagsbuttonsize = " Set slotsize"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "文本信息"
	DuffedUIConfigUILocalization.datatexttime24 = "使用24小时制"
	DuffedUIConfigUILocalization.datatextlocaltime = "使用本地时间取代服务器时间"
	DuffedUIConfigUILocalization.datatextbattleground = "启用战场状态"
	DuffedUIConfigUILocalization.datatextguild = "公会信息 (输入0关闭)"
	DuffedUIConfigUILocalization.datatext_arp = "护甲穿透 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextsystem = "内存占用信息 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextbags = "背包 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextfontsize = "文本字体大小"
	DuffedUIConfigUILocalization.datatextfps_ms = "延时和帧数(输入0关闭)"
	DuffedUIConfigUILocalization.datatextarmor = "护甲值 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextavd = "免伤 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextpower = "攻强/法伤(输入0关闭)"
	DuffedUIConfigUILocalization.datatexthaste = "急速(输入0关闭)"
	DuffedUIConfigUILocalization.datatextfriends = "好友(输入0关闭)"
	DuffedUIConfigUILocalization.datatextwowtime = "时间(输入0关闭)"
	DuffedUIConfigUILocalization.datatextgold = "金币(输入0关闭)"
	DuffedUIConfigUILocalization.datatextcrit = "爆击 % (输入0关闭)"
	DuffedUIConfigUILocalization.datatextdur = "耐久度(输入0关闭)"
	DuffedUIConfigUILocalization.datatextmicromenu = "微型菜单(输入0关闭)"
	DuffedUIConfigUILocalization.datatexthit = "命中(输入0关闭)"
	DuffedUIConfigUILocalization.datatextmastery = "精通 (输入0关闭)"
	DuffedUIConfigUILocalization.datatexttalent = "显示天赋 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "地下城战斗的召唤 (输入0关闭)"
	DuffedUIConfigUILocalization.datatextsmf = "系统(输入0关闭)"
	DuffedUIConfigUILocalization.datatexthonorablekills = "荣誉击杀统计(输入0关闭)"
	DuffedUIConfigUILocalization.datatextdodge = "闪躲率(输入0关闭)"
	DuffedUIConfigUILocalization.datatextparry = "招架率(输入0关闭)"
	DuffedUIConfigUILocalization.datatextblock = "格挡率(输入0关闭)"
	DuffedUIConfigUILocalization.datatexthonor = "荣誉值(输入0关闭)"
	DuffedUIConfigUILocalization.datatextprofession = "专业(输入0关闭)"

	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "单位框体"
	DuffedUIConfigUILocalization.unitframesenable = "启用Duffed Ui头像框架"
	DuffedUIConfigUILocalization.unitframeslayout = "设置人物头像样式 (layout数值为:1, 2 or 3, 默认 = 2)"
	DuffedUIConfigUILocalization.unitframespercent = "启用生命百分比显示于玩家&目标旁边"
	DuffedUIConfigUILocalization.unitframeshealthbarcolor = "设定生命血条颜色"
	DuffedUIConfigUILocalization.unitframesdeficitcolor = "设定生命血量不足颜色"
	DuffedUIConfigUILocalization.unitframesColorGradient = "启用生命条颜色渐变功能(随血量变化)"
	DuffedUIConfigUILocalization.unitframesframewidth = "设定头像框体宽度"
	DuffedUIConfigUILocalization.unitframestotandpetlines = "启用宠物&目标的目标与头像框体的连线效果(仅限于layout布局1 & 2)"
	DuffedUIConfigUILocalization.unitframesportraitstyle = "设定头像显示风格(填写 MODEL 或 ICON,仅限于layout布局1&2)"
	DuffedUIConfigUILocalization.unitframeslargefocus = "启用大型焦点目标框体(仅限于layout布局1)"
	DuffedUIConfigUILocalization.unitframesbuffrows = "设定buff行数"
	DuffedUIConfigUILocalization.unitframesdebuffrows = "设定debuff行数"
	DuffedUIConfigUILocalization.unitframesvengeancebar = "启用复仇条(坦克)代替仇恨条功能"
	DuffedUIConfigUILocalization.unitframespowerClasscolored = "启用能量条职业颜色功能"
	DuffedUIConfigUILocalization.unitframesfocusdebuffs = "启用焦点目标Debuff"
	DuffedUIConfigUILocalization.unitframessComboenable = "启用sCombo连击点插件"
	DuffedUIConfigUILocalization.unitframessComboenergybar = "启用sCombo能量条插件"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "用敌对颜色为敌人框体着色(PVP玩家血条颜色)"
	DuffedUIConfigUILocalization.unitframesauratimer = "在光环上显示时间"
	DuffedUIConfigUILocalization.unitframesauratextscale = "光环文字大小设置"
	DuffedUIConfigUILocalization.unitframestargetauras = "启用目标光环"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "低法力值警报 (所有的法系职业)"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "只显示敌对目标的能量值"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "启用目标的目标的DEBUFF显示 (仅限高分辨率)"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "显示总的生命/能量值"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "启用平滑状态条"
	DuffedUIConfigUILocalization.unitframescharportrait = "为自身和目标启用头像显示"
	DuffedUIConfigUILocalization.unitframesunicolor = "启用单一的颜色主题(灰色的生命条)"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "在玩家和目标框体上显示战斗信息"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "在自身头像上启用仇恨显示"
	DuffedUIConfigUILocalization.unitframeshealcomm = "启用预估治疗"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "只在目标框体上显示你释放的DEBUFF"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "启用焦点的目标框体"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "显示状态条"
	DuffedUIConfigUILocalization.unitframesbordercolor = "设置为默认的边框颜色"
	DuffedUIConfigUILocalization.unitframesruneofpower = "启用奥法符能能量条（法师）"
	DuffedUIConfigUILocalization.unitframesfader = "启用头像渐隐"
	DuffedUIConfigUILocalization.unitframesminalpha = "设置头像渐隐最低透明度(默认 = 0.1)"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "启用灵魂虚弱指示 (牧师)"
	DuffedUIConfigUILocalization.unitframesclassbar = "启用职业条"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "熊、猫姿态下显示魔法条（德鲁伊）"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "平衡或恢复天赋下启用蘑菇条（德鲁伊）"
	DuffedUIConfigUILocalization.unitframesfocusbutton = "Enable focus button on player / focus frame"
	DuffedUIConfigUILocalization.unitframestotdbsize = "Set size of debuffs for Target of Target"

	-- Raidframes
	DuffedUIConfigUILocalization.raid = "团队界面"
	DuffedUIConfigUILocalization.raidenable = "启用团队界面"
	DuffedUIConfigUILocalization.raidshowrange = "启用小队/团队距离检测"
	DuffedUIConfigUILocalization.raidraidalphaoor = "小队/团队超出距离透明值"
	DuffedUIConfigUILocalization.raidshowsymbols = "显示小队/团队标记"
	DuffedUIConfigUILocalization.raidaggro = "在小队/团队中启用仇恨显示"
	DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "启用PVE光环检测 (只能在GRIG模式下)"
	DuffedUIConfigUILocalization.raidgridhealthvertical = "在Grid模式中垂直显示生命条"
	DuffedUIConfigUILocalization.raidgridscale = "Grid框体大小"
	DuffedUIConfigUILocalization.raidgridvertical = "在Grid中垂直显示小队"
	DuffedUIConfigUILocalization.raidshowraidpets = "Duffed团队框架中启用宠物框体"
	DuffedUIConfigUILocalization.raidshowgroupresurrect = "显示(某人)被复活的图标于团队框架中"
	DuffedUIConfigUILocalization.raidshowplayerinparty = "在队伍中显示你自己"
	DuffedUIConfigUILocalization.raidgridonly = "治疗模式下仅使用GRID样式"
	DuffedUIConfigUILocalization.raidshowboss = "启用BOSS框体"
	DuffedUIConfigUILocalization.raidarena = "开启竞技场单位框体"
	DuffedUIConfigUILocalization.raidmaintank = "启用主坦克框体"
	DuffedUIConfigUILocalization.raidmainassist = "启用主助理框架"
	DuffedUIConfigUILocalization.raidframewidth = "Set width of the unitframe"
	DuffedUIConfigUILocalization.raidframeheight = "Set height of the unitframe"
	DuffedUIConfigUILocalization.raidcolumnSpacing = "Columnspacing between unitframe"
	

	-- loot
	DuffedUIConfigUILocalization.loot = "拾取"
	DuffedUIConfigUILocalization.lootlootframe = "启用拾取框"
	DuffedUIConfigUILocalization.lootautogreed = "满级时启用自动贪婪绿色物品"
	DuffedUIConfigUILocalization.lootrolllootframe = "启用Roll点框体"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "邀请"
	DuffedUIConfigUILocalization.inviteautoaccept = "开启自动接受邀请 (好友和公会成员)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "鼠标提示"
	DuffedUIConfigUILocalization.tooltipenable = "开启鼠标提示"
	DuffedUIConfigUILocalization.tooltiphidecombat = "战斗中隐藏鼠标提示"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "隐藏动作条鼠标提示"
	DuffedUIConfigUILocalization.tooltiphideuf = "隐藏头像框体鼠标提示"
	DuffedUIConfigUILocalization.tooltipcursor = "开启提示跟随鼠标指针"
	DuffedUIConfigUILocalization.tooltipids = "在物品提示上显示法术/物品ID"
	DuffedUIConfigUILocalization.tooltipilvl = "启用目标装备等级统计显示于鼠标提示信息上"
	DuffedUIConfigUILocalization.tooltipenablecaster = "Enable Castername for buffs / debuffs on tooltip"
	 
	-- error
	DuffedUIConfigUILocalization.error = "错误信息"
	DuffedUIConfigUILocalization.errorenable = "隐藏屏幕中间的红色错误提示信息"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "动作条"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "隐藏姿态或者图腾栏"
	DuffedUIConfigUILocalization.actionbarshowgrid = "始终在动作条上显示空按钮"
	DuffedUIConfigUILocalization.actionbarenable = "启用 DuffedUI 动作条"
	DuffedUIConfigUILocalization.actionbarrb = "启用右侧动作条鼠标划过显示"
	DuffedUIConfigUILocalization.actionbarhotkey = "显示快捷键名称"
	DuffedUIConfigUILocalization.actionbarssmo = "鼠标划过显示姿态栏和图腾栏"
	DuffedUIConfigUILocalization.actionbarrbn = "底部动作条数目 (1 或 2)"
	DuffedUIConfigUILocalization.actionbarrn = "右侧动作条数目 (0, 1, 2 或 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "主动作条按钮大小"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "动作条按钮间距"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "宠物或姿态栏按钮大小"
	DuffedUIConfigUILocalization.actionbarownshdbar = "当暗影之舞时使用一个空的动作条来替代盗贼的潜行动作条（仅盗贼）"
	DuffedUIConfigUILocalization.actionbarownmetabar = "当恶魔形态时使用一个空的动作条来替代主动作条（仅术士）"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "切换姿态时使用一个空的动作条来替代主动作条（仅战士）"
	DuffedUIConfigUILocalization.actionbarmacro = "在动作条上显示宏名称"
	DuffedUIConfigUILocalization.actionbarbutton2 = "隐藏动作条中间的按钮 (只有在动作条1与3没有交换的情况下生效)"
	DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "右动作条鼠标划过显示"
	DuffedUIConfigUILocalization.actionbarswap = "动作条3和动作条1位置互换"
	DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "宠物条永久可视"
	DuffedUIConfigUILocalization.actionbarshapeshiftborder = "启用姿态条边框"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "姿态条鼠标划过显示"
	DuffedUIConfigUILocalization.actionbarverticalshapeshift = "姿态条纵向显示"
	DuffedUIConfigUILocalization.actionbarborderhighlight = "启用 Tukui动作条技能高亮模式 (默认 = 关闭)"
	DuffedUIConfigUILocalization.actionbarlayout = "设定动作条布局模式(默认布局 = 1,填写1或2)"
	DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "设定宠物动作条水平显示模式"

	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "冷却计时模块"
	DuffedUIConfigUILocalization.cooldownenable = "在技能按钮上显示冷却时间"
	DuffedUIConfigUILocalization.cooldowntreshold = "在X秒以后以红色显示冷却时间"

	-- raidcooldowns
	DuffedUIConfigUILocalization.rcd = "团队技能冷却"
	DuffedUIConfigUILocalization.rcdenable = "启用团队技能冷却"
	DuffedUIConfigUILocalization.rcdraid = "在团队中启用团队技能冷却"
	DuffedUIConfigUILocalization.rcdparty = "在队伍中启用团队技能冷却"
	DuffedUIConfigUILocalization.rcdarena = "在竞技场中启用团队技能冷却"

	-- spellcooldowns
	DuffedUIConfigUILocalization.scd = "技能冷却模块"
	DuffedUIConfigUILocalization.scdenable = "启用技能冷却插件(界面中部冷却提醒)"
	DuffedUIConfigUILocalization.scdsize = "设定图标大小(默认= 36)"
	DuffedUIConfigUILocalization.scdspacing = "设定图标间隔(默认 = 10)"
	DuffedUIConfigUILocalization.scdfade = "设定渐隐(设定值: 0 one color, 1 green to red, 2 red to green)"
	DuffedUIConfigUILocalization.scddisplay = "设定显示模式(设定值: SPIRAL 或 STATUSBAR, 默认 = STATUSBAR)"
	DuffedUIConfigUILocalization.scddirection = "设定冷却显示方向(值: HORIZONTAL or VERTICAL, 默认 = HORIZONTAL)"
	DuffedUIConfigUILocalization.scdfsize = "设定字体大小"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "聊天"
	DuffedUIConfigUILocalization.chatenable = "启用DuffedUI的聊天框架"
	DuffedUIConfigUILocalization.chatwhispersound = "在收到密语时播放提示音"
	DuffedUIConfigUILocalization.chatlbackground = "启用聊天面板背景 (左)"
	DuffedUIConfigUILocalization.chatrbackground = "启用聊天面板背景 (右)"
	DuffedUIConfigUILocalization.chatfading = "启用聊天信息渐隐"
	DuffedUIConfigUILocalization.chattextright = "右下方聊天框文字向右对齐"

	-- buff
	DuffedUIConfigUILocalization.auras = "光环"
	DuffedUIConfigUILocalization.aurasplayer = "启用 DuffedUI Buff/Debuff 框架"
	DuffedUIConfigUILocalization.aurasconsolidate = "启用BUFF整合"
	DuffedUIConfigUILocalization.aurasflash = "当光环剩余时间少于30秒时启用闪烁动画"
	DuffedUIConfigUILocalization.aurasclassictimer = "启用经典光环计时样式"
	DuffedUIConfigUILocalization.aurasbuffnotice = "启用Buff缺失警告提醒"
	DuffedUIConfigUILocalization.auraswarning = "为Buff缺失警告提醒功能(BuffNotice)启用报警音效"
	DuffedUIConfigUILocalization.aurasbufftracker = "启用 Buff追踪功能"
	DuffedUIConfigUILocalization.auraswrap = "设定(小地图旁)单行Buff显示数量(默认 = 18)"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "重置"
	DuffedUIConfigUILocalization.option_button_load = "应用设定"
	DuffedUIConfigUILocalization.option_button_close = "关闭"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "为每个角色建立单独的设定"
	DuffedUIConfigUILocalization.option_resetchar = "你确定要重置这个角色的设定到你的默认设定么?"
	DuffedUIConfigUILocalization.option_resetall = "你确定要重置所有的设置为默认值么?"
	DuffedUIConfigUILocalization.option_perchar = "你确定要启用或者关闭“为单一角色设定”么?"
	DuffedUIConfigUILocalization.option_makeselection = "在你继续设置之前你必须要做出一个选择。"
end