DuffedUIConfigUILocalization = { }

--[[General]]--
DuffedUIConfigUILocalization.general = "General"
DuffedUIConfigUILocalization.generalautoscale = "Auto UI Scale"
DuffedUIConfigUILocalization.generaluiscale = "UI Scale (if auto-scale is disabled)"
DuffedUIConfigUILocalization.generalbackdropcolor = "Set default backdrop color of panels"
DuffedUIConfigUILocalization.generalbordercolor = "Set default border color of panels"
DuffedUIConfigUILocalization.generalclasscolor = "Enable class color for textelements"
DuffedUIConfigUILocalization.generalblizzardreskin = "Reskin Blizzard frames to match DuffedUI"
DuffedUIConfigUILocalization.generalcalendarevent = "Disable calendar event textures"
DuffedUIConfigUILocalization.generalautoaccept = "Enable Auto-Invite (Friends and Guildmates)"
DuffedUIConfigUILocalization.general4kpp = "Double scaling for 4k-Monitors to get pixelperfect (should only used with 4k and autoscaling\nis to small)"
DuffedUIConfigUILocalization.generalmoveblizzardframes = 'Move Blizzard Frames'
DuffedUIConfigUILocalization.generalminimapsize = 'Minimap Size (Default = 144)'

--[[Unit Frames]]--
DuffedUIConfigUILocalization.unitframes = "Unit Frames"
DuffedUIConfigUILocalization.unitframesenable = "Enable DuffedUI Unit Frames"
DuffedUIConfigUILocalization.unitframeslayout = "Set UF-Layout (1, 2, 3 or 4, default = 1)"
DuffedUIConfigUILocalization.unitframespercent = "Enable percent display beside player & target"
DuffedUIConfigUILocalization.unitframespercentoutside = "Show the percent Display outside unitframes"
DuffedUIConfigUILocalization.unitframesshowsmooth = "Enable smooth bar"
DuffedUIConfigUILocalization.unitframesunicolor = "Enable Unique color theme (grey health bar)"
DuffedUIConfigUILocalization.unitframeshealthbarcolor = "Set healthbar color"
DuffedUIConfigUILocalization.unitframesdeficitcolor = "Set deficit color"
DuffedUIConfigUILocalization.unitframesColorGradient = "Enable ColorGradient for Healthbar"
DuffedUIConfigUILocalization.unitframescharportrait = "Enable portraits on player and target"
DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Enable Weakened Soul bar notification (Priest)" --- This debuff is no longer in the game.
DuffedUIConfigUILocalization.unitframestargetauras = "Enable target auras"
DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Display only our debuffs on target"
DuffedUIConfigUILocalization.unitframescombatfeedback = "Combat Feedback on player and target"
DuffedUIConfigUILocalization.unitframeshealcomm = "Enable healcomm"
DuffedUIConfigUILocalization.unitframesplayeraggro = "Enable aggro display on yourself"
DuffedUIConfigUILocalization.unitframestotdebuffs = "Enable Target of Target debuffs (High Reso)"
DuffedUIConfigUILocalization.unitframestotdbsize = "Set size of debuffs for Target of Target"
DuffedUIConfigUILocalization.unitframesfocusdebuffs = "Enable focus debuffs"
DuffedUIConfigUILocalization.unitframesfocusbutton = "Enable focus button on player / focus frame"
DuffedUIConfigUILocalization.unitframesbuffsize = "Set size of Buffs on Targetframe"
DuffedUIConfigUILocalization.unitframesdebuffsize = "Set size of Debuffs on Targetframe"
DuffedUIConfigUILocalization.unitframesclassbar = "Enable Classbars"
DuffedUIConfigUILocalization.unitframesattached = "Attach Classbars to Unitframes"
DuffedUIConfigUILocalization.unitframesoocHide = "Hide Classbars out of Combat"
DuffedUIConfigUILocalization.unitframesEnableAltMana = "Enable additional Manadisplay for Druids, Priests & Shamans"
DuffedUIConfigUILocalization.unitframesgrouptext = "Enable groupnumber (See your groupnumber in raid)"

--[[Chat]]--
DuffedUIConfigUILocalization.chat = "Chat"
DuffedUIConfigUILocalization.chatenable = "Enable DuffedUI Chat"
DuffedUIConfigUILocalization.chatwhispersound = "Play sound when receiving private message"
DuffedUIConfigUILocalization.chatlbackground = "Enable chat panel background (left)"
DuffedUIConfigUILocalization.chatrbackground = "Enable chat panel background (right)"
DuffedUIConfigUILocalization.chatfading = "Enable chatfading"
DuffedUIConfigUILocalization.chattextright = "Set textalign to right for right chatframe"

--[[Castbar]]--
DuffedUIConfigUILocalization.castbar = "Castbar"
DuffedUIConfigUILocalization.castbarenable = "Enable castbar"
DuffedUIConfigUILocalization.castbarpetenable = "Enable pet castbar"
DuffedUIConfigUILocalization.castbarcbicons = "Enable castbar-icons"
DuffedUIConfigUILocalization.castbarcblatency = "Enable castbar latency"
DuffedUIConfigUILocalization.castbarspark = "Enable castbar spark"
DuffedUIConfigUILocalization.castbarcolor = "Set color for castbars"
DuffedUIConfigUILocalization.castbarclasscolor = "Enable classcolor for castbar"
DuffedUIConfigUILocalization.castbarcbticks = "Enable castbar ticks for channeled casts."
DuffedUIConfigUILocalization.castbarplayerwidth = "Set width of player castbar"
DuffedUIConfigUILocalization.castbartargetwidth = "Set width of target castbar"
DuffedUIConfigUILocalization.castbarplayerheight = "Set height of player castbar"
DuffedUIConfigUILocalization.castbartargetheight = "Set height of target castbar"
DuffedUIConfigUILocalization.castbarcbiconwidth = "Set width of castbar icons"
DuffedUIConfigUILocalization.castbarcbiconheight = "Set height of castbar icons"

--[[Nameplate]]--
DuffedUIConfigUILocalization.nameplate = "Nameplates"
DuffedUIConfigUILocalization.nameplateactive = "Enable Nameplates"
DuffedUIConfigUILocalization.nameplateplatewidth = "Set width of nameplates (default = 110)"
DuffedUIConfigUILocalization.nameplateplateheight = "Set height of nameplates (default = 7)"
DuffedUIConfigUILocalization.nameplatethreat = "Enable Enhanced Threat"
DuffedUIConfigUILocalization.nameplateclasscolor = "Enable classcolor-display on nameplates"
DuffedUIConfigUILocalization.nameplateplatescale = "Set scale of nameplates (default 1.5)"
DuffedUIConfigUILocalization.nameplatepDebuffs = "Enable display of debuffs on nameplates"
DuffedUIConfigUILocalization.nameplatefloatingct = "Enable floating combattext on nameplates"
DuffedUIConfigUILocalization.nameplatefloatingst = "Combattext scrolltime (default = 1.2)"
DuffedUIConfigUILocalization.nameplatefloatingan = "Abbreviate numbers from combattext (1000 to 1k)"
DuffedUIConfigUILocalization.nameplatehidetargetglow = "Hide targetborder"
DuffedUIConfigUILocalization.nameplateeliteicon = "Enable classification (rare, elite) on nameplates"
DuffedUIConfigUILocalization.nameplatequesticons = "Enable questicons on nameplates"
DuffedUIConfigUILocalization.nameplatecombat = "Enable nameplates only in combat"
DuffedUIConfigUILocalization.nameplateshowperc = "Show healthpercent on target"

--[[Actionbars]]--
DuffedUIConfigUILocalization.actionbar = "Action Bars"
DuffedUIConfigUILocalization.actionbarenable = "Enable DuffedUI action bar"
DuffedUIConfigUILocalization.actionbarrightbarvertical = "Set Rightbar horizontal"
DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "Set rightbars on mouseover"
DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "Set petbar horizontal"
DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "Set petbar to always visible"
DuffedUIConfigUILocalization.actionbarverticalshapeshift = "Enable vertical Shapeshiftbar"
DuffedUIConfigUILocalization.actionbarhotkey = "Show hotkey on buttons"
DuffedUIConfigUILocalization.actionbarmacro = "Show macro text on action bar"
DuffedUIConfigUILocalization.actionbarbuttonsize = "Size of the main action buttons"
DuffedUIConfigUILocalization.actionbarbuttonspacing = "Spacing of the main action buttons"
DuffedUIConfigUILocalization.actionbarshapeshiftborder = "Enable Shapeshiftbarborder"
DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "Enable mouseover for Shapeshift bar"
DuffedUIConfigUILocalization.actionbarborderhighlight = "Enable prochighlight from DuffedUI (default = disabled)"
DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Size of the petactionbuttons"
DuffedUIConfigUILocalization.actionbarLeftsidebars = "Enable mouseover for Left SideBar on chat frame"
DuffedUIConfigUILocalization.actionbarRightsidebars = "Enable mouseover for Right SideBar on chat frame"
DuffedUIConfigUILocalization.actionbarSidebarButtonsize = "Set size of buttons for sidebars on chat (only when vertical)"
DuffedUIConfigUILocalization.actionbarLeftSideBar = "Set left side actionbar horizontal"
DuffedUIConfigUILocalization.actionbarRightSideBar = "Set right side actionbar horizontal"
DuffedUIConfigUILocalization.actionbarLeftSideBarDisable = "Disable left side actionbar"
DuffedUIConfigUILocalization.actionbarRightSideBarDisable = "Disable right side actionbar"
DuffedUIConfigUILocalization.actionbarrightbarDisable = "Disable bar on the right side"
DuffedUIConfigUILocalization.actionbarhidepanels = "Hide panels of actionbars"
DuffedUIConfigUILocalization.actionbarextraquestbutton = "Enable ExtraQuestButton"
DuffedUIConfigUILocalization.actionbarmicrobar = "Enable Micromenubar"
DuffedUIConfigUILocalization.actionbarmicrobarmouseover = "Enable mouseover for Micromenubar"

--[[Raid Frames]]--
DuffedUIConfigUILocalization.raid = "Raid Frames"
DuffedUIConfigUILocalization.raidenable = "Enable Raid Frames"
DuffedUIConfigUILocalization.raidshowboss = "Enable Boss Unit Frames"
DuffedUIConfigUILocalization.raidarena = "Enable arena unit frames"
DuffedUIConfigUILocalization.raidmaintank = "Enable Main Tank"
DuffedUIConfigUILocalization.raidmainassist = "Enable Main Assist"
DuffedUIConfigUILocalization.raidshowrange = "Enable party/raid Range alpha display"
DuffedUIConfigUILocalization.raidraidalphaoor = "Alpha on Party/Raid unit out of range"
DuffedUIConfigUILocalization.raidshowsymbols = "Show symbols on party/raid"
DuffedUIConfigUILocalization.raidaggro = "Enable aggro display on party/raid"
DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "Enable PVE raid Aura Watch (Grid Only)"
DuffedUIConfigUILocalization.raidshowraidpets = "Show Pets in DuffedUI Raid Frames"
DuffedUIConfigUILocalization.raidshowplayerinparty = "Show yourself in party"
DuffedUIConfigUILocalization.raidframewidth = "Set width of the unitframe"
DuffedUIConfigUILocalization.raidframeheight = "Set height of the unitframe"
DuffedUIConfigUILocalization.raidlayout = "Set layout for group frames (default = heal, Values: |cffC41F3Bheal|r or |cffC41F3Bdps|r)"

--[[DataText]]--
DuffedUIConfigUILocalization.datatext = "Data Text"
DuffedUIConfigUILocalization.datatextarmor = "Armor Position (0 for disabled)"
DuffedUIConfigUILocalization.datatextbags = "Bags position (0 for disabled)"
DuffedUIConfigUILocalization.datatextbattleground = "Enable Battleground Stats"
DuffedUIConfigUILocalization.datatextcalltoarms = "Call to Arms & Dungeons (0 for disabled)"
DuffedUIConfigUILocalization.datatextcrit = "Crit % position (0 for disabled)"
DuffedUIConfigUILocalization.datatextdur = "Durability position (0 for disabled)"
DuffedUIConfigUILocalization.datatextfriends = "Friends position (0 for disabled)"
DuffedUIConfigUILocalization.datatextgold = "Gold position (0 for disabled)"
DuffedUIConfigUILocalization.datatextguild = "Guild position (0 for disabled)"
DuffedUIConfigUILocalization.datatexthaste = "Haste position (0 for disabled)"
DuffedUIConfigUILocalization.datatexthonor = "Honor  position (0 for disabled)"
DuffedUIConfigUILocalization.datatexthonorablekills = "Honorable Kills position (0 for disabled)"
DuffedUIConfigUILocalization.datatextmastery = "Mastery position (0 for disabled)"
DuffedUIConfigUILocalization.datatextmicromenu = "Micro Menu position (0 for disabled)"
DuffedUIConfigUILocalization.datatextpower = "Power position (0 for disabled)"
DuffedUIConfigUILocalization.datatextprofession = "Profession position (0 for disabled)"
DuffedUIConfigUILocalization.datatextsmf = "System position (0 for disabled)"
DuffedUIConfigUILocalization.datatexttalent = "Display talents (0 for disabled)"
DuffedUIConfigUILocalization.datatextversatility = "Versatility position (0 for disabled)"
DuffedUIConfigUILocalization.datatextwowtime = "Time position (0 for disabled)"
DuffedUIConfigUILocalization.datatextgarrison = "Garrison position (0 for disabled)"
DuffedUIConfigUILocalization.datatextorderhall = "Orderhall position (0 for disabled)"
DuffedUIConfigUILocalization.datatextbfamissions = "BfA Missions position (0 for disabled)"
DuffedUIConfigUILocalization.datatextquickjoin = "QuickJoin position (0 for disabled)"
DuffedUIConfigUILocalization.datatexttime24 = "Enable 24h time"
DuffedUIConfigUILocalization.datatextlocaltime = "Use Local Time instead of Server Time"
DuffedUIConfigUILocalization.datatextfontsize = "Font size of text"
DuffedUIConfigUILocalization.datatextShowInCombat = "Show DataText-Tooltip in combat"

--[[Cooldowns]]--
DuffedUIConfigUILocalization.cooldown = "Cooldowns"
DuffedUIConfigUILocalization.cooldownenable = "Enable cooldown number on buttons"
DuffedUIConfigUILocalization.cooldowntreshold = "Turn cooldown number red at X value"
DuffedUIConfigUILocalization.cooldownrcdenable = "Enable Raid Cooldowns"
DuffedUIConfigUILocalization.cooldownrcdraid = "Enable cooldown announcement for raid"
DuffedUIConfigUILocalization.cooldownrcdparty = "Enable cooldown announcement for party"
DuffedUIConfigUILocalization.cooldownrcdarena = "Enable cooldown announcement for arena"
DuffedUIConfigUILocalization.cooldownscdenable = "Enable the SpellCooldown-Plugin"
DuffedUIConfigUILocalization.cooldownscdfsize = "Set fontsize"
DuffedUIConfigUILocalization.cooldownscdsize = "Set size for icons (default = 28)"
DuffedUIConfigUILocalization.cooldownscdspacing = "Set spacing of icons (default = 10)"
DuffedUIConfigUILocalization.cooldownscdfade = "Set fading (values: 0 one color, 1 green to red, 2 red to green)"

--[[ClassTimer]]--
DuffedUIConfigUILocalization.classtimer = "Classtimer"
DuffedUIConfigUILocalization.classtimerenable = "Enable Classtimer"
DuffedUIConfigUILocalization.classtimerspark = "Enable spark"
DuffedUIConfigUILocalization.classtimertargetdebuff = "Enable Debuff display above target frame instead of player frame"
DuffedUIConfigUILocalization.classtimerplayercolor = "Set player color"
DuffedUIConfigUILocalization.classtimertargetbuffcolor = "Set target buff color"
DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "Set target debuff color"
DuffedUIConfigUILocalization.classtimertrinketcolor = "Set trinket color"
DuffedUIConfigUILocalization.classtimerheight = "Set height of classtimer bar"
DuffedUIConfigUILocalization.classtimerspacing = "Set spacing of classtimer bars"
DuffedUIConfigUILocalization.classtimerseparator = "Enable cast separator"
DuffedUIConfigUILocalization.classtimerseparatorcolor = "Set color of separator"
DuffedUIConfigUILocalization.classtimerdebuffsenable = "Enable Debuff display on classtimer"

--[[Buffs]]--
DuffedUIConfigUILocalization.auras = "Auras"
DuffedUIConfigUILocalization.aurasplayer = "Enable DuffedUI Buff/Debuff Frames"
DuffedUIConfigUILocalization.aurasflash = "Enable flashing animation on aura less than 30 seconds"
DuffedUIConfigUILocalization.aurasclassictimer = "Display classic timer on player auras"
DuffedUIConfigUILocalization.auraswrap = "Set wrap for buffs (default = 18)"

--[[Bags]]--
DuffedUIConfigUILocalization.bags = "Bags"
DuffedUIConfigUILocalization.bagsBagColumns = "Set bagbuttons per row"
DuffedUIConfigUILocalization.bagsBankColumns = "Set bankbuttons per row"
DuffedUIConfigUILocalization.bagsBindText = "Show keybind on items in bag"
DuffedUIConfigUILocalization.bagsButtonSize = "Set slotsize"
DuffedUIConfigUILocalization.bagsButtonSpace = "Set spacing betweens bagslots"
DuffedUIConfigUILocalization.bagsEnable = "Enable all-in-one bag"
DuffedUIConfigUILocalization.bagsItemLevel = "Show ItemLevel"
DuffedUIConfigUILocalization.bagsItemLevelThreshold = "ItemLevel Threshold"
DuffedUIConfigUILocalization.bagsJunkIcon = "Show JunkIcon"
DuffedUIConfigUILocalization.bagsScrapIcon = "Show ScrapIcon"
DuffedUIConfigUILocalization.bagsPulseNewItem = "Enable Pulse Animation for new items"
DuffedUIConfigUILocalization.bagsReverseLoot = "Loot in left bag first"
DuffedUIConfigUILocalization.bagsSortInverted = "Sort inverted"
DuffedUIConfigUILocalization.bagsBagBar = "Enable Bagbar"
DuffedUIConfigUILocalization.bagsBagBarMouseover = "Enable mouseover for Bagbar"

--[[Misc]]--
DuffedUIConfigUILocalization.misc = "Misc"
DuffedUIConfigUILocalization.miscgold = "Enable shorten gold display in chat"
DuffedUIConfigUILocalization.miscsesenable = "Enable Spec switcher plugin"
DuffedUIConfigUILocalization.miscsesenablegear = "Enable Equipment set buttons"
DuffedUIConfigUILocalization.miscsesgearswap = "Enable automatic setswap on respec"
DuffedUIConfigUILocalization.miscsesset1 = "Set set for first spec (must be an value between 1 - 10)"
DuffedUIConfigUILocalization.miscsesset2 = "Set set for second spec (must be an value between 1 - 10)"
DuffedUIConfigUILocalization.miscsesset3 = "Set set for third spec (must be an value between 1 - 10)"
DuffedUIConfigUILocalization.miscsesset4 = "Set set for fourth spec (must be an value between 1 - 10)"
DuffedUIConfigUILocalization.misccombatanimation = "Enable Combatanimation"
DuffedUIConfigUILocalization.miscflightpoint = "Enable Flight point list"
DuffedUIConfigUILocalization.miscilvlcharacter = "Enable item level on character screen"
DuffedUIConfigUILocalization.miscacm_screen = "Enable automatic Achievment screenshots"
DuffedUIConfigUILocalization.miscAFKCamera = "Enable AFKCamera"
DuffedUIConfigUILocalization.miscXPBar = "Enable XP-Bar"
DuffedUIConfigUILocalization.miscXPBarWidth = "Set width of XP-Bar"
DuffedUIConfigUILocalization.miscXPBarHeight = "Set height of XP-Bar"
DuffedUIConfigUILocalization.miscmagemenu = "Enable Teleport menu (works only on Mages)"
DuffedUIConfigUILocalization.miscazerite = "Enable Azerite-Bar"
DuffedUIConfigUILocalization.miscazeritewidth = "Set width of Azerite-Bar"
DuffedUIConfigUILocalization.miscazeriteheight = "Set height of Azerite-Bar"
DuffedUIConfigUILocalization.miscdurabilitycharacter = "Enable durability on character screen"

--[[Duffed]]--
DuffedUIConfigUILocalization.duffed = "Duffed"
DuffedUIConfigUILocalization.duffeddrinkannouncement = "Enable Drink announcement"
DuffedUIConfigUILocalization.duffedsayinterrupt = "Enable Interrupt announcement"
DuffedUIConfigUILocalization.duffedannouncechannel = "Set channel for announcement (|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r or |cffC41F3BINSTANCE_CHAT|r)"
DuffedUIConfigUILocalization.duffeddispelannouncement = "Enable Dispel announcement"
DuffedUIConfigUILocalization.duffedspellannounce = "Enable Aura announcement"
DuffedUIConfigUILocalization.duffederrorfilter = "Hide spamming error in the middle of your screen"
DuffedUIConfigUILocalization.duffednotalkinghead = "Disable the Talking Head-Frame"
DuffedUIConfigUILocalization.duffedobjectivetracker = "Enable moving for objectivetracker"

--[[Loot]]--
DuffedUIConfigUILocalization.loot = "Loot"
DuffedUIConfigUILocalization.lootlootframe = "Enable loot window"
DuffedUIConfigUILocalization.lootrolllootframe = "Enable item roll window"

--[[Tooltip]]--
DuffedUIConfigUILocalization.tooltip = "Tooltip"
DuffedUIConfigUILocalization.tooltipAzeriteArmor = "Show Azerite Armor"
DuffedUIConfigUILocalization.tooltipCursorAnchor = "Show Cursor on Anchor"
DuffedUIConfigUILocalization.tooltipEnable = "Enable DuffedUI Tooltip"
DuffedUIConfigUILocalization.tooltipGuildRanks = "Show Guild Ranks"
DuffedUIConfigUILocalization.tooltipHealthbarHeight = "Healthbar Height"
DuffedUIConfigUILocalization.tooltipFontSize = "Font Size"
DuffedUIConfigUILocalization.tooltipHealthBarText = "Show Healthbar Text"
DuffedUIConfigUILocalization.tooltipHideInCombat = "Hide Tooltip in Combat"
DuffedUIConfigUILocalization.tooltipIcons = "Show Icons"
DuffedUIConfigUILocalization.tooltipTargetInfo = "Show TargetInfo"
DuffedUIConfigUILocalization.tooltipInspectInfo = "Show InspectInfo - ilvl (Hold Shift)"
DuffedUIConfigUILocalization.tooltipItemQualityBorder = "Show Itemqualityborders" 
DuffedUIConfigUILocalization.tooltipPlayerTitles = "Show Player Titles"
DuffedUIConfigUILocalization.tooltipNpcID = "Show NpcID"
DuffedUIConfigUILocalization.tooltipPlayerRoles = "Show Player Roles in Groups/Raid"
DuffedUIConfigUILocalization.tooltipSpellID = "Show Spell- and ItemID"
DuffedUIConfigUILocalization.tooltipShowMount = "Show Mount (Hold Ctrl for more info)"

--[[Merchant]]--
DuffedUIConfigUILocalization.merchant = "Merchant"
DuffedUIConfigUILocalization.merchantsellgrays = "Auto Sell grey items"
DuffedUIConfigUILocalization.merchantautorepair = "Auto Repair items"
DuffedUIConfigUILocalization.merchantsellmisc = "Sell some defined (craps not grey) items automatically"
DuffedUIConfigUILocalization.merchantautoguildrepair = "Enable Guild Repair Items"

--[[Buttons]]--
DuffedUIConfigUILocalization.option_button_reset = "|cffffd100Reset|r"
DuffedUIConfigUILocalization.option_button_load = "|cff00FF00" .. APPLY .. "|r"
DuffedUIConfigUILocalization.option_button_close = "|cffFF0000" .. CLOSE .. "|r"
DuffedUIConfigUILocalization.option_setsavedsetttings = "Set settings Per-Character"
DuffedUIConfigUILocalization.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
DuffedUIConfigUILocalization.option_resetall = "Are you sure you want to reset all of your settings to Default?"
DuffedUIConfigUILocalization.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
DuffedUIConfigUILocalization.option_makeselection = "You must make a selection before you can continue to config."
