if GetLocale() == "deDE" then
	--[[General]]--
	DuffedUIConfigUILocalization.general = "Allgemein"
	DuffedUIConfigUILocalization.generalautoscale = "Aktiviere 'Automatischen UI Maßstab'"
	DuffedUIConfigUILocalization.generaluiscale = "UI Maßstab (wenn 'Automatischer UI Maßstab' deaktiviert ist)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Setze Standard-Hintergrundfarbe der Panels"
	DuffedUIConfigUILocalization.generalbordercolor = "Setze Standard-Rahmenfarbe der Panels"
	DuffedUIConfigUILocalization.generalclasscolor = "Aktiviere Klassenfarben für Textelemente"
	DuffedUIConfigUILocalization.generalblizzardreskin = "Zeige die Blizzard eigenen Fenster im Stile von DuffedUI an"
	DuffedUIConfigUILocalization.generalcalendarevent = "Deaktiviere die Texturen, der Events, im Kalender"
	DuffedUIConfigUILocalization.generalautoaccept = "Aktiviere die automatische Einladung von Freunden und Gildenmitgliedern"
	DuffedUIConfigUILocalization.general4kpp = 'Verdoppelt die Skalierung bei 4k-Monitoren für PixelPerfect (Sollte nur mit 4k-Monitoren benutzt werden, wenn die Autosklaierung\nzu klein ist)'
	DuffedUIConfigUILocalization.generalmoveblizzardframes = 'Blizzardfenster beweglich machen'
	DuffedUIConfigUILocalization.generalminimapsize = 'Minimap Größe (Standard = 144)'
	DuffedUIConfigUILocalization.generalwelcome = 'Aktiviere die Willkommensnachricht'
	DuffedUIConfigUILocalization.generalminimapbuttons = 'Aktiviere die Minimap Buttons'

	--[[Unit Frames]]--
	DuffedUIConfigUILocalization.unitframes = "Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesenable = "Aktiviere die DuffedUI Einheitenfenster"
	DuffedUIConfigUILocalization.unitframeslayout = "Wähle Dein UF-Layout (1, 2, 3 oder 4, Standard = 1)"
	DuffedUIConfigUILocalization.unitframespercent = "Aktiviere eine Prozentanzeige neben Spieler & Ziel"
	DuffedUIConfigUILocalization.unitframespercentoutside = "Zeige die Prozentanzeige an den Einheitenfenstern außen an"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Aktiviere weiche Übergänge bei den Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesunicolor = "Aktiviere ein einheitliches Farbmotiv (graue Lebensleiste)"
	DuffedUIConfigUILocalization.unitframeshealthbarcolor = "Setze die Farbe der Lebensleiste"
	DuffedUIConfigUILocalization.unitframesdeficitcolor = "Setze die Farbe bei Lebensverlust"
	DuffedUIConfigUILocalization.unitframesColorGradient = "Aktiviere Farbverlauf für die Heilleiste"
	DuffedUIConfigUILocalization.unitframescharportrait = "Aktiviere Charakterportraits am Spieler- und Zielframe"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Aktiviere 'Geschwächte Seele' Leiste (Priester ->Rote Leiste)"
	DuffedUIConfigUILocalization.unitframestargetauras = "Aktiviere Auren am Einheitenfenster des Ziels"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Zeige nur deine Schwächungszauber am Einheitenfester des Ziels"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Zeige Kampf-Feedback auf dem Spieler- und Zieleinheitenfenster"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Aktiviere die 'Ankommende Heilungsleiste'"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Aktiviere die Anzeige von Aggro am Spielereinheitenfenster"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Aktiviere Ziel-des-Ziels Schwächungszauber (Nur Hohe Grtafikauflösung!)"
	DuffedUIConfigUILocalization.unitframestotdbsize = "Wähle die Größe für Schwächungszauber vom 'Ziel des Ziels' Einheitenfester"
	DuffedUIConfigUILocalization.unitframesfocusdebuffs = "Aktiviere Schwächungszauber am Fokuseinheitenfenster"
	DuffedUIConfigUILocalization.unitframesfocusbutton = "Aktiviere den Fokusbutton für Spieler- / Fokuseinheitenfenster"
	DuffedUIConfigUILocalization.unitframesbuffsize = "Wähle die Größe der Stärkungszauber am Ziel"
	DuffedUIConfigUILocalization.unitframesdebuffsize = "Wähle die Größe der Schwächungszauber am Ziel"
	DuffedUIConfigUILocalization.unitframesclassbar = "Aktiviere die Klassenleiste"
	DuffedUIConfigUILocalization.unitframesattached = "Verbinde die Klassenleiste mit dem Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesoocHide = "Verstecke die Klassenleiste wenn Du nicht im Kampf bist"
	DuffedUIConfigUILocalization.unitframesEnableAltMana = "Aktiviere zusätzliche Manaanzeige für Druiden, Priester & Schamanen"
	DuffedUIConfigUILocalization.unitframesgrouptext = "Zeige im Raid die Gruppe an in der du bist"
	DuffedUIConfigUILocalization.unitframescombatfade = "Aktiviere das Verblassen der Einheitenfenster, wenn nicht im Kampf"
	DuffedUIConfigUILocalization.unitframesshowrange = "Aktiviere das Verblassen der Einheitenfenster, wenn ausser Reichweite"

	--[[Chat]]--
	DuffedUIConfigUILocalization.chat = "Chat"
	DuffedUIConfigUILocalization.chatenable = "Aktiviere den DuffedUI Chat"
	DuffedUIConfigUILocalization.chatwhispersound = "Spiele einen Ton bei Empfang einer privaten Nachricht"
	DuffedUIConfigUILocalization.chatlbackground = "Aktiviere Chathintergrund (links)"
	DuffedUIConfigUILocalization.chatrbackground = "Aktiviere Chathintergrund (rechts)"
	DuffedUIConfigUILocalization.chatfading = "Aktiviere ausblenden des Chats"
	DuffedUIConfigUILocalization.chattextright = "Textausrichtung rechts für den rechten Chatframe"
	DuffedUIConfigUILocalization.chatnewchatbubbles = "Aktiviere die neuen Chatblasen"
	DuffedUIConfigUILocalization.chatchatbubblesfontsize = "Schriftgröße der neuen Chatblasen"

	--[[Castbar]]--
	DuffedUIConfigUILocalization.castbar = "Zauberleiste"
	DuffedUIConfigUILocalization.castbarenable = "Aktiviere Zauberleiste"
	DuffedUIConfigUILocalization.castbarpetenable = "Aktiviere Gefährten-Zauberleiste"
	DuffedUIConfigUILocalization.castbarcbicons = "Aktiviere Zauberleisten-Symbole"
	DuffedUIConfigUILocalization.castbarcblatency = "Aktiviere Zauberleisten-Latenz"
	DuffedUIConfigUILocalization.castbarspark = "Aktiviere Zauberleisten-Spark"
	DuffedUIConfigUILocalization.castbarcolor = "Wähle Farbe der Zauberleiste"
	DuffedUIConfigUILocalization.castbarclasscolor = "Aktiviere Klassenfarben für die Zauberleiste"
	DuffedUIConfigUILocalization.castbarcbticks = "Aktiviere Ticks für kanalisierte Zauber"
	DuffedUIConfigUILocalization.castbarplayerwidth = "Setze Breite der Spielerzauberleiste"
	DuffedUIConfigUILocalization.castbartargetwidth = "Setze Breite der Zielzauberleiste"
	DuffedUIConfigUILocalization.castbarplayerheight = "Setze Höhe der Spielerzauberleiste"
	DuffedUIConfigUILocalization.castbartargetheight = "Setze Höhe der Zielzauberleiste"
	DuffedUIConfigUILocalization.castbarcbiconwidth = "Setze Breit der Zauberleisten-Icons"
	DuffedUIConfigUILocalization.castbarcbiconheight = "Setze Höhe der Zauberleisten-Icons"

	--[[Nameplate]]--
	DuffedUIConfigUILocalization.nameplate = "Namensplaketten"
	DuffedUIConfigUILocalization.nameplateactive = "Aktivere Namensplaketten"
	DuffedUIConfigUILocalization.nameplateplatewidth = "Breite der Namensplaketten (Standard = 110)"
	DuffedUIConfigUILocalization.nameplateplateheight = "Höhe der Namensplaketten (Standard = 7)"
	DuffedUIConfigUILocalization.nameplatethreat = "Aktiviere erweitertete Aggroanzeige"
	DuffedUIConfigUILocalization.nameplateclasscolor = "Aktiviere Anzeige für Klassenfarben bei den Namensplaketten"
	DuffedUIConfigUILocalization.nameplateplatescale = "Wähle die Skalierung der Namensplaketten (Standard 1.5)"
	DuffedUIConfigUILocalization.nameplatepDebuffs = "Aktiviere die Anzeige der Schwächungszauber"
	DuffedUIConfigUILocalization.nameplatefloatingct = "Aktiviere den fliegenden Kampftext an den Namensplaketten"
	DuffedUIConfigUILocalization.nameplatefloatingst = "Scrollzeit des Kampftexts (Standard 1.2)"
	DuffedUIConfigUILocalization.nameplatefloatingan = "Kürze den Kampftext (1000 zu 1k)"
	DuffedUIConfigUILocalization.nameplatehidetargetglow = "Verstecke den Umriss des gewählten Ziels"
	DuffedUIConfigUILocalization.nameplateeliteicon = "Zeige die Klassifizierung (Rare, Elite) an den Namensplaketten"
	DuffedUIConfigUILocalization.nameplatequesticons = "Aktiviere die Questsymbole an den Namensplaketten"
	DuffedUIConfigUILocalization.nameplatecombat = "Aktiviere die Namensplaketten nur im Kampf"
	DuffedUIConfigUILocalization.nameplateshowperc = "Zeige das Leben des Ziels in '%' an"

	--[[Actionbars]]--
	DuffedUIConfigUILocalization.actionbar = "Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarenable = "Aktiviere die DuffedUI Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarrightbarvertical = "Setze die rechte Leiste auf 'horizontal'"
	DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "Aktiviere die rechte Leiste per 'mouseover'"
	DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "Setze die Begleiterleiste auf 'horizontal'"
	DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "Setze die Begleiterleiste auf 'immer sichtbar'"
	DuffedUIConfigUILocalization.actionbarverticalshapeshift = "Setze die Haltungsleiste auf 'vertikal'"
	DuffedUIConfigUILocalization.actionbarhotkey = "Zeige die Hotkeys auf den Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarmacro = "Zeige den Makrotext auf den Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Einstellung der Größe von den Aktionsleistenknöpfen"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Abstand zwischen den Aktionsleistenknöpfen"
	DuffedUIConfigUILocalization.actionbarshapeshiftborder = "Aktiviere den Rahmen der Haltungsleisten"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "Aktiviere die Haltungsleiste per 'mouseover'"
	DuffedUIConfigUILocalization.actionbarborderhighlight = "Aktiviere die Proc-Hervorhebung auf den Aktionsleisten (Standard = Deaktiviert)"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Größe der Begleiter- und Haltungsleistenschaltflächen"
	DuffedUIConfigUILocalization.actionbarLeftsidebars = "Aktiviere die linke Seitenleiste an den Chatframes per 'mouseover'"
	DuffedUIConfigUILocalization.actionbarRightsidebars = "Aktiviere die rechte Seitenleiste an den Chatframes per 'mouseover'"
	DuffedUIConfigUILocalization.actionbarSidebarButtonsize = "Setze Größe der Knöpfe für die Seitenleisten am Chat (nur wenn vertikal)"
	DuffedUIConfigUILocalization.actionbarLeftSideBar = "Setze die linke Sidebar 'horizontal'"
	DuffedUIConfigUILocalization.actionbarRightSideBar = "Setze die rechte Sidebar 'horizontal'"
	DuffedUIConfigUILocalization.actionbarLeftSideBarDisable = "Deaktiviere die linke Sidebar"
	DuffedUIConfigUILocalization.actionbarRightSideBarDisable = "Deaktiviere die rechte Sidebar"
	DuffedUIConfigUILocalization.actionbarrightbarDisable = "Deaktiviere Leiste auf der rechten Seite"
	DuffedUIConfigUILocalization.actionbarhidepanels = "Deaktiviere die Hintergrundpanels der Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarextraquestbutton = "Aktiviere den ExtraQuestButton"
	DuffedUIConfigUILocalization.actionbarmicrobar = "Aktiviere die Micromenüleiste"
	DuffedUIConfigUILocalization.actionbarmicrobarmouseover = "Aktiviere die Micromenüleiste per 'mouseover'"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseovervalue = "'Mouseover' Verblassenwert (Standard 1)"

	--[[Raid Frames]]--
	DuffedUIConfigUILocalization.raid = "Schlachtzugfenster"
	DuffedUIConfigUILocalization.raidenable = "Aktiviere die DuffedUI Schlachtzugsfenster"
	DuffedUIConfigUILocalization.raidshowboss = "Aktiviere Einheitenfenster für Bosse"
	DuffedUIConfigUILocalization.raidarena = "Aktiviere Einheitenfenster für die Arena"
	DuffedUIConfigUILocalization.raidmaintank = "Aktiviere die 'Haupt-Tank' Anzeige"
	DuffedUIConfigUILocalization.raidmainassist = "Aktiviere die 'Haupt-Assistent' Anzeige"
	DuffedUIConfigUILocalization.raidshowrange = "Aktiviere die Gruppen- und Raid Entfernungsanzeige"
	DuffedUIConfigUILocalization.raidraidalphaoor = "Sichtbarkeit der Gruppen- und Schlachtzugeinheiten, die ausser Reichweite sind"
	DuffedUIConfigUILocalization.raidshowsymbols = "Zeige Symbole auf Gruppen- und Schlachtzugeinheiten"
	DuffedUIConfigUILocalization.raidaggro = "Aktiviere die Anzeige von Aggro auf den Gruppen- und Raidfenstern"
	DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "Aktiviere die Aurenbeobachtung im PVE Schlachtzug"
	DuffedUIConfigUILocalization.raidshowraidpets = "Zeige die Begleiterfenster im Schlachtzug an."
	DuffedUIConfigUILocalization.raidshowplayerinparty = "Füge Dein Einheitenfester der Gruppe hinzu"
	DuffedUIConfigUILocalization.raidframewidth = "Einstellung für die Breite der Einheitenfenster"
	DuffedUIConfigUILocalization.raidframeheight = "Einstellung für die Höhe der Einheitenfenster"
	DuffedUIConfigUILocalization.raidlayout = "Wähle Layout für das Schlachtzugfenster (Standard = heal, Werte: |cffC41F3Bheal|r oder |cffC41F3Bdps|r)"
	DuffedUIConfigUILocalization.raidaurawatchiconsize = "Größe des Aura Watch Symbols"
	DuffedUIConfigUILocalization.raidaurawatchtexturedicon = "Zeige das Aura Watch Sybol texturiert (Aus, zeigt das Icon farbig an.)"

	--[[DataText]]--
	DuffedUIConfigUILocalization.datatext = "Datatext"
	DuffedUIConfigUILocalization.datatextarmor = "Position der 'Rüstungsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextbags = "Position der 'Taschenanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextbattleground = "Aktiviere die 'Statistikanzeige' auf den 'Schlachtfeldern'"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Position der 'Ruf zu den Waffen Anzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextcrit = "Position der 'Kritische Trefferanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextdur = "Position der 'Haltbarkeitsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextfriends = "Position der 'Freundschaftsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextgold = "Position der 'Goldanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextguild = "Position der 'Gildenanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthaste = "Position der 'Schnelligkeitsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthonor = "Position der 'Ehrepunkteanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthonorablekills = "Position der 'Tötungsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextmastery = "Position der 'Meisterschaftsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Position der 'Mikromenüanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextpower = "Position der 'Kraftanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextprofession = "Position der 'Berufsanzeige' position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextsmf = "Position der 'Systemanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexttalent = "Position der 'Talenteanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextversatility = "Position der 'Vielseitigkeitsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextwowtime = "Position der 'Zeitanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextgarrison = "Position der 'Garnison' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextorderhall = "Position der 'Ordenshalle' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextbfamissions = "Position der 'BfA Missionssanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextquickjoin = "Position der 'QuickJoinanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexttime24 = "Aktiviere 24h Zeitanzeige"
	DuffedUIConfigUILocalization.datatextlocaltime = "Zeige die lokale Zeit, anstatt der Server Zeit"
	DuffedUIConfigUILocalization.datatextfontsize = "Schriftgröße des Datatexts"
	DuffedUIConfigUILocalization.datatextShowInCombat = "Zeige DataText-Tooltip im Kampf"

	--[[Cooldowns]]--
	DuffedUIConfigUILocalization.cooldown = "Abklingzeiten"
	DuffedUIConfigUILocalization.cooldownenable = "Aktiviere DuffedUI Abklingzeiten"
	DuffedUIConfigUILocalization.cooldowntreshold = "Färbe die Abklingszeiten beim erreichen von Wert X 'rot'"
	DuffedUIConfigUILocalization.cooldownrcdenable = "Aktiviere Abklingzeiten im Raid"
	DuffedUIConfigUILocalization.cooldownrcdraid = "Aktiviere Ankündigungen der Abklingzeiten für Raids"
	DuffedUIConfigUILocalization.cooldownrcdparty = "Aktiviere Ankündigungen der Abklingzeiten für die Gruppe"
	DuffedUIConfigUILocalization.cooldownrcdarena = "Aktiviere Ankündigungen der Abklingzeiten in der Arena"
	DuffedUIConfigUILocalization.cooldownscdenable = "Aktiviere das Zauber Abklingzeit-Plugin"
	DuffedUIConfigUILocalization.cooldownscdfsize = "Schritgröße der Zauberabklingzeiten"
	DuffedUIConfigUILocalization.cooldownscdsize = "Größe der Icons (Standard = 28)"
	DuffedUIConfigUILocalization.cooldownscdspacing = "Abstand der Icons (Standard = 10)"
	DuffedUIConfigUILocalization.cooldownscdfade = "Verblassen der Abklingen (Werte: 0 eine Farbe, 1 Grün nach Rot, 2 Rot nach Grün)"

	--[[ClassTimer]]--
	DuffedUIConfigUILocalization.classtimer = "Classtimer"
	DuffedUIConfigUILocalization.classtimerenable = "Aktiviere den 'Classtimer' an den Einheitenfestern"
	DuffedUIConfigUILocalization.classtimerspark = "Aktiviere den 'Funken' an den Classtimern"
	DuffedUIConfigUILocalization.classtimertargetdebuff = "Aktiviere Zieldebuffs über dem Ziel anstatt über dem Spieler"
	DuffedUIConfigUILocalization.classtimerplayercolor = "Wähle die Farbe am Spielerfenster"
	DuffedUIConfigUILocalization.classtimertargetbuffcolor = "Wähle die Farbe des Stärkungszaubers auf dem Ziel"
	DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "Wähle Farbe des Schwächungszaubers auf dem Ziel"
	DuffedUIConfigUILocalization.classtimertrinketcolor = "Wähle die Schmuckstückfarbe"
	DuffedUIConfigUILocalization.classtimerheight = "Setze die Höhe der ClassTimer-Leiste"
	DuffedUIConfigUILocalization.classtimerspacing = "Setze den Zwischenraum der ClassTimer-Leisten"
	DuffedUIConfigUILocalization.classtimerseparator = "Aktiviere die Zauberabgrenzung"
	DuffedUIConfigUILocalization.classtimerseparatorcolor = "Wähle die Abgrenzungsfarbe"
	DuffedUIConfigUILocalization.classtimerdebuffsenable = "Aktiviere die Anzeige der Schwächungszauberleisten"

	--[[Buffs]]--
	DuffedUIConfigUILocalization.auras = "Auren"
	DuffedUIConfigUILocalization.aurasplayer = "Aktiviere die DuffedUI Buff- und Debufffenster"
	DuffedUIConfigUILocalization.aurasflash = "Aktiviere das Aufblitzen der Auren bei weniger als 30 Sekunden"
	DuffedUIConfigUILocalization.aurasclassictimer = "Zeige den klassischen Timer auf den Spieler Auren"
	DuffedUIConfigUILocalization.auraswrap = "Wähle Umbruch der Stärkungszauberleiste (Standard = 18)"
	DuffedUIConfigUILocalization.aurasInside = "Verschiebe den Timer nach innen"

	--[[Bags]]--
	DuffedUIConfigUILocalization.bags = "Taschen"
	DuffedUIConfigUILocalization.bagsBagsWidth = "Taschenplatzanzahl pro Reihe (Taschen)"
	DuffedUIConfigUILocalization.bagsBankWidth = "Taschenplatzanzahl pro Reihe (Bank)"
	DuffedUIConfigUILocalization.bagsBagsiLvl = "Zeigt die Gegenstandsstufe auf anlegbaren Gegenständen"
	DuffedUIConfigUILocalization.bagsDeleteButton = "Zeige den Gegenstands 'Löschen' Knopf"
	DuffedUIConfigUILocalization.bagsGatherEmpty = "Leere Plätze als einen anzeigen mit der Anzahl leerer Plätze"
	DuffedUIConfigUILocalization.bagsIconSize = "Größe der Taschenplätze"
	DuffedUIConfigUILocalization.bagsScrapIcon = "Zeige Schrottsymbol"
	DuffedUIConfigUILocalization.bagsItemFilter = "Aktiviere die Gegenstandsfilterung in den Taschen"
	DuffedUIConfigUILocalization.bagsItemSetFilter = "Filter für Setgegendstände"
	DuffedUIConfigUILocalization.bagsQuestItemFilter = "Filter für Questgegendstände"
	DuffedUIConfigUILocalization.bagsTradeGoodsFilter = "Filter für Handwerkswaren"
	DuffedUIConfigUILocalization.bagsSpecialBagsColor = "Spezialtaschen einfärben"
	DuffedUIConfigUILocalization.bagsUpgradeIcon = "Zeige Upgrade Symbol"
	DuffedUIConfigUILocalization.bagsEnable = "Aktiviere die 'Alles in einer Tasche' Ansicht"
	DuffedUIConfigUILocalization.bagsBagBar = "Aktiviere die Taschenleiste"
	DuffedUIConfigUILocalization.bagsBagBarMouseover = "Aktiviere die Taschenleiste per 'mouseover'"

	--[[Misc]]--
	DuffedUIConfigUILocalization.misc = "Sonstiges"
	DuffedUIConfigUILocalization.miscgold = "Kürze die Goldanzeige im Chat"
	DuffedUIConfigUILocalization.miscsesenable = "Aktiviere das Talenwechsel-Plugin"
	DuffedUIConfigUILocalization.miscsesenablegear = "Aktiviere Ausrüstungsset-Schaltflächen"
	DuffedUIConfigUILocalization.miscsesgearswap = "Aktiviere automatischen Setwechsel bei Talentwechsel"
	DuffedUIConfigUILocalization.miscsesset1 = "Aktiviere das Set für die erste Spezalisierung (muss ein Wert zwischen 1 - 10 sein)"
	DuffedUIConfigUILocalization.miscsesset2 = "Aktiviere das Set für die zweite Spezalisierung (muss ein Wert zwischen 1 - 10 sein)"
	DuffedUIConfigUILocalization.miscsesset3 = "Aktiviere das Set für die dritte Spezalisierung (muss ein Wert zwischen 1 - 10 sein)"
	DuffedUIConfigUILocalization.miscsesset4 = "Aktiviere das Set für die vierte Spezalisierung (muss ein Wert zwischen 1 - 10 sein)"
	DuffedUIConfigUILocalization.misccombatanimation = "Aktiviere die Kampf beginnen und verlassen Anzeige"
	DuffedUIConfigUILocalization.miscflightpoint = "Zeige alle Flugpunkte auf der Weltkarte an"
	DuffedUIConfigUILocalization.miscitemlevel = "Aktiviere die Gegenstandsstufenanzeige im Charakterbildschirm"
	DuffedUIConfigUILocalization.miscgemenchantinfo = "Aktiviere die Juwelen- und Verzauberungsinfo im Charakterbildschirm"
	DuffedUIConfigUILocalization.miscacm_screen = "Aktiviere ein automatisches Bildschirmfoto beim Erreichen eines Achievements"
	DuffedUIConfigUILocalization.miscAFKCamera = "Aktiviere die AFK Kamera"
	DuffedUIConfigUILocalization.miscXPBar = "Aktiviere XP-Leiste"
	DuffedUIConfigUILocalization.miscXPBarWidth = "Stelle Breite der XP-Leiste ein"
	DuffedUIConfigUILocalization.miscXPBarHeight = "Stelle Höhe der XP-Leiste ein"
	DuffedUIConfigUILocalization.miscmagemenu = "Aktiviere Teleportmenu (funktioniert nur bei Magiern)"
	DuffedUIConfigUILocalization.miscazerite = "Aktiviere Azerite-Bar"
	DuffedUIConfigUILocalization.miscazeritewidth = "Stelle Breite der Azerite-Bar ein"
	DuffedUIConfigUILocalization.miscazeriteheight = "Stelle Höhe der Azerite-Bar ein"
	DuffedUIConfigUILocalization.misccorruption = "Aktiviere Verderbnis-Bar"
	DuffedUIConfigUILocalization.misccorruptionwidth = "Stelle Breite der Verderbnis-Bar ein"
	DuffedUIConfigUILocalization.misccorruptionheight = "Stelle Höhe der Verderbnis-Bar ein"
	DuffedUIConfigUILocalization.misccorruptioneffects = "Aktiviere die Verderbniseffekte im Tooltip"
	DuffedUIConfigUILocalization.miscdurabilitycharacter = "Aktiviere die Haltbarkeitsanzeige im Charakterbildschirm"

	--[[Duffed]]--
	DuffedUIConfigUILocalization.duffed = "Duffed"
	DuffedUIConfigUILocalization.duffeddrinkannouncement = "Aktiviere Trinkwarnungen"
	DuffedUIConfigUILocalization.duffedsayinterrupt = "Aktiviere Unterbrechungsansagen"
	DuffedUIConfigUILocalization.duffedannouncechannel = "Chatkanal für Warnungsansagen (|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r oder |cffC41F3BINSTANCE_CHAT|r)"
	DuffedUIConfigUILocalization.duffeddispelannouncement = "Aktiviere Reinigungswarnungen"
	DuffedUIConfigUILocalization.duffedspellannounce = "Aktiviere Aurawarnungen"
	DuffedUIConfigUILocalization.duffederrorfilter = "Verstecke die Fehlermeldungen, die in der Mitte Deines Bildschirms immer wieder angezeigt werden"
	DuffedUIConfigUILocalization.duffednotalkinghead = "Deaktiviere den Emoteframe von NPC's"
	DuffedUIConfigUILocalization.duffedautocollapse = "Aktiviere das automatische Zuklappen der Questverfolgung"

	--[[Loot]]--
	DuffedUIConfigUILocalization.loot = "Beutefenster"
	DuffedUIConfigUILocalization.lootlootframe = "Aktiviere das DuffedUI Lootfenster"
	DuffedUIConfigUILocalization.lootrolllootframe = "Aktiviere das DuffedUI Würfelfenster"

	--[[Tooltip]]--
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipAzeriteArmor = "Anzeigen der Azeriterüstunginfos"
	DuffedUIConfigUILocalization.tooltipCursorAnchor = "Aktiviere Tooltip am Mauszeiger"
	DuffedUIConfigUILocalization.tooltipEnable = "Aktiviere den DuffedUI Tooltip"
	DuffedUIConfigUILocalization.tooltipGuildRanks = "Zeige die Gildenränge"
	DuffedUIConfigUILocalization.tooltipHealthbarHeight = "Lebensbalkengröße"
	DuffedUIConfigUILocalization.tooltipFontSize = "Schriftgröße"
	DuffedUIConfigUILocalization.tooltipHealthBarText = "Zeige Lebenspunkte auf dem Lebensbalken an"
	DuffedUIConfigUILocalization.tooltipHideInCombat = "Verstecke den Tooltip während des Kampfes"
	DuffedUIConfigUILocalization.tooltipIcons = "Zeige die Tooltipsymbole an"
	DuffedUIConfigUILocalization.tooltipTargetInfo = "Zeige Zielinformationen an"
	DuffedUIConfigUILocalization.tooltipInspectInfo = "Zeige die Gegenstandslevelanzeige im Tooltip (Shift halten)"
	DuffedUIConfigUILocalization.tooltipItemQualityBorder = "Zeige den Rand des Tooltips in Qualitätsfarbe an" 
	DuffedUIConfigUILocalization.tooltipPlayerTitles = "Zeige den Spielertitel an"
	DuffedUIConfigUILocalization.tooltipNpcID = "Zeige die NpcID an"
	DuffedUIConfigUILocalization.tooltipPlayerRoles = "Zeige die Spielerrollen in der Gruppe/Schlachtzug an"
	DuffedUIConfigUILocalization.tooltipSpellID = "Zeige die Zauber- und Gegenstands-ID im Tooltip"
	DuffedUIConfigUILocalization.tooltipShowMount = "Zeige das Mount des Spielers an (Strg halten für mehr Infos)"
	DuffedUIConfigUILocalization.tooltipFactionIcon = "Zeige das Fraktionssymbol im Tooltip"
	DuffedUIConfigUILocalization.tooltipCorruptionRank = "Zeige den Verderbnisrang im Tooltip"

	--[[Merchant]]--
	DuffedUIConfigUILocalization.merchant = "Händler"
	DuffedUIConfigUILocalization.merchantsellgrays = "Verkaufe graue Gegenstände automatisch"
	DuffedUIConfigUILocalization.merchantautorepair = "Repariere beschädigte Rüstung automatisch"
	DuffedUIConfigUILocalization.merchantsellmisc = "Verkaufe vordefinierte Gegenstände automatisch (Müll, NICHT grau)"
	DuffedUIConfigUILocalization.merchantautoguildrepair = "Aktiviere Reparatur über die Gildenbank"

	--[[Buttons]]--
	DuffedUIConfigUILocalization.option_button_reset = "|cffffd100Zurücksetzen|r"
	DuffedUIConfigUILocalization.option_button_load = "|cff00FF00" .. APPLY .. "|r"
	DuffedUIConfigUILocalization.option_button_close = "|cffFF0000" .. CLOSE .. "|r"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Einstellungen für jeden Charakter einzeln abspeichern"
	DuffedUIConfigUILocalization.option_resetchar = "Bist du dir sicher, dass du deine Charaktereinstellungen auf den Standardwert zurücksetzen willst?"
	DuffedUIConfigUILocalization.option_resetall = "Bist du dir sicher, dass du alle deine Einstellungen auf Standardwerte zurücksetzen willst?"
	DuffedUIConfigUILocalization.option_perchar = "Bist du dir sicher, dass du von, oder auf die \"für jeden Charakter einzeln abspeichern\"-Einstellungen wechseln möchtest?"
	DuffedUIConfigUILocalization.option_makeselection = "Um mit der Konfiguration fortfahren zu können, musst du erst eine Auswahl getroffen haben."
end
