if GetLocale() == "deDE" then
	-- general
	DuffedUIConfigUILocalization.general = "Allgemein"
	DuffedUIConfigUILocalization.generalautoscale = "Automatischer UI Ma\195\159stab"
	DuffedUIConfigUILocalization.generaluiscale = "UI Ma\195\159stab (wenn \"Automatischer UI Ma\195\159stab\" deaktiviert ist)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Setze Standard-Hintergrundfarbe der Panels"
	DuffedUIConfigUILocalization.generalbordercolor = "Setze Standard-Rahmenfarbe der Panels"
	DuffedUIConfigUILocalization.generalclasscolor = "Aktiviere Klassenfarben f\195\188r Textelemente"
	
	-- castbar
	DuffedUIConfigUILocalization.castbar = "Zauberleiste"
	DuffedUIConfigUILocalization.castbarenable = "Aktiviere Zauberleiste"
	DuffedUIConfigUILocalization.castbarpetenable = "Aktiviere Gef\195\164hrten-Zauberleiste"
	DuffedUIConfigUILocalization.castbarcbicons = "Aktiviere Zauberleisten-Symbole"
	DuffedUIConfigUILocalization.castbarcblatency = "Aktiviere Zauberleisten-Latenz"
	DuffedUIConfigUILocalization.castbarspark = "Aktiviere Zauberleisten-Spark"
	DuffedUIConfigUILocalization.castbarcolor = "Wähle Farbe der Zauberleiste"
	DuffedUIConfigUILocalization.castbarclasscolor = "Aktiviere Klassenfarben f\195\188r die Zauberleiste"
	DuffedUIConfigUILocalization.castbarcbticks = "Aktiviere Ticks f\195\188r kanalisierte Zauber."

	-- misc
	DuffedUIConfigUILocalization.misc = "Diverses"
	DuffedUIConfigUILocalization.misccombatanimation = "Aktviere Kampf beginnen/verlassen"
	DuffedUIConfigUILocalization.miscflightpoint = "Aktviere Flugpunktliste"
	DuffedUIConfigUILocalization.miscilvlcharacter = "Aktviere Gegenstandsstufenanzeige im Charakterbildschirm"
	DuffedUIConfigUILocalization.miscsComboenergybar = "Aktviere sCombo-Energieleiste"
	DuffedUIConfigUILocalization.miscsesenable = "Aktiviere Talenwechsel-Plugin"
	DuffedUIConfigUILocalization.miscsesenablegear = "Aktiviere Ausr\195\188stungsset-Schaltfl\195\164chen"
	DuffedUIConfigUILocalization.miscsesgearswap = "Aktviere automatischen Setwechsel bei Talentwechsel"
	DuffedUIConfigUILocalization.miscsesset1 = "Aktiviere Set f\195\188r erste Spezalisierung (muss ein Wer zwischen 1 - 10 sein)"
	DuffedUIConfigUILocalization.miscsesset2 = "Aktiviere Set f\195\188r zweite Spezalisierung (muss ein Wer zwischen 1 - 10 sein)"
	DuffedUIConfigUILocalization.miscgold = "Aktiviere gek\195\188rzte Goldanzeige im Chat"
	DuffedUIConfigUILocalization.miscloc = "Deaktiviere Loss of Control an den Aktionsleisten"
	DuffedUIConfigUILocalization.misclocation = "Aktviere / Deaktviere Ortsanzeige"
	DuffedUIConfigUILocalization.miscexp_rep = "Zeige Erfahrungs / XP-Panel an dem unteren Panel"
	DuffedUIConfigUILocalization.miscacm_screen = "Aktiviere automatische Screenshots bei Achievments"
	DuffedUIConfigUILocalization.miscclickcast = "Aktiviere Click2Cast-Plugin"

	-- skins
	DuffedUIConfigUILocalization.skins = "AddOn-Skins"
	DuffedUIConfigUILocalization.skinsblizzardreskin = "Gestalte Blizzard-Frames in DuffedUI-Design um"
	DuffedUIConfigUILocalization.skinscalendarevent = "Deaktiviere die Kalendareventtexturen"

	-- classtimer
	DuffedUIConfigUILocalization.classtimer = "Classtimer"
	DuffedUIConfigUILocalization.classtimerenable = "Aktiviere Classtimer"
	DuffedUIConfigUILocalization.classtimerspark = "Aktiviere Spark"
	DuffedUIConfigUILocalization.classtimertargetdebuffs = "Aktviere Zieldebuffs"
	DuffedUIConfigUILocalization.classtimerplayercolor = "Setze Spielerfarbe"
	DuffedUIConfigUILocalization.classtimertargetbuffcolor = "Setze Zielbufffarbe"
	DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "Setze Zieldebufffarbe"
	DuffedUIConfigUILocalization.classtimertrinketcolor = "Setze Schmuckst\195\188ckfarbe"
	DuffedUIConfigUILocalization.classtimerheight = "Höhe der ClassTimer-Leiste"
	DuffedUIConfigUILocalization.classtimerspacing = "Zwischenraum der ClassTimer-Leisten"
	DuffedUIConfigUILocalization.classtimerseparator = "Aktiviere Zauberabgrenzung"
	DuffedUIConfigUILocalization.classtimerseparatorcolor = "Wähle Abgrenzungsfarbe"
	DuffedUIConfigUILocalization.classtimertargetdebuffsenable = "Aktiviere / Deaktiviere Debuffleisten"

	-- duffed
	DuffedUIConfigUILocalization.duffed = "Duffed"
	DuffedUIConfigUILocalization.duffedbossicons = "Aktviere Nummer anstatt der Bossicons"
	DuffedUIConfigUILocalization.duffeddrinkannouncement = "Aktviere Trinkwarnung"
	DuffedUIConfigUILocalization.duffedsayinterrupt = "Aktviere Unterbrechungsansage"
	DuffedUIConfigUILocalization.duffedannouncechannel = "Setze Kanal f\195\188r Warnung (|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r oder |cffC41F3BINSTANCE_CHAT|r)"
	DuffedUIConfigUILocalization.duffeddispelannouncement = "Aktviere Reinigungswarnnung"
	DuffedUIConfigUILocalization.duffedspellannounce = "Aktiviere Aurawarnung"
		
	-- drunes
	DuffedUIConfigUILocalization.runes = "|cffC41F3Bd|rRunes"
	DuffedUIConfigUILocalization.runesenable = "Aktiviere alternative Runenanzeige f\195\188r Todesritter"
	DuffedUIConfigUILocalization.runesbarlength = "Setze Länge der Runen"
	DuffedUIConfigUILocalization.runesbarthickness = "Setze Dicke der Runen"
	DuffedUIConfigUILocalization.runesdisplayrpbar = "Aktiviere Runenmachtanzeige unterhalb der Runen"
	DuffedUIConfigUILocalization.runesdisplayrpbartext = "Aktiviere Runenmachttext"
	DuffedUIConfigUILocalization.runesrpbarthickness = "Setze Dicke der Runenmachtanzeige"
	DuffedUIConfigUILocalization.runeshideooc = "Verstecke dRunes ausserhalb des Kampfes"
	DuffedUIConfigUILocalization.runesgrowthdirection = "Setze Wachstumsrichtung der Runen (VERTICAL or HORIZONTAL)"

	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Namensplakette"
	DuffedUIConfigUILocalization.nameplateenable = "Aktiviere Namensplaketten"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "Aktiviere Bedrohungs-Feature, wechselt automatisch je nach Rolle"
	DuffedUIConfigUILocalization.nameplateshowhealth = "Aktiviere Anzeige der Lebenspunkte in der Namensplakette"
	DuffedUIConfigUILocalization.nameplatecombat = "Zeige nur die Feind-Namenplaketten w\195\164hrend eines Kampfes"
	DuffedUIConfigUILocalization.nameplategoodcolor = "Aktiviere \"Gute\" Bedrohungs-Anzeige, variiert je nach Rolle"
	DuffedUIConfigUILocalization.nameplatebadcolor = "Aktiviere \"Schlechte\" Bedrohungs-Anzeige, variiert je nach Rolle"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "Aktiviere Einf\195\164rbung von Verlust/Gewinn der Bedrohung"
	DuffedUIConfigUILocalization.nameplatedebuffs = "Aktviere Debuff-Anzeige"
	DuffedUIConfigUILocalization.nameplateheight = "Setze H\195\182he der Namensplaketten (Standard = 7)"
	DuffedUIConfigUILocalization.nameplatewidth = "Setze Breite der Namensplaketten (Standard = 110)"
	DuffedUIConfigUILocalization.nameplateshowcastbarname = "Zeige zus\195\164tzlich den gewirkten Zauber unter der Namensplakette"
	DuffedUIConfigUILocalization.nameplatenameabbrev = "Zeige abgek\195\188rzte Namen"
	DuffedUIConfigUILocalization.nameplateaurassize = "Setze Auragr\195\182\195\159e (Standard = 20)"

	-- merchant
	DuffedUIConfigUILocalization.merchant = "H ändler"
	DuffedUIConfigUILocalization.merchantsellgrays = "Verkaufe automatisch graue Gegenst\195\164nde"
	DuffedUIConfigUILocalization.merchantautorepair = "Repariere automatisch besch\195\164digte R\195\188stung"
	DuffedUIConfigUILocalization.merchantsellmisc = "Verkaufe automatisch vordefinierte Gegenst\195\164nde (M\195\188ll, NICHT grau)"
	DuffedUIConfigUILocalization.merchantautoguildrepair = "Aktiviere Reperatur \195\188ber die Gildenbank"

	-- bags
	DuffedUIConfigUILocalization.bags = "Taschen"
	DuffedUIConfigUILocalization.bagsenable = "Aktiviere alle-in-einer Ansicht"
	DuffedUIConfigUILocalization.bagsbpr = "Setze Schaltfl\195\164chen pro Reihe"
	DuffedUIConfigUILocalization.bagsmoveable = "Aktiviere bewegbare Taschen"
	DuffedUIConfigUILocalization.bagsscale = "Sklaierung für Bank und Taschen"
	DuffedUIConfigUILocalization.bagsspacing = "Zwischenraum zwischen Taschenslots"
	DuffedUIConfigUILocalization.bagsbuttonsize = "Größe der Slots"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "Data Text"
	DuffedUIConfigUILocalization.datatexttime24 = "Aktiviere 24-Stunden Zeitanzeige"
	DuffedUIConfigUILocalization.datatextlocaltime = "Benutze lokale Uhrzeit, anstatt die Server-Uhrzeit"
	DuffedUIConfigUILocalization.datatextbattleground = "Aktiviere Schlachtfeld-Statistiken"
	DuffedUIConfigUILocalization.datatextguild = "Gilden-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatext_arp = "R\195\188stungsdurchdringung-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextsystem = "Speicher-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextbags = "Taschen-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextfontsize = "Schriftgr\195\182\195\159e des Texts"
	DuffedUIConfigUILocalization.datatextfps_ms = "Latenz und FPS Position(0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextarmor = "R\195\188stung-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextavd = "Vermeidungs-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextpower = "Angriffskraft-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthaste = "Angriffstempo-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextfriends = "Freunde-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextwowtime = "Zeit-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextgold = "Gold-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextcrit = "Kritisch-Position, in % (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextdur = "R\195\188stungs-Haltbarkeit-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Micro-Menu\195\188-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthit = "Trefferwertung-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextmastery = "Meisterschaft-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexttalent = "Zeige Talente (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Ruf zu den Waffen & Dungeons (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextsmf = "System-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthonorablekills = "Ehrenhafte T\195\182tungen Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextdodge = "Ausweichen-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextparry = "Parrieren-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextblock = "Blocken-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthonor = "Ehrenpunkte-Position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextprofession = "Beruf-Position (0 zum deaktivieren)"

	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesenable = "Aktiviere DuffedUI Einheitenfenster"
	DuffedUIConfigUILocalization.unitframeslayout = "Setze UF-Layout (1, 2 oder 3, Standard = 2)"
	DuffedUIConfigUILocalization.unitframespercent = "Aktiviere Prozentanzeige neben Spieler & Ziel"
	DuffedUIConfigUILocalization.unitframeshealthbarcolor = "Setze Heil-Leisten-Farbe"
	DuffedUIConfigUILocalization.unitframesdeficitcolor = "Setze Defizit-Farbe"
	DuffedUIConfigUILocalization.unitframesColorGradient = "Aktiviere Farbverlauf f\195\188r die Heil-Leiste"
	DuffedUIConfigUILocalization.unitframesframewidth = "Setze Rahmenweite"
	DuffedUIConfigUILocalization.unitframestotandpetlines = "Aktiviere Linien f\195\188r Haustier & ToT (nur Layout 1 & 2)"
	DuffedUIConfigUILocalization.unitframesportraitstyle = "Setze Portraitstyle (MODEL oder ICON, nur Layout 1 & 2)"
	DuffedUIConfigUILocalization.unitframeslargefocus = "Aktiviere gro\195\159e Fokus-Rahmen (nur Layout 1)"
	DuffedUIConfigUILocalization.unitframesbuffrows = "Setze Buffreihen"
	DuffedUIConfigUILocalization.unitframesdebuffrows = "Setze Debuffreihen"
	DuffedUIConfigUILocalization.unitframesvengeancebar = "Aktiviere Vergeltungsleiste anstatt der Bedrohungsleiste"
	DuffedUIConfigUILocalization.unitframespowerClasscolored = "Aktiviere Klassenfarben spezifische Energieleiste"
	DuffedUIConfigUILocalization.unitframesfocusdebuffs = "Aktiviere Schwächungszauber am Fokus"
	DuffedUIConfigUILocalization.unitframessComboenable = "Aktiviere sCombo-Plugin"
	DuffedUIConfigUILocalization.unitframessComboenergybar = "Aktiviere Energieleiste f\195\188r sCombo"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "F\195\164rbe die Gesundheitsleiste nach Feindlichkeit ein (f\195\188r PVP)"
	DuffedUIConfigUILocalization.unitframesauratimer = "Aktiviere Timer f\195\188r Auren"
	DuffedUIConfigUILocalization.unitframesauratextscale = "Textgr\195\182\195\159e f\195\188r Auren"
	DuffedUIConfigUILocalization.unitframestargetauras = "Aktiviere Ziel-Auren"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "Niedriger Mana Indikator (alle Mana-Klassen)"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "Aktiviere Kraft-Anzeige nur an Feind"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Aktiviere Ziel-des-Ziels Debuff (Hohe Aufl\195\182sung)"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "Zeige gesamte Gesundheit/Energie"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Aktiviere glatte Leisten"
	DuffedUIConfigUILocalization.unitframescharportrait = "Aktviere Charakterportraits"
	DuffedUIConfigUILocalization.unitframesunicolor = "Aktiviere einheitliches Farbmotiv (graue Lebensleiste)"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Kampf-Feedback auf Spieler und Ziel"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Aktiviere Aggro-Anzeige an sich selbst"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Aktiviere healcomm"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Zeige nur eigen verursachte Debuffs des Ziels"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "Aktiviere fokussieren des Ziels"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Zeige Statusleiste"
	DuffedUIConfigUILocalization.unitframesbordercolor = "Setze Standard Rahmenfarbe der Panels"
	DuffedUIConfigUILocalization.unitframesruneofpower = "Aktiviere Rune der Macht-Leiste"
	DuffedUIConfigUILocalization.unitframesfader = "Aktiviere Fader für Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesminalpha = "Setze Minimumwert für Fader (Standard = 0.1)"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Aktiviere \"Geschw\195\164chte Seele\"-Leisten Ank\195\188ndigung (Priester)"
	DuffedUIConfigUILocalization.unitframesclassbar = "Aktiviere Klassenleisten"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "Zeige Druiden Manaleiste auch in B\195\164ren/Katzen-Form"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "Zeige Druiden \"Wildpilz\"-Leiste auch in Gleichgewicht oder Wiederherstellungs Spezialisierung"
	DuffedUIConfigUILocalization.unitframesfocusbutton = "Aktiviere Fokusbutton f\195\188r Spieler- / Fokusfenster"
	DuffedUIConfigUILocalization.unitframestotdbsize = "Wähle Größe für Debuffs von Ziel des Ziels"

	-- raid frames
	DuffedUIConfigUILocalization.raid = "Schlachtzugfenster"
	DuffedUIConfigUILocalization.raidenable = "Aktiviere DuffedUI-Schlachtzugsfenster"
	DuffedUIConfigUILocalization.raidshowrange = "Aktiviere Alpha Gruppen/Raid Entfernungs Anzeige"
	DuffedUIConfigUILocalization.raidraidalphaoor = "Alpha auf Gruppen/Raid Einheiten au\195\159er Reichweite"
	DuffedUIConfigUILocalization.raidshowsymbols = "Zeige Symbole an Gruppe/Raid"
	DuffedUIConfigUILocalization.raidaggro = "Aktiviere Aggro-Anzeige an Gruppe/Raid"
	DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "Aktiviere Aura-Beobachtung im PVE Raid (nur Grid)"
	DuffedUIConfigUILocalization.raidgridhealthvertical = "Zeige Gesundheitsleiste senkrecht des Grid Layouts"
	DuffedUIConfigUILocalization.raidgridscale = "Grid Ma\195\159stab"
	DuffedUIConfigUILocalization.raidgridvertical = "Zeige Raid-Gruppen senkrecht in Grid an"
	DuffedUIConfigUILocalization.raidshowraidpets = "Zeige Haustiere in DuffedUI Raid Frames"
	DuffedUIConfigUILocalization.raidshowgroupresurrect = "Zeige Auferstehungs Icon im Raid-Frame"
	DuffedUIConfigUILocalization.raidshowplayerinparty = "Zeige sich selbst in der Gruppe"
	DuffedUIConfigUILocalization.raidgridonly = "Aktiviere Grid-Modus f\195\188r das Heiler-Layout"
	DuffedUIConfigUILocalization.raidshowboss = "Aktiviere Boss Unit Frames"
	DuffedUIConfigUILocalization.raidarena = "Aktiviere Arena unit frames"
	DuffedUIConfigUILocalization.raidmaintank = "Aktiviere Haupt-Tank"
	DuffedUIConfigUILocalization.raidmainassist = "Aktiviere Haupt-Assistent"
	DuffedUIConfigUILocalization.raidframewidth = "Setze Breite des Einheitenfenster"
	DuffedUIConfigUILocalization.raidframeheight = "Setze Höhe des Einheitenfenster"
	DuffedUIConfigUILocalization.raidcolumnSpacing = "Abstand der Einheitenfenster"
	

	-- loot
	DuffedUIConfigUILocalization.loot = "Beute"
	DuffedUIConfigUILocalization.lootlootframe = "Aktiviere Beutefenster"
	DuffedUIConfigUILocalization.lootautogreed = "Aktiviere automatisches Gier w\195\188rfeln f\195\188r graue Gegenst\195\164nde auf max Lvl"
	DuffedUIConfigUILocalization.lootrolllootframe = "Aktiviere W\195\188rfelfenster"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "Einladung"
	DuffedUIConfigUILocalization.inviteautoaccept = "Aktiviere Auto-Einladung (Freunde und Gildenkollegen)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipenable = "Aktiviere Tooltip"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Verstecke Tooltip w\195\164hrend des Kampfes"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Verstecke Tooltip auf Aktionsleisten-Buttons"
	DuffedUIConfigUILocalization.tooltiphideuf = "Verstecke Tooltip auf Unit Frames"
	DuffedUIConfigUILocalization.tooltipcursor = "Aktiviere Tooltip am Cursor"
	DuffedUIConfigUILocalization.tooltipids = "Zeige Zauber-/Gegenstands-ID im Tooltip"
	DuffedUIConfigUILocalization.tooltipilvl = "Aktiviere Gegenstandslevel-Anzeige im Tooltip"
	DuffedUIConfigUILocalization.tooltipitemcompare = "Aktiviere Itemvergleich"
	DuffedUIConfigUILocalization.tooltipenablecaster = "Aktiviere Castername für Buffs / Debuffs im Tooltip"
	 
	-- error
	DuffedUIConfigUILocalization.error = "Fehlermeldung"
	DuffedUIConfigUILocalization.errorenable = "Verstecke Fehlermeldung-Spamming in der Mitte deines Bildschirms"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Aktionsleiste"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "Verstecke Haltungs- oder Totemleiste"
	DuffedUIConfigUILocalization.actionbarshowgrid = "Zeige immer Grid an der Aktionsleiste"
	DuffedUIConfigUILocalization.actionbarenable = "Aktiviere DuffedUI Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarrb = "Aktiviere rechte Leiste bei mouseover"
	DuffedUIConfigUILocalization.actionbarhotkey = "Zeige Hotkey auf den Schaltfl\195\164chen"
	DuffedUIConfigUILocalization.actionbarssmo = "Zeige Haltungs- oder Totemleiste bei mouseover"
	DuffedUIConfigUILocalization.actionbarrbn = "Anzahl der unteren Aktionsleisten (1 oder 2)"
	DuffedUIConfigUILocalization.actionbarrn = "Anzahl der rechten Aktionsleisten (0, 1, 2 or 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Gr\195\182\195\159e der Hauptaktionsschaltfl\195\164chen"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Abstand zwischen der Hauptaktionsschaltfl\195\164chen"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Gr\195\182\195\159e der Haustier-/Haltungsleistenschaltfl\195\164chen"
	DuffedUIConfigUILocalization.actionbarownshdbar = "Benutze eine leere Leiste f\195\188r \"Schattentanz\" (Schurke) anstelle der Verstolenheits-Leiste"
	DuffedUIConfigUILocalization.actionbarownmetabar = "Benutze eine leere Leiste f\195\188r \"Metamorphose\" (Hexenmeister) anstelle der Hauptleiste"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "Benutze eine leere Leiste f\195\188r jede Haltung (Krieger) anstelle der Hauptleiste"
	DuffedUIConfigUILocalization.actionbarmacro = "Zeige Makrotext auf der Aktionsleiste"
	DuffedUIConfigUILocalization.actionbarbutton2 = "Verstecke die Schaltfl\195\164chen zwischen dem Data Text-Panel(funktioniert nur ohne \"actionbarswap\")"
	DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "Aktiviert mouseover f\195\188r rechte Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarswap = "Wechsel Bar 3 mit Bar 1"
	DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "Setze Begleiterleiste immer sichtbar"
	DuffedUIConfigUILocalization.actionbarshapeshiftborder = "Aktiviere Haltungsleistenrahmen"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "Aktiviere mouseover f\195\188r Haltungsleiste"
	DuffedUIConfigUILocalization.actionbarverticalshapeshift = "Aktiviere vertikale Haltungsleiste"
	DuffedUIConfigUILocalization.actionbarborderhighlight = "Aktiviere Proc-Hervorhebung von DuffedUI (Standard = disabled)"
	DuffedUIConfigUILocalization.actionbarlayout = "W\195\164hle Aktionsleistenlayout (1 oder 2, Standard = 1)"
	DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "Setze Haustierleiste horizontal"
	 
	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Abklingzeit"
	DuffedUIConfigUILocalization.cooldownenable = "Aktiviere Abklingzeit-Zahlen auf den Schalfl\195\164chen"
	DuffedUIConfigUILocalization.cooldowntreshold = "Wechsel Abklingzeit-Zahlen in Rot ab dem Wert X"

	-- raidcooldowns
	DuffedUIConfigUILocalization.rcd = "Raid Abklingzeit"
	DuffedUIConfigUILocalization.rcdenable = "Aktiviere Raid Abklingzeiten"
	DuffedUIConfigUILocalization.rcdraid = "Aktiviere Abklingzeiten Ank\195\188ndigungen f\195\188r Raids"
	DuffedUIConfigUILocalization.rcdparty = "Aktiviere Abklingzeiten Ank\195\188ndigungen f\195\188r Gruppen"
	DuffedUIConfigUILocalization.rcdarena = "Aktiviere Abklingzeiten Ank\195\188ndigungen f\195\188r Arenas"

	-- spellcooldowns
	DuffedUIConfigUILocalization.scd = "Zauber Abklingzeit"
	DuffedUIConfigUILocalization.scdenable = "Aktiviere das Zauber Abklingzeit-Plugin"
	DuffedUIConfigUILocalization.scdsize = "Setze Gr\195\182\195\159e der Icons (Standard = 36)"
	DuffedUIConfigUILocalization.scdspacing = "Setze Abstand der Icons (Standard = 10)"
	DuffedUIConfigUILocalization.scdfade = "Setze Abklingen (Werte: 0 eine Farbe, 1 Gr\195\188n nach Rot, 2 Rot nach Gr\195\188n)"
	DuffedUIConfigUILocalization.scddisplay = "Setze Anzeige der Abklingzeit (Werte: SPIRAL oder STATUSBAR, Standard = STATUSBAR)"
	DuffedUIConfigUILocalization.scddirection = "Setze Richtung der Abklingzeit-Anzeige (Werte: HORIZONTAL oder VERTICAL, Standard = HORIZONTAL)"
	DuffedUIConfigUILocalization.scdfsize = "Setze Textgr\195\182\195\159e"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "Chat"
	DuffedUIConfigUILocalization.chatenable = "Aktiviere DuffedUI Chat"
	DuffedUIConfigUILocalization.chatwhispersound = "Spiele einen Ton bei Empfang einer privaten Nachricht"
	DuffedUIConfigUILocalization.chatlbackground = "Aktiviere Chathintergrund (links)"
	DuffedUIConfigUILocalization.chatrbackground = "Aktiviere Chathintergrund (rechts)"
	DuffedUIConfigUILocalization.chatfading = "Aktviere ausblenden des Chats"
	DuffedUIConfigUILocalization.chattextright = "Textausrichtung rechts f\195\188r den rechten Chatframe"

	-- buff
	DuffedUIConfigUILocalization.auras = "Auras"
	DuffedUIConfigUILocalization.aurasplayer = "Aktiviere DuffedUI Buff/Debuff Frames"
	DuffedUIConfigUILocalization.aurasconsolidate = "Aktiviere fundierte Buffs"
	DuffedUIConfigUILocalization.aurasflash = "Aktiviere aufblitz Animation auf Auren mit weniger als 30 Sekunden"
	DuffedUIConfigUILocalization.aurasclassictimer = "Zeige klassischen Timer auf Spieler Auren"
	DuffedUIConfigUILocalization.aurasbuffnotice = "Aktiviere BuffNotice"
	DuffedUIConfigUILocalization.auraswarning = "Aktiviere Warnton f\195\188r BuffNotice"
	DuffedUIConfigUILocalization.aurasbufftracker = "Aktiviere Bufftracker-Plugin"
	DuffedUIConfigUILocalization.auraswrap = "Wähle Umbruch der Stärkungszauberleiste (Standard = 18)"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Zur\195\188cksetzen"
	DuffedUIConfigUILocalization.option_button_load = "\195\156bernehmen"
	DuffedUIConfigUILocalization.option_button_close = "Schlie\195\159en"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Setze Einstellungen pro Charakter"
	DuffedUIConfigUILocalization.option_resetchar = "Bist du dir sicher das du deine Charakter-Einstellungen auf den Standardwert zur\195\188cksetzen willst?"
	DuffedUIConfigUILocalization.option_resetall = "Bist du dir sicher das du alle deine Einstellungen auf Standard zur\195\188cksetzen willst?"
	DuffedUIConfigUILocalization.option_perchar = "Bist du dir sicher das du von oder auf \"pro Charakter\"-Einstellungen wechseln m\195\182chtest?"
	DuffedUIConfigUILocalization.option_makeselection = "Um die Konfiguration fort fahren zu k\195\182nnen musst du erst eine Auswahl treffen."
end