if GetLocale() == "deDE" then
	-- general
	DuffedUIConfigUILocalization.general = "Allgemein"
	DuffedUIConfigUILocalization.generalautoscale = "Aktiviere 'Automatischen UI Maßstab'"
	DuffedUIConfigUILocalization.generaluiscale = "UI Maßstab (wenn 'Automatischer UI Maßstab' deaktiviert ist)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Setze Standard-Hintergrundfarbe der Panels"
	DuffedUIConfigUILocalization.generalbordercolor = "Setze Standard-Rahmenfarbe der Panels"
	DuffedUIConfigUILocalization.generalclasscolor = "Aktiviere Klassenfarben für Textelemente"

	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesenable = "Aktiviere die DuffedUI Einheitenfenster"
	DuffedUIConfigUILocalization.unitframeslayout = "Wähle Dein UF-Layout (1, 2 oder 3, Standard = 2)"
	DuffedUIConfigUILocalization.unitframesfader = "Aktiviere 'Verblassen' für Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesminalpha = "Setze den Minimumwert für das 'Verblassen' der Einheitenfenster (Standard = 0.1)"
	DuffedUIConfigUILocalization.unitframespercent = "Aktiviere eine Prozentanzeige neben Spieler & Ziel"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Aktiviere weiche Übergänge bei den Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesunicolor = "Aktiviere ein einheitliches Farbmotiv (graue Lebensleiste)"
	DuffedUIConfigUILocalization.unitframeshealthbarcolor = "Setze die Farbe der Heileiste"
	DuffedUIConfigUILocalization.unitframesdeficitcolor = "Setze die Farbe bei Lebensverlust"
	DuffedUIConfigUILocalization.unitframesColorGradient = "Aktiviere Farbverlauf für die Heilleiste"
	DuffedUIConfigUILocalization.unitframescharportrait = "Aktviere Charakterportraits am Spieler- und Zielframe"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Aktiviere 'Geschwächte Seele' Leiste (Priester ->Rote Leiste)"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Zeige die Statusleiste"
	DuffedUIConfigUILocalization.unitframesclassbar = "Aktiviere die Klassenleisten"
	DuffedUIConfigUILocalization.unitframesruneofpower = "Aktiviere die 'Rune der Macht' Leiste"
	DuffedUIConfigUILocalization.unitframestargetauras = "Aktiviere Auren am Einheitenfenster des Ziels"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Zeige nur deine Schwächungszauber am Einheitenfester des Ziels"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Zeige Kampf-Feedback auf dem Spieler- und Zieleinheitenfenster"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Aktiviere die 'Ankommende Heilungsleiste'"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Aktiviere die Anzeige von Aggro am Spielereinheitenfenster"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Aktiviere Ziel-des-Ziels Schwächungszauber (Nur Hohe Grtafikauflösung!)"
	DuffedUIConfigUILocalization.unitframestotdbsize = "Wähle die Größe für Schwächungszauber vom 'Ziel des Ziels' Einheitenfester"
	DuffedUIConfigUILocalization.unitframesfocusdebuffs = "Aktiviere Schwächungszauber am Fokuseinheitenfenster"
	DuffedUIConfigUILocalization.unitframesfocusbutton = "Aktiviere den Fokusbutton für Spieler- / Fokuseinheitenfenster"
	DuffedUIConfigUILocalization.unitframesattached = "Verbinde die Klassenleisten und die Einheitenfenster"
	DuffedUIConfigUILocalization.unitframesoocHide = "Verstecke die Klassenleisten, wenn Du nicht im Kampf bist"
	DuffedUIConfigUILocalization.unitframesplayermodel = "Setze den Portraitstil (Icon oder Model, Standard => Model)"

	-- chat
	DuffedUIConfigUILocalization.chat = "Chat"
	DuffedUIConfigUILocalization.chatenable = "Aktiviere den DuffedUI Chat"
	DuffedUIConfigUILocalization.chatwhispersound = "Spiele einen Ton bei Empfang einer privaten Nachricht"
	DuffedUIConfigUILocalization.chatlbackground = "Aktiviere Chathintergrund (links)"
	DuffedUIConfigUILocalization.chatrbackground = "Aktiviere Chathintergrund (rechts)"
	DuffedUIConfigUILocalization.chatfading = "Aktviere ausblenden des Chats"
	DuffedUIConfigUILocalization.chattextright = "Textausrichtung rechts für den rechten Chatframe"

	-- castbar
	DuffedUIConfigUILocalization.castbar = "Zauberleiste"
	DuffedUIConfigUILocalization.castbarenable = "Aktiviere Zauberleiste"
	DuffedUIConfigUILocalization.castbarpetenable = "Aktiviere Gefährten-Zauberleiste"
	DuffedUIConfigUILocalization.castbarcbicons = "Aktiviere Zauberleisten-Symbole"
	DuffedUIConfigUILocalization.castbarcblatency = "Aktiviere Zauberleisten-Latenz"
	DuffedUIConfigUILocalization.castbarspark = "Aktiviere Zauberleisten-Spark"
	DuffedUIConfigUILocalization.castbarcolor = "Wähle Farbe der Zauberleiste"
	DuffedUIConfigUILocalization.castbarclasscolor = "Aktiviere Klassenfarben für die Zauberleiste"
	DuffedUIConfigUILocalization.castbarcbticks = "Aktiviere Ticks für kanalisierte Zauber."
	DuffedUIConfigUILocalization.castbarplayerwidth = "Setze Breite der Zauberleiste."

	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Namensplaketten"
	DuffedUIConfigUILocalization.nameplateenable = "Aktiviere die DuffedUI Namensplaketten"
	DuffedUIConfigUILocalization.nameplatedebuffs = "Aktviere die Anzeige der Schwächungszauber"
	DuffedUIConfigUILocalization.nameplatewidth = "'Breite' der Namensplaketten (Standard = 110)"
	DuffedUIConfigUILocalization.nameplateheight = "'Höhe' der Namensplaketten (Standard = 7)"
	DuffedUIConfigUILocalization.nameplateauraswidth = "'Breite' der Schwächungszaubersymbole"
	DuffedUIConfigUILocalization.nameplateaurasheight = "'Höhe' der Schwächungszaubersymbole"
	DuffedUIConfigUILocalization.nameplateMaxDebuffs = "'Anzahl' der angezeigten Schwächungszauber (Standard = 5)"
	DuffedUIConfigUILocalization.nameplateCastHeight = "'Höhe' der Zauberleiste an den Namensplaketten"
	DuffedUIConfigUILocalization.nameplateShowComboPoints = "Zeige deine Kombopunkte an den Namensplaketten"

	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarenable = "Aktiviere die DuffedUI Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarrightbarvertical = "Setze die rechte Leiste auf 'horizontal'"
	DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "Aktiviere die rechte Leiste per 'mouseover'"
	DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "Setze die Begleiterleiste auf 'horizontal'"
	DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "Setze die Begleiterleiste auf 'immer sichtbar'"
	DuffedUIConfigUILocalization.actionbarverticalshapeshift = "Setze die Haltungsleiste auf 'vertikal'"
	DuffedUIConfigUILocalization.actionbarhotkey = "Zeige die Hotkeys auf den Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarmacro = "Zeige den Makrotext auf den Aktionsleisten"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Einstellung der Größe von den Aktionsleistenknöpfen"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Abstand zwischen den Aktionsleistenknöpfen"
	DuffedUIConfigUILocalization.actionbarshapeshiftborder = "Aktiviere den Rahmen der Haltungsleisten"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "Aktiviere die Haltungsleiste per 'mouseover'"
	DuffedUIConfigUILocalization.actionbarborderhighlight = "Aktiviere die Proc-Hervorhebung auf den Aktionsleisten (Standard = Deaktiviert)"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Größe der Begleiter- und Haltungsleistenschaltflächen"
	DuffedUIConfigUILocalization.actionbarsidebars = "Aktiviere die Sidebars an den Chatframes per 'mouseover'"

	-- raid frames
	DuffedUIConfigUILocalization.raid = "Schlachtzugfenster"
	DuffedUIConfigUILocalization.raidenable = "Aktiviere die DuffedUI Schlachtzugsfenster"
	DuffedUIConfigUILocalization.raidshowboss = "Aktiviere Einheitenfenster für Bosse"
	DuffedUIConfigUILocalization.raidarena = "Aktiviere Einheitenfenster für die Arena"
	DuffedUIConfigUILocalization.raidmaintank = "Aktiviere die 'Haupt-Tank' Anzeige"
	DuffedUIConfigUILocalization.raidmainassist = "Aktiviere die 'Haupt-Assistent' Anzeige"
	DuffedUIConfigUILocalization.raidshowrange = "Aktiviere die Gruppen- und Raid Entfernungsanzeige"
	DuffedUIConfigUILocalization.raidraidalphaoor = "Sichtbarkeit der Gruppen- und Schlachtzugeinheiten, die ausser Reichweite sind"
	DuffedUIConfigUILocalization.raidshowsymbols = "Zeige Symbole auf Gruppen- und Schlachtzugeinheiten"
	DuffedUIConfigUILocalization.raidaggro = "Aktiviere die Anzeige von Aggro auf den Gruppen- und Raidfenstern"
	DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "Aktiviere die Aurenbeobachtung im PVE Schlachtzug"
	DuffedUIConfigUILocalization.raidshowraidpets = "Zeige die Begleiterfenster im Schlachtzug an."
	DuffedUIConfigUILocalization.raidshowplayerinparty = "Füge Dein Einheitenfester der Gruppe hinzu"
	DuffedUIConfigUILocalization.raidframewidth = "Einstellung für die Breite der Einheitenfenster"
	DuffedUIConfigUILocalization.raidframeheight = "Einstellung für die Höhe der Einheitenfenster"
	DuffedUIConfigUILocalization.raidpointer = "Aktiviere Richtungspfeile für Deine Schlachtzugsmitglieder"

	-- datatext
	DuffedUIConfigUILocalization.datatext = "Datatext"
	DuffedUIConfigUILocalization.datatextarmor = "Position der 'Rüstungsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextavd = "Position der 'Vermeidungsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextbags = "Position der 'Taschenanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextbattleground = "Aktviere die 'Statistikanzeige' auf den 'Schlachtfeldern'"
	DuffedUIConfigUILocalization.datatextblock = "Position der 'Blockenanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextbonusarmor = "Position der 'Bonus Rüstungsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Position der 'Ruf zu den Waffen Anzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextcrit = "Position der 'Kritische Trefferanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextdodge = "Position der 'Ausweichenanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextdur = "Position der 'Haltbarkeitsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextfriends = "Position der 'Freundschaftsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextgold = "Position der 'Goldanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextguild = "Position der 'Gildenanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthaste = "Position der 'Schnelligkeitsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthonor = "Position der 'Ehrepunkteanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexthonorablekills = "Position der 'Tötungsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextleech = "Position der 'Lebensraubanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextmastery = "Position der 'Meisterschaftsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Position der 'Mikromenüanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextmultistrike = "Position der 'Mehrfachschlaganzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextparry = "Position der 'Parrierenanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextpower = "Position der 'Kraftanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextprofession = "Position der 'Berufsanzeige' position (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextsmf = "Position der 'Systemanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexttalent = "Position der 'Talenteanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextversatility = "Position der 'Vielseitigkeitsanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatextwowtime = "Position der 'Zeitanzeige' (0 zum deaktivieren)"
	DuffedUIConfigUILocalization.datatexttime24 = "Aktiviere 24h Zeitanzeige"
	DuffedUIConfigUILocalization.datatextlocaltime = "Zeige die lokale Zeit, anstatt der Server Zeit"
	DuffedUIConfigUILocalization.datatextfontsize = "Schriftgröße des Datatexts"

	-- skins
	DuffedUIConfigUILocalization.skins = "AddOn-Skins"
	DuffedUIConfigUILocalization.skinsblizzardreskin = "Zeige die Blizzard eigenen Fenster im Stile von DuffedUI an"
	DuffedUIConfigUILocalization.skinscalendarevent = "Deaktiviere die Texturen, der Events, im Kalender"

	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Abklingzeiten"
	DuffedUIConfigUILocalization.cooldownenable = "Aktiviere DuffedUI Abklingzeiten"
	DuffedUIConfigUILocalization.cooldowntreshold = "Färbe die Abklingszeiten beim erreichen von Wert X 'rot'"
	DuffedUIConfigUILocalization.cooldownicdenable = "Aktiviere Gegenstandsabklingzeiten"
	DuffedUIConfigUILocalization.cooldownrcdenable = "Aktiviere Abklingzeiten im Raid"
	DuffedUIConfigUILocalization.cooldownrcdraid = "Aktiviere Ankündigungen der Abklingzeiten für Raids"
	DuffedUIConfigUILocalization.cooldownrcdparty = "Aktiviere Ankündigungen der Abklingzeiten für die Gruppe"
	DuffedUIConfigUILocalization.cooldownrcdarena = "Aktiviere Ankündigungen der Abklingzeiten in der Arena"
	DuffedUIConfigUILocalization.cooldownscdenable = "Aktiviere das Zauber Abklingzeit-Plugin"
	DuffedUIConfigUILocalization.cooldownscdfsize = "Schritgröße der Zauberabklingzeiten"
	DuffedUIConfigUILocalization.cooldownscdsize = "Größe der Icons (Standard = 28)"
	DuffedUIConfigUILocalization.cooldownscdspacing = "Abstand der Icons (Standard = 10)"
	DuffedUIConfigUILocalization.cooldownscdfade = "Verblassen der Abklingen (Werte: 0 eine Farbe, 1 Grün nach Rot, 2 Rot nach Grün)"

	-- classtimer
	DuffedUIConfigUILocalization.classtimer = "Classtimer"
	DuffedUIConfigUILocalization.classtimerenable = "Aktiviere den 'Classtimer' an den Einheitenfestern"
	DuffedUIConfigUILocalization.classtimerspark = "Aktiviere den 'Funken' an den Classtimern"
	DuffedUIConfigUILocalization.classtimertargetdebuffs = "Aktviere Zieldebuffs"
	DuffedUIConfigUILocalization.classtimerplayercolor = "Wähle die Farbe am Spielerfenster"
	DuffedUIConfigUILocalization.classtimertargetbuffcolor = "Wähle die Farbe des Stärkungszaubers auf dem Ziel"
	DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "Wähle Farbe des Schwächungszaubers auf dem Ziel"
	DuffedUIConfigUILocalization.classtimertrinketcolor = "Wähle die Schmuckstückfarbe"
	DuffedUIConfigUILocalization.classtimerheight = "Setze die Höhe der ClassTimer-Leiste"
	DuffedUIConfigUILocalization.classtimerspacing = "Setze den Zwischenraum der ClassTimer-Leisten"
	DuffedUIConfigUILocalization.classtimerseparator = "Aktiviere die Zauberabgrenzung"
	DuffedUIConfigUILocalization.classtimerseparatorcolor = "Wähle die Abgrenzungsfarbe"
	DuffedUIConfigUILocalization.classtimertargetdebuffsenable = "Aktiviere oder deaktiviere die Debuffleisten"

	-- buff
	DuffedUIConfigUILocalization.auras = "Auren"
	DuffedUIConfigUILocalization.aurasplayer = "Aktiviere die DuffedUI Buff- und Debufffenster"
	DuffedUIConfigUILocalization.aurasconsolidate = "Aktiviere zusammengelegte Buffs"
	DuffedUIConfigUILocalization.aurasflash = "Aktiviere das Aufblitzen der Auren bei weniger als 30 Sekunden"
	DuffedUIConfigUILocalization.aurasclassictimer = "Zeige den klassischen Timer auf den Spieler Auren"
	DuffedUIConfigUILocalization.aurasbuffnotice = "Aktiviere die Bufferinnerung"
	DuffedUIConfigUILocalization.auraswarning = "Aktiviere einen Warnton für die Bufferinnerung"
	DuffedUIConfigUILocalization.aurasbufftracker = "Aktiviere das Bufftracker-Plugin"
	DuffedUIConfigUILocalization.auraswrap = "Wähle Umbruch der Stärkungszauberleiste (Standard = 18)"

	-- bags
	DuffedUIConfigUILocalization.bags = "Taschen"
	DuffedUIConfigUILocalization.bagsenable = "Aktiviere die 'Alles in einer Tasche' Ansicht"
	DuffedUIConfigUILocalization.bagsbpr = "Taschenplatzanzahl pro Reihe"
	DuffedUIConfigUILocalization.bagsmovable = "Aktiviere bewegliche Taschen"
	DuffedUIConfigUILocalization.bagsscale = "Sklalierung für Bank und Taschen"
	DuffedUIConfigUILocalization.bagsspacing = "Zwischenraum zwischen den Taschenslots"
	DuffedUIConfigUILocalization.bagsbuttonsize = "Größe der Taschenplätze"

	-- misc
	DuffedUIConfigUILocalization.misc = "Sonstiges"
	DuffedUIConfigUILocalization.miscgold = "Kürze die Goldanzeige im Chat"
	DuffedUIConfigUILocalization.miscsesenable = "Aktiviere das Talenwechsel-Plugin"
	DuffedUIConfigUILocalization.miscsesenablegear = "Aktiviere Ausrüstungsset-Schaltflächen"
	DuffedUIConfigUILocalization.miscsesgearswap = "Aktviere automatischen Setwechsel bei Talentwechsel"
	DuffedUIConfigUILocalization.miscsesset1 = "Aktiviere das Set für die erste Spezalisierung (muss ein Wert zwischen 1 - 10 sein)"
	DuffedUIConfigUILocalization.miscsesset2 = "Aktiviere das Set für die zweite Spezalisierung (muss ein Wert zwischen 1 - 10 sein)"
	DuffedUIConfigUILocalization.misccombatanimation = "Aktviere die Kampf beginnen und verlassen Anzeige"
	DuffedUIConfigUILocalization.miscflightpoint = "Zeige alle Flugpunkte auf der Weltkarte an"
	DuffedUIConfigUILocalization.miscilvlcharacter = "Aktviere die Gegenstandsstufenanzeige im Charakterbildschirm"
	DuffedUIConfigUILocalization.miscloc = "Deaktiviere die 'Kontrollverlustanzeige' an den Aktionsleisten"
	DuffedUIConfigUILocalization.miscacm_screen = "Aktiviere ein automatisches Bildschirmfoto beim Erreichen eines Achievements"
	DuffedUIConfigUILocalization.miscclickcast = "Aktiviere das Click2Cast-Plugin"
	DuffedUIConfigUILocalization.miscClick2Cast_Filter = "Aktiviere den Click2Cast Filter für das Spieler- und Zielfenster"
	DuffedUIConfigUILocalization.miscAFKCamera = "Aktiviere die AFK Kamera"

	-- duffed
	DuffedUIConfigUILocalization.duffed = "Duffed"
	DuffedUIConfigUILocalization.duffeddrinkannouncement = "Aktviere Trinkwarnungen"
	DuffedUIConfigUILocalization.duffedsayinterrupt = "Aktviere Unterbrechungsansagen"
	DuffedUIConfigUILocalization.duffedannouncechannel = "Chatkanal für Warnungsansagen (|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r oder |cffC41F3BINSTANCE_CHAT|r)"
	DuffedUIConfigUILocalization.duffeddispelannouncement = "Aktviere Reinigungswarnungen"
	DuffedUIConfigUILocalization.duffedspellannounce = "Aktiviere Aurawarnungen"

	-- loot
	DuffedUIConfigUILocalization.loot = "Beutefenster"
	DuffedUIConfigUILocalization.lootlootframe = "Aktiviere das DuffedUI Lootfenster"
	DuffedUIConfigUILocalization.lootrolllootframe = "Aktiviere das DuffedUI Würfelfenster"

	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipenable = "Aktiviere den DuffedUI Tooltip"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Verstecke den Tooltip während des Kampfes"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Verstecke den Tooltip auf Aktionsleistenknöpfen"
	DuffedUIConfigUILocalization.tooltiphideuf = "Verstecke den Tooltip auf den Einheitenfentern"
	DuffedUIConfigUILocalization.tooltipids = "Zeige die Zauber- und Gegenstands-ID im Tooltip"
	DuffedUIConfigUILocalization.tooltipilvl = "Aktiviere die Gegenstandslevelanzeige im Tooltip"
	DuffedUIConfigUILocalization.tooltipenablecaster = "Zeige den Namen des Zaubernden, für Stärkungs- und Schwächungszauber, im Tooltip"

	-- merchant
	DuffedUIConfigUILocalization.merchant = "H ändler"
	DuffedUIConfigUILocalization.merchantsellgrays = "Verkaufe graue Gegenstände automatisch"
	DuffedUIConfigUILocalization.merchantautorepair = "Repariere beschädigte Rüstung automatisch"
	DuffedUIConfigUILocalization.merchantsellmisc = "Verkaufe vordefinierte Gegenstände automatisch (Müll, NICHT grau)"
	DuffedUIConfigUILocalization.merchantautoguildrepair = "Aktiviere Reparatur über die Gildenbank"

	-- error
	DuffedUIConfigUILocalization.error = "Fehlermeldungen"
	DuffedUIConfigUILocalization.errorenable = "Verstecke die Fehlermeldungen, die in der Mitte Deines Bildschirms immer wieder angezeigt werden"

	-- invite
	DuffedUIConfigUILocalization.invite = "Einladungen"
	DuffedUIConfigUILocalization.inviteautoaccept = "Aktiviere die automatische Einladung von Freunden und Gildenmitgliedern"
	 
	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Zurücksetzen"
	DuffedUIConfigUILocalization.option_button_load = "Übernehmen"
	DuffedUIConfigUILocalization.option_button_close = "Schließen"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Einstellungen für jeden Charakter einzeln abspeichern"
	DuffedUIConfigUILocalization.option_resetchar = "Bist du dir sicher, dass du deine Charaktereinstellungen auf den Standardwert zurücksetzen willst?"
	DuffedUIConfigUILocalization.option_resetall = "Bist du dir sicher, dass du alle deine Einstellungen auf Standardwerte zurücksetzen willst?"
	DuffedUIConfigUILocalization.option_perchar = "Bist du dir sicher, dass du von, oder auf die \"für jeden Charakter einzeln abspeichern\"-Einstellungen wechseln möchtest?"
	DuffedUIConfigUILocalization.option_makeselection = "Um mit der Konfiguration fortfahren zu können, musst du erst eine Auswahl getroffen haben."
end