if GetLocale() == "itIT" then
	-- general
	DuffedUIConfigUILocalization.general = "General"
	DuffedUIConfigUILocalization.generalautoscale = "Auto UI Scale"
	DuffedUIConfigUILocalization.generaluiscale = "UI Scale (if auto-scale is disabled)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Set default backdrop color of panels"
	DuffedUIConfigUILocalization.generalbordercolor = "Set default border color of panels"
	DuffedUIConfigUILocalization.generalclasscolor = "Enable class color for textelements"

	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "Unit Frames"
	DuffedUIConfigUILocalization.unitframesenable = "Enable DuffedUI Unit Frames"
	DuffedUIConfigUILocalization.unitframeslayout = "Set UF-Layout (1, 2 or 3, default = 2)"
	DuffedUIConfigUILocalization.unitframesfader = "Enable Fader for unitframes"
	DuffedUIConfigUILocalization.unitframesminalpha = "Set minimum alpha for Fader (default = 0.1)"
	DuffedUIConfigUILocalization.unitframespercent = "Enable percent display beside player & target"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Enable smooth bar"
	DuffedUIConfigUILocalization.unitframesunicolor = "Enable Unique color theme (grey health bar)"
	DuffedUIConfigUILocalization.unitframeshealthbarcolor = "Set healthbar color"
	DuffedUIConfigUILocalization.unitframesdeficitcolor = "Set deficit color"
	DuffedUIConfigUILocalization.unitframesColorGradient = "Enable ColorGradient for Healthbar"
	DuffedUIConfigUILocalization.unitframescharportrait = "Enable portraits on player and target"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Enable Weakened Soul bar notification (Priest)"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "Show Statue Bar"
	DuffedUIConfigUILocalization.unitframesclassbar = "Enable class bar"
	DuffedUIConfigUILocalization.unitframesruneofpower = "Enable rune of power bar"
	DuffedUIConfigUILocalization.unitframestargetauras = "Enable target auras"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Display only our debuffs on target"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Combat Feedback on player and target"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Enable healcomm"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Enable aggro display on yourself"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Enable Target of Target debuffs (High Reso)"
	DuffedUIConfigUILocalization.unitframestotdbsize = "Set size of debuffs for Target of Target"
	DuffedUIConfigUILocalization.unitframesfocusdebuffs = "Enable focus debuffs"
	DuffedUIConfigUILocalization.unitframesfocusbutton = "Enable focus button on player / focus frame"
	DuffedUIConfigUILocalization.unitframesattached = "Attach Classbars to Unitframes"
	DuffedUIConfigUILocalization.unitframesoocHide = "Hide Classbars out of Combat"

	-- chat
	DuffedUIConfigUILocalization.chat = "Chat"
	DuffedUIConfigUILocalization.chatenable = "Enable DuffedUI Chat"
	DuffedUIConfigUILocalization.chatwhispersound = "Play sound when receiving private message"
	DuffedUIConfigUILocalization.chatlbackground = "Enable chat panel background (left)"
	DuffedUIConfigUILocalization.chatrbackground = "Enable chat panel background (right)"
	DuffedUIConfigUILocalization.chatfading = "Enable chatfading"
	DuffedUIConfigUILocalization.chattextright = "Set textalign to right for right chatframe"

	-- castbar
	DuffedUIConfigUILocalization.castbar = "Castbar"
	DuffedUIConfigUILocalization.castbarenable = "Enable castbar"
	DuffedUIConfigUILocalization.castbarpetenable = "Enable pet castbar"
	DuffedUIConfigUILocalization.castbarcbicons = "Enable castbar-icons"
	DuffedUIConfigUILocalization.castbarcblatency = "Enable castbar latency"
	DuffedUIConfigUILocalization.castbarspark = "Enable castbar spark"
	DuffedUIConfigUILocalization.castbarcolor = "Set color for castbars"
	DuffedUIConfigUILocalization.castbarclasscolor = "Enable classcolor for castbar"
	DuffedUIConfigUILocalization.castbarcbticks = "Enable castbar ticks for channeled casts."
	DuffedUIConfigUILocalization.castbarplayerwidth = "Set width of player castbar"

	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "Nameplates"
	DuffedUIConfigUILocalization.nameplateenable = "Enable Nameplates"
	DuffedUIConfigUILocalization.nameplatedebuffs = "Enable debuff display"
	DuffedUIConfigUILocalization.nameplatewidth = "Set width of nameplates (default = 110)"
	DuffedUIConfigUILocalization.nameplateheight = "Set height of nameplates (default = 7)"
	DuffedUIConfigUILocalization.nameplateauraswidth = "Set width of Debufficon"
	DuffedUIConfigUILocalization.nameplateaurasheight = "Set height of Debufficon"
	DuffedUIConfigUILocalization.nameplateMaxDebuffs = "Set max debuffs to display (default = 5)"
	DuffedUIConfigUILocalization.nameplateCastHeight = "Set height for Castbar"
	DuffedUIConfigUILocalization.nameplateShowComboPoints = "Show ComboPoints on nameplates"

	-- action bar
	DuffedUIConfigUILocalization.actionbar = "Action Bars"
	DuffedUIConfigUILocalization.actionbarenable = "Enable DuffedUI action bar"
	DuffedUIConfigUILocalization.actionbarrightbarvertical = "Set Rightbar horizontal"
	DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "Set rightbars on mouseover"
	DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "Set petbar horizontal"
	DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "Set petbar to always visible"
	DuffedUIConfigUILocalization.actionbarverticalshapeshift = "Enable vertical Shapeshiftbar"
	DuffedUIConfigUILocalization.actionbarhotkey = "Show hotkey on buttons"
	DuffedUIConfigUILocalization.actionbarmacro = "Show macro text on action bar"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Size of the main action buttons"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Spacing of the main action buttons"
	DuffedUIConfigUILocalization.actionbarshapeshiftborder = "Enable Shapeshiftbarborder"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "Enable mouseover for Shapeshiftbar"
	DuffedUIConfigUILocalization.actionbarborderhighlight = "Enable prochighlight from DuffedUI (default = disabled)"
	DuffedUIConfigUILocalization.actionbarsidebars = "Enable mouseover for SideBars on chatframes"

	-- raid frames
	DuffedUIConfigUILocalization.raid = "Raid Frames"
	DuffedUIConfigUILocalization.raidenable = "Enable Raid Frames"
	DuffedUIConfigUILocalization.raidshowboss = "Enable Boss Unit Frames"
	DuffedUIConfigUILocalization.raidarena = "Enable arena unit frames"
	DuffedUIConfigUILocalization.raidmaintank = "Enable Main Tank"
	DuffedUIConfigUILocalization.raidmainassist = "Enable Main Assist"
	DuffedUIConfigUILocalization.raidshowrange = "Enable party/raid Range alpha display"
	DuffedUIConfigUILocalization.raidraidalphaoor = "Alpha on Party/Raid unit out of range"
	DuffedUIConfigUILocalization.raidshowsymbols = "Show symbols on party/raid"
	DuffedUIConfigUILocalization.raidaggro = "Enable aggro display on party/raid"
	DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "Enable PVE raid Aura Watch (Grid Only)"
	DuffedUIConfigUILocalization.raidshowraidpets = "Show Pets in DuffedUI Raid Frames"
	DuffedUIConfigUILocalization.raidshowplayerinparty = "Show yourself in party"
	DuffedUIConfigUILocalization.raidframewidth = "Set width of the unitframe"
	DuffedUIConfigUILocalization.raidframeheight = "Set height of the unitframe"
	DuffedUIConfigUILocalization.raidpointer = "Enable Pointer for direction display"

	-- datatext
	DuffedUIConfigUILocalization.datatext = "Data Text"
	DuffedUIConfigUILocalization.datatextarmor = "Armor Position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextavd = "Avoidance position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextbags = "Bags position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextbattleground = "Enable Battleground Stats"
	DuffedUIConfigUILocalization.datatextblock = "Block position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextbonusarmor = "Bonus Armor position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Call to Arms & Dungeons (0 for disabled)"
	DuffedUIConfigUILocalization.datatextcrit = "Crit % position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextdodge = "Dodge position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextdur = "Durability position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextfriends = "Friends position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextgold = "Gold position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextguild = "Guild position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthaste = "Haste position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthonor = "Honor  position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthonorablekills = "Honorable Kills position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextleech = "Leech position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextmastery = "Mastery position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Micro Menu position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextmulstistrike = "Multistrike position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextparry = "Parry position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextpower = "Power position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextprofession = "Profession position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextsmf = "System position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexttalent = "Display talents (0 for disabled)"
	DuffedUIConfigUILocalization.datatextversatility = "Versatility position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextwowtime = "Time position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexttime24 = "Enable 24h time"
	DuffedUIConfigUILocalization.datatextlocaltime = "Use Local Time instead of Server Time"
	DuffedUIConfigUILocalization.datatextfontsize = "Font size of text"

	-- skins
	DuffedUIConfigUILocalization.skins = "Skins"
	DuffedUIConfigUILocalization.skinsblizzardreskin = "Reskin Blizzard frames to match DuffedUI"
	DuffedUIConfigUILocalization.skinscalendarevent = "Disable calendar event textures"

	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "Cooldowns"
	DuffedUIConfigUILocalization.cooldownenable = "Enable cooldown number on buttons"
	DuffedUIConfigUILocalization.cooldowntreshold = "Turn cooldown number red at X value"
	DuffedUIConfigUILocalization.cooldownicdenable = "Enable ItemCooldown"
	DuffedUIConfigUILocalization.cooldownrcdenable = "Enable RaidCooldowns"
	DuffedUIConfigUILocalization.cooldownrcdraid = "Enable cooldown announcement for raid"
	DuffedUIConfigUILocalization.cooldownrcdparty = "Enable cooldown announcement for party"
	DuffedUIConfigUILocalization.cooldownrcdarena = "Enable cooldown announcement for arena"
	DuffedUIConfigUILocalization.cooldownscdenable = "Enable the SpellCooldown-Plugin"
	DuffedUIConfigUILocalization.cooldownscdfsize = "Set fontsize"
	DuffedUIConfigUILocalization.cooldownscdsize = "Set size for icons (default = 28)"
	DuffedUIConfigUILocalization.cooldownscdspacing = "Set spacing of icons (default = 10)"
	DuffedUIConfigUILocalization.cooldownscdfade = "Set fading (values: 0 one color, 1 green to red, 2 red to green)"

	-- classtimer
	DuffedUIConfigUILocalization.classtimer = "Classtimer"
	DuffedUIConfigUILocalization.classtimerenable = "Enable Classtimer"
	DuffedUIConfigUILocalization.classtimerspark = "Enable spark"
	DuffedUIConfigUILocalization.classtimertargetdebuffs = "Enable targetdebuffs"
	DuffedUIConfigUILocalization.classtimerplayercolor = "Set player color"
	DuffedUIConfigUILocalization.classtimertargetbuffcolor = "Set target buff color"
	DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "Set target debuff color"
	DuffedUIConfigUILocalization.classtimertrinketcolor = "Set trinket color"
	DuffedUIConfigUILocalization.classtimerheight = "Set height of classtimer bar"
	DuffedUIConfigUILocalization.classtimerspacing = "Set spacing of classtimer bars"
	DuffedUIConfigUILocalization.classtimerseparator = "Enable cast separator"
	DuffedUIConfigUILocalization.classtimerseparatorcolor = "Set color of separator"
	DuffedUIConfigUILocalization.classtimertargetdebuffsenable = "Enable / disable debuff bars"

	-- buff
	DuffedUIConfigUILocalization.auras = "Auras"
	DuffedUIConfigUILocalization.aurasplayer = "Enable DuffedUI Buff/Debuff Frames"
	DuffedUIConfigUILocalization.aurasconsolidate = "Enable Consolidate Buffs"
	DuffedUIConfigUILocalization.aurasflash = "Enable flashing animation on aura less than 30 seconds"
	DuffedUIConfigUILocalization.aurasclassictimer = "Display classic timer on player auras"
	DuffedUIConfigUILocalization.aurasbuffnotice = "Enable BuffNotice"
	DuffedUIConfigUILocalization.auraswarning = "Enable warningsound for BuffNotice"
	DuffedUIConfigUILocalization.aurasbufftracker = "Enable Bufftrackerplugin"
	DuffedUIConfigUILocalization.auraswrap = "Set wrap for buffs (default = 18)"

	-- bags
	DuffedUIConfigUILocalization.bags = "Bags"
	DuffedUIConfigUILocalization.bagsenable = "Enable all-in-one bag"
	DuffedUIConfigUILocalization.bagsbpr = "Set bagbuttons per row"
	DuffedUIConfigUILocalization.bagsmovable = "Make bags moveable"
	DuffedUIConfigUILocalization.bagsscale = "Set scale of bag & bank frames"
	DuffedUIConfigUILocalization.bagsspacing = "Set spacing betweens bagslots"
	DuffedUIConfigUILocalization.bagsbuttonsize = " Set slotsize"

	-- misc
	DuffedUIConfigUILocalization.misc = "Misc"
	DuffedUIConfigUILocalization.miscgold = "Enable shorten golddisplay in chat"
	DuffedUIConfigUILocalization.miscsesenable = "Enable Specswitcherplugin"
	DuffedUIConfigUILocalization.miscsesenablegear = "Enable Equipmentsetbuttons"
	DuffedUIConfigUILocalization.miscsesgearswap = "Enable automatic setswap on respec"
	DuffedUIConfigUILocalization.miscsesset1 = "Set set for first spec (must be an value between 1 - 10)"
	DuffedUIConfigUILocalization.miscsesset2 = "Set set for second spec (must be an value between 1 - 10)"
	DuffedUIConfigUILocalization.misccombatanimation = "Enable Combatanimation"
	DuffedUIConfigUILocalization.miscflightpoint = "Enable Flightpointlist"
	DuffedUIConfigUILocalization.miscilvlcharacter = "Enable itemlevel on character screen"
	DuffedUIConfigUILocalization.miscloc = "Disable Loss of Control for actionbars"
	DuffedUIConfigUILocalization.miscacm_screen = "Enable automatic Achievment screenshots"
	DuffedUIConfigUILocalization.miscclickcast = "Enable Click2Cast-plugin"
	DuffedUIConfigUILocalization.miscClick2Cast_Filter = "Enable Click2Cast-Filter"
	DuffedUIConfigUILocalization.miscAFKCamera = "Enable AFKCamera"

	-- duffed
	DuffedUIConfigUILocalization.duffed = "Duffed"
	DuffedUIConfigUILocalization.duffeddrinkannouncement = "Enable Drinkannouncement"
	DuffedUIConfigUILocalization.duffedsayinterrupt = "Enable Interruptannouncement"
	DuffedUIConfigUILocalization.duffedannouncechannel = "Set channel for announcement (|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r or |cffC41F3BINSTANCE_CHAT|r)"
	DuffedUIConfigUILocalization.duffeddispelannouncement = "Enable Dispelannouncement"
	DuffedUIConfigUILocalization.duffedspellannounce = "Enable Auraannouncement"

	-- loot
	DuffedUIConfigUILocalization.loot = "Loot"
	DuffedUIConfigUILocalization.lootlootframe = "Enable loot window"
	DuffedUIConfigUILocalization.lootrolllootframe = "Enable item roll window"

	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipenable = "Enable tooltip"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Hide tooltip in combat"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Hide tooltip on action bar buttons"
	DuffedUIConfigUILocalization.tooltiphideuf = "Hide tooltip on unit frames"
	DuffedUIConfigUILocalization.tooltipids = "Show spell / item-id on tooltip"
	DuffedUIConfigUILocalization.tooltipilvl = "Enable Itemleveldisplay on tooltip"
	DuffedUIConfigUILocalization.tooltipenablecaster = "Enable Castername for buffs / debuffs on tooltip"

	-- merchant
	DuffedUIConfigUILocalization.merchant = "Merchant"
	DuffedUIConfigUILocalization.merchantsellgrays = "Auto sell grey items"
	DuffedUIConfigUILocalization.merchantautorepair = "Auto Repair items"
	DuffedUIConfigUILocalization.merchantsellmisc = "Sell some defined (craps not grey) items automatically"
	DuffedUIConfigUILocalization.merchantautoguildrepair = "Enable Guild Repair Items"

	-- error
	DuffedUIConfigUILocalization.error = "Error Message"
	DuffedUIConfigUILocalization.errorenable = "Hide spamming error in the middle of your screen"

	-- invite
	DuffedUIConfigUILocalization.invite = "Invite"
	DuffedUIConfigUILocalization.inviteautoaccept = "Enable Auto-Invite (Friends and Guildmates)"
	 
	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "Reset"
	DuffedUIConfigUILocalization.option_button_load = "Apply Settings"
	DuffedUIConfigUILocalization.option_button_close = "Close"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Set settings Per-Character"
	DuffedUIConfigUILocalization.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
	DuffedUIConfigUILocalization.option_resetall = "Are you sure you want to reset all of your settings to Default?"
	DuffedUIConfigUILocalization.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
	DuffedUIConfigUILocalization.option_makeselection = "You must make a selection before you can continue to config."
end