if GetLocale() == "koKR" then
	--[[General]]--
	DuffedUIConfigUILocalization.general = "General"
	DuffedUIConfigUILocalization.generalautoscale = "Auto UI Scale"
	DuffedUIConfigUILocalization.generaluiscale = "UI Scale (if auto-scale is disabled)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "Set default backdrop color of panels"
	DuffedUIConfigUILocalization.generalbordercolor = "Set default border color of panels"
	DuffedUIConfigUILocalization.generalclasscolor = "Enable class color for textelements"
	DuffedUIConfigUILocalization.generalblizzardreskin = "Reskin Blizzard frames to match DuffedUI"
	DuffedUIConfigUILocalization.generalcalendarevent = "Disable calendar event textures"
	DuffedUIConfigUILocalization.generalautoaccept = "Enable Auto-Invite (Friends and Guildmates)"

	--[[Font]]--
	DuffedUIConfigUILocalization.font = "Fonts"
	DuffedUIConfigUILocalization.fontduffeduisize = "Fontsize DuffedUI (default = 11)"
	DuffedUIConfigUILocalization.fontduffedui_altsize = "Fontsize DuffedUI Alternativ (default = 12)"
	DuffedUIConfigUILocalization.fontpixelfontsize = "Fontsize Pixel Font (default = 12)"
	DuffedUIConfigUILocalization.fontactionbars = "Actionbar-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"
	DuffedUIConfigUILocalization.fontauras = "Aura-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"
	DuffedUIConfigUILocalization.fontclasstimer = "Classtimer-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"
	DuffedUIConfigUILocalization.fontses = "SpecSwitcher-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"
	DuffedUIConfigUILocalization.fontdatatext = "Datatext-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"
	DuffedUIConfigUILocalization.fontunitframes = "Unit Frames-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"
	DuffedUIConfigUILocalization.fontscd = "SpellCooldown-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"
	DuffedUIConfigUILocalization.fontrcd = "RaidCooldowns-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"
	DuffedUIConfigUILocalization.fontexperience = "ExperienceBar-Font (Values: |cffC41F3BDuffedUI|r, |cffC41F3BDuffedUI Alternativ|r, |cffC41F3BPixel Font|r)"

	--[[Unit Frames]]--
	DuffedUIConfigUILocalization.unitframes = "Unit Frames"
	DuffedUIConfigUILocalization.unitframesenable = "Enable DuffedUI Unit Frames"
	DuffedUIConfigUILocalization.unitframeslayout = "Set UF-Layout (1, 2, 3 or 4, default = 1)"
	DuffedUIConfigUILocalization.unitframespercent = "Enable percent display beside player & target"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "Enable smooth bar"
	DuffedUIConfigUILocalization.unitframesunicolor = "Enable Unique color theme (grey health bar)"
	DuffedUIConfigUILocalization.unitframeshealthbarcolor = "Set healthbar color"
	DuffedUIConfigUILocalization.unitframesdeficitcolor = "Set deficit color"
	DuffedUIConfigUILocalization.unitframesColorGradient = "Enable ColorGradient for Healthbar"
	DuffedUIConfigUILocalization.unitframescharportrait = "Enable portraits on player and target"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "Enable Weakened Soul bar notification (Priest)"
	DuffedUIConfigUILocalization.unitframesclassbar = "Enable class bar"
	DuffedUIConfigUILocalization.unitframesruneofpower = "Enable rune of power bar"
	DuffedUIConfigUILocalization.unitframestargetauras = "Enable target auras"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "Display only our debuffs on target"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "Combat Feedback on player and target"
	DuffedUIConfigUILocalization.unitframeshealcomm = "Enable healcomm"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "Enable aggro display on yourself"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "Enable Target of Target debuffs (High Reso)"
	DuffedUIConfigUILocalization.unitframestotdbsize = "Set size of debuffs for Target of Target"
	DuffedUIConfigUILocalization.unitframesfocusdebuffs = "Enable focus debuffs"
	DuffedUIConfigUILocalization.unitframesfocusbutton = "Enable focus button on player / focus frame"
	DuffedUIConfigUILocalization.unitframesattached = "Attach Classbars to Unitframes"
	DuffedUIConfigUILocalization.unitframesoocHide = "Hide Classbars out of Combat"
	DuffedUIConfigUILocalization.unitframesplayermodel = "Set Portraitstyle (Icon or Model, default => Model)"
	DuffedUIConfigUILocalization.unitframesbuffsize = "Set size of Buffs on Targetframe"
	DuffedUIConfigUILocalization.unitframesdebuffsize = "Set size of Debuffs on Targetframe"
	DuffedUIConfigUILocalization.unitframesDruidMana = "Enable the display for Mana if shapeshifted"
	DuffedUIConfigUILocalization.unitframesAnticipationBar = "Enable Anticipationbar if skill is learned"

	--[[Chat]]--
	DuffedUIConfigUILocalization.chat = "Chat"
	DuffedUIConfigUILocalization.chatenable = "Enable DuffedUI Chat"
	DuffedUIConfigUILocalization.chatwhispersound = "Play sound when receiving private message"
	DuffedUIConfigUILocalization.chatlbackground = "Enable chat panel background (left)"
	DuffedUIConfigUILocalization.chatrbackground = "Enable chat panel background (right)"
	DuffedUIConfigUILocalization.chatfading = "Enable chatfading"
	DuffedUIConfigUILocalization.chattextright = "Set textalign to right for right chatframe"

	--[[Castbar]]--
	DuffedUIConfigUILocalization.castbar = "Castbar"
	DuffedUIConfigUILocalization.castbarenable = "Enable castbar"
	DuffedUIConfigUILocalization.castbarpetenable = "Enable pet castbar"
	DuffedUIConfigUILocalization.castbarcbicons = "Enable castbar-icons"
	DuffedUIConfigUILocalization.castbarcblatency = "Enable castbar latency"
	DuffedUIConfigUILocalization.castbarspark = "Enable castbar spark"
	DuffedUIConfigUILocalization.castbarcolor = "Set color for castbars"
	DuffedUIConfigUILocalization.castbarclasscolor = "Enable classcolor for castbar"
	DuffedUIConfigUILocalization.castbarcbticks = "Enable castbar ticks for channeled casts."
	DuffedUIConfigUILocalization.castbarplayerwidth = "Set width of player castbar"

	--[[Nameplate]]--
	DuffedUIConfigUILocalization.nameplate = "Nameplates"
	DuffedUIConfigUILocalization.nameplateactive = "Enable Nameplates"
	DuffedUIConfigUILocalization.nameplatedebuffs = "Enable debuff display"
	DuffedUIConfigUILocalization.nameplateplatewidth = "Set width of nameplates (default = 110)"
	DuffedUIConfigUILocalization.nameplateplateheight = "Set height of nameplates (default = 7)"
	DuffedUIConfigUILocalization.nameplateauraswidth = "Set width of Debufficon"
	DuffedUIConfigUILocalization.nameplateaurasheight = "Set height of Debufficon"
	DuffedUIConfigUILocalization.nameplateMaxDebuffs = "Set max debuffs to display (default = 5)"
	DuffedUIConfigUILocalization.nameplatethreat = "Enable Threatfeature"
	DuffedUIConfigUILocalization.nameplatethreat_badcolor = "Bad threat color, varies depending if your a tank or dps/heal"
	DuffedUIConfigUILocalization.nameplatethreat_goodcolor = "Good threat color, varies depending if your a tank or dps/heal"
	DuffedUIConfigUILocalization.nameplatethreat_transitioncolor = "Losing/Gaining threat color"
	DuffedUIConfigUILocalization.nameplatePercent = "Enable Percent-Display on Nameplates"
	DuffedUIConfigUILocalization.nameplateNonTargetAlpha = "Set alpha for non target Nameplates"

	--[[Actionbars]]--
	DuffedUIConfigUILocalization.actionbar = "Action Bars"
	DuffedUIConfigUILocalization.actionbarenable = "Enable DuffedUI action bar"
	DuffedUIConfigUILocalization.actionbarrightbarvertical = "Set Rightbar horizontal"
	DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "Set rightbars on mouseover"
	DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "Set petbar horizontal"
	DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "Set petbar to always visible"
	DuffedUIConfigUILocalization.actionbarverticalshapeshift = "Enable vertical Shapeshiftbar"
	DuffedUIConfigUILocalization.actionbarhotkey = "Show hotkey on buttons"
	DuffedUIConfigUILocalization.actionbarmacro = "Show macro text on action bar"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "Size of the main action buttons"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "Spacing of the main action buttons"
	DuffedUIConfigUILocalization.actionbarshapeshiftborder = "Enable Shapeshiftbarborder"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "Enable mouseover for Shapeshiftbar"
	DuffedUIConfigUILocalization.actionbarborderhighlight = "Enable prochighlight from DuffedUI (default = disabled)"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "Size of the petactionbuttons"
	DuffedUIConfigUILocalization.actionbarLeftsidebars = "Enable mouseover for Left SideBar on chatframe"
	DuffedUIConfigUILocalization.actionbarRightsidebars = "Enable mouseover for Right SideBar on chatframe"
	DuffedUIConfigUILocalization.actionbarSidebarButtonsize = "Set size of buttons for sidebars on chat (only when vertical)"

	--[[Raid Frames]]--
	DuffedUIConfigUILocalization.raid = "Raid Frames"
	DuffedUIConfigUILocalization.raidenable = "Enable Raid Frames"
	DuffedUIConfigUILocalization.raidshowboss = "Enable Boss Unit Frames"
	DuffedUIConfigUILocalization.raidarena = "Enable arena unit frames"
	DuffedUIConfigUILocalization.raidmaintank = "Enable Main Tank"
	DuffedUIConfigUILocalization.raidmainassist = "Enable Main Assist"
	DuffedUIConfigUILocalization.raidshowrange = "Enable party/raid Range alpha display"
	DuffedUIConfigUILocalization.raidraidalphaoor = "Alpha on Party/Raid unit out of range"
	DuffedUIConfigUILocalization.raidshowsymbols = "Show symbols on party/raid"
	DuffedUIConfigUILocalization.raidaggro = "Enable aggro display on party/raid"
	DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "Enable PVE raid Aura Watch (Grid Only)"
	DuffedUIConfigUILocalization.raidshowraidpets = "Show Pets in DuffedUI Raid Frames"
	DuffedUIConfigUILocalization.raidshowplayerinparty = "Show yourself in party"
	DuffedUIConfigUILocalization.raidframewidth = "Set width of the unitframe"
	DuffedUIConfigUILocalization.raidframeheight = "Set height of the unitframe"
	DuffedUIConfigUILocalization.raidlayout = "Set layout for group frames (default = heal, Values: |cffC41F3Bheal|r or |cffC41F3Bdps|r)"

	--[[DataText]]--
	DuffedUIConfigUILocalization.datatext = "Data Text"
	DuffedUIConfigUILocalization.datatextarmor = "Armor Position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextavd = "Avoidance position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextbags = "Bags position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextbattleground = "Enable Battleground Stats"
	DuffedUIConfigUILocalization.datatextblock = "Block position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextbonusarmor = "Bonus Armor position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "Call to Arms & Dungeons (0 for disabled)"
	DuffedUIConfigUILocalization.datatextcrit = "Crit % position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextdodge = "Dodge position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextdur = "Durability position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextfriends = "Friends position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextgold = "Gold position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextguild = "Guild position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthaste = "Haste position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthonor = "Honor  position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexthonorablekills = "Honorable Kills position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextleech = "Leech position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextmastery = "Mastery position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextmicromenu = "Micro Menu position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextmulstistrike = "Multistrike position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextparry = "Parry position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextpower = "Power position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextprofession = "Profession position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextsmf = "System position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexttalent = "Display talents (0 for disabled)"
	DuffedUIConfigUILocalization.datatextversatility = "Versatility position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextwowtime = "Time position (0 for disabled)"
	DuffedUIConfigUILocalization.datatextgarrison = "Garrison position (0 for disabled)"
	DuffedUIConfigUILocalization.datatexttime24 = "Enable 24h time"
	DuffedUIConfigUILocalization.datatextlocaltime = "Use Local Time instead of Server Time"
	DuffedUIConfigUILocalization.datatextfontsize = "Font size of text"
	DuffedUIConfigUILocalization.datatextShowInCombat = "Show DataText-Tooltip in combat"

	--[[Cooldowns]]--
	DuffedUIConfigUILocalization.cooldown = "Cooldowns"
	DuffedUIConfigUILocalization.cooldownenable = "Enable cooldown number on buttons"
	DuffedUIConfigUILocalization.cooldowntreshold = "Turn cooldown number red at X value"
	DuffedUIConfigUILocalization.cooldownicdenable = "Enable ItemCooldown"
	DuffedUIConfigUILocalization.cooldownrcdenable = "Enable RaidCooldowns"
	DuffedUIConfigUILocalization.cooldownrcdraid = "Enable cooldown announcement for raid"
	DuffedUIConfigUILocalization.cooldownrcdparty = "Enable cooldown announcement for party"
	DuffedUIConfigUILocalization.cooldownrcdarena = "Enable cooldown announcement for arena"
	DuffedUIConfigUILocalization.cooldownscdenable = "Enable the SpellCooldown-Plugin"
	DuffedUIConfigUILocalization.cooldownscdfsize = "Set fontsize"
	DuffedUIConfigUILocalization.cooldownscdsize = "Set size for icons (default = 28)"
	DuffedUIConfigUILocalization.cooldownscdspacing = "Set spacing of icons (default = 10)"
	DuffedUIConfigUILocalization.cooldownscdfade = "Set fading (values: 0 one color, 1 green to red, 2 red to green)"

	--[[ClassTimer]]--
	DuffedUIConfigUILocalization.classtimer = "Classtimer"
	DuffedUIConfigUILocalization.classtimerenable = "Enable Classtimer"
	DuffedUIConfigUILocalization.classtimerspark = "Enable spark"
	DuffedUIConfigUILocalization.classtimertargetdebuff = "Enable Debuff display above target frame instead of player frame"
	DuffedUIConfigUILocalization.classtimerplayercolor = "Set player color"
	DuffedUIConfigUILocalization.classtimertargetbuffcolor = "Set target buff color"
	DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "Set target debuff color"
	DuffedUIConfigUILocalization.classtimertrinketcolor = "Set trinket color"
	DuffedUIConfigUILocalization.classtimerheight = "Set height of classtimer bar"
	DuffedUIConfigUILocalization.classtimerspacing = "Set spacing of classtimer bars"
	DuffedUIConfigUILocalization.classtimerseparator = "Enable cast separator"
	DuffedUIConfigUILocalization.classtimerseparatorcolor = "Set color of separator"
	DuffedUIConfigUILocalization.classtimerdebuffsenable = "Enable Debuff display on classtimer"

	--[[Buffs]]--
	DuffedUIConfigUILocalization.auras = "Auras"
	DuffedUIConfigUILocalization.aurasplayer = "Enable DuffedUI Buff/Debuff Frames"
	DuffedUIConfigUILocalization.aurasconsolidate = "Enable Consolidate Buffs"
	DuffedUIConfigUILocalization.aurasflash = "Enable flashing animation on aura less than 30 seconds"
	DuffedUIConfigUILocalization.aurasclassictimer = "Display classic timer on player auras"
	DuffedUIConfigUILocalization.aurasbuffnotice = "Enable BuffNotice"
	DuffedUIConfigUILocalization.auraswarning = "Enable warningsound for BuffNotice"
	DuffedUIConfigUILocalization.aurasbufftracker = "Enable Bufftrackerplugin"
	DuffedUIConfigUILocalization.auraswrap = "Set wrap for buffs (default = 18)"

	--[[Bags]]--
	DuffedUIConfigUILocalization.bags = "Bags"
	DuffedUIConfigUILocalization.bagsenable = "Enable all-in-one bag"
	DuffedUIConfigUILocalization.bagsbpr = "Set bagbuttons per row"
	DuffedUIConfigUILocalization.bagsmovable = "Make bags moveable"
	DuffedUIConfigUILocalization.bagsscale = "Set scale of bag & bank frames"
	DuffedUIConfigUILocalization.bagsspacing = "Set spacing betweens bagslots"
	DuffedUIConfigUILocalization.bagsbuttonsize = " Set slotsize"
	DuffedUIConfigUILocalization.bagsBounce = "Enable Pulse Animation for new items"
	DuffedUIConfigUILocalization.bagsSortingButton = "Enable the sorting button on bags and bank"

	--[[Misc]]--
	DuffedUIConfigUILocalization.misc = "Misc"
	DuffedUIConfigUILocalization.miscgold = "Enable shorten golddisplay in chat"
	DuffedUIConfigUILocalization.miscsesenable = "Enable Specswitcherplugin"
	DuffedUIConfigUILocalization.miscsesenablegear = "Enable Equipmentsetbuttons"
	DuffedUIConfigUILocalization.miscsesgearswap = "Enable automatic setswap on respec"
	DuffedUIConfigUILocalization.miscsesset1 = "Set set for first spec (must be an value between 1 - 10)"
	DuffedUIConfigUILocalization.miscsesset2 = "Set set for second spec (must be an value between 1 - 10)"
	DuffedUIConfigUILocalization.misccombatanimation = "Enable Combatanimation"
	DuffedUIConfigUILocalization.miscflightpoint = "Enable Flightpointlist"
	DuffedUIConfigUILocalization.miscilvlcharacter = "Enable itemlevel on character screen"
	DuffedUIConfigUILocalization.miscloc = "Disable Loss of Control for actionbars"
	DuffedUIConfigUILocalization.miscacm_screen = "Enable automatic Achievment screenshots"
	DuffedUIConfigUILocalization.miscclickcast = "Enable Click2Cast-plugin"
	DuffedUIConfigUILocalization.miscAFKCamera = "Enable AFKCamera"
	DuffedUIConfigUILocalization.miscXPBar = "Enable XP-Bar"
	DuffedUIConfigUILocalization.miscXPBarWidth = "Set width of XP-Bar"

	--[[Duffed]]--
	DuffedUIConfigUILocalization.duffed = "Duffed"
	DuffedUIConfigUILocalization.duffeddrinkannouncement = "Enable Drinkannouncement"
	DuffedUIConfigUILocalization.duffedsayinterrupt = "Enable Interruptannouncement"
	DuffedUIConfigUILocalization.duffedannouncechannel = "Set channel for announcement (|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r or |cffC41F3BINSTANCE_CHAT|r)"
	DuffedUIConfigUILocalization.duffeddispelannouncement = "Enable Dispelannouncement"
	DuffedUIConfigUILocalization.duffedspellannounce = "Enable Auraannouncement"
	DuffedUIConfigUILocalization.duffederrorfilter = "Hide spamming error in the middle of your screen"

	--[[Loot]]--
	DuffedUIConfigUILocalization.loot = "Loot"
	DuffedUIConfigUILocalization.lootlootframe = "Enable loot window"
	DuffedUIConfigUILocalization.lootrolllootframe = "Enable item roll window"

	--[[Tooltip]]--
	DuffedUIConfigUILocalization.tooltip = "Tooltip"
	DuffedUIConfigUILocalization.tooltipenable = "Enable tooltip"
	DuffedUIConfigUILocalization.tooltiphidecombat = "Hide tooltip in combat"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "Hide tooltip on action bar buttons"
	DuffedUIConfigUILocalization.tooltiphideuf = "Hide tooltip on unit frames"
	DuffedUIConfigUILocalization.tooltipids = "Show spell / item-id on tooltip"
	DuffedUIConfigUILocalization.tooltipilvl = "Enable Itemleveldisplay on tooltip"
	DuffedUIConfigUILocalization.tooltipenablecaster = "Enable Castername for buffs / debuffs on tooltip"
	DuffedUIConfigUILocalization.tooltipMouse = "Enable Tooltip on cursor"

	--[[Merchant]]--
	DuffedUIConfigUILocalization.merchant = "Merchant"
	DuffedUIConfigUILocalization.merchantsellgrays = "Auto sell grey items"
	DuffedUIConfigUILocalization.merchantautorepair = "Auto Repair items"
	DuffedUIConfigUILocalization.merchantsellmisc = "Sell some defined (craps not grey) items automatically"
	DuffedUIConfigUILocalization.merchantautoguildrepair = "Enable Guild Repair Items"

	--[[Buttons]]--
	DuffedUIConfigUILocalization.option_button_reset = "Reset"
	DuffedUIConfigUILocalization.option_button_load = "Apply Settings"
	DuffedUIConfigUILocalization.option_button_close = "Close"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "Set settings Per-Character"
	DuffedUIConfigUILocalization.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
	DuffedUIConfigUILocalization.option_resetall = "Are you sure you want to reset all of your settings to Default?"
	DuffedUIConfigUILocalization.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
	DuffedUIConfigUILocalization.option_makeselection = "You must make a selection before you can continue to config."
end