if GetLocale() == "zhTW" then
	-- general
	DuffedUIConfigUILocalization.general = "綜合"
	DuffedUIConfigUILocalization.generalautoscale = "UI自動縮放"
	DuffedUIConfigUILocalization.generaluiscale = "UI縮放 (僅在UI自動縮放關閉的時候啟用)"
	DuffedUIConfigUILocalization.generalbackdropcolor = "設置默認的面板背景色"
	DuffedUIConfigUILocalization.generalbordercolor = "設置默認的面板邊框顏色"
	DuffedUIConfigUILocalization.generalclasscolor = "啟用文本按職業著色顯示設定"
	
	-- castbar
	DuffedUIConfigUILocalization.castbar = "施法條"
	DuffedUIConfigUILocalization.castbarenable = "啟用施法條"
	DuffedUIConfigUILocalization.castbarpetenable = "啟用寵物施法條"
	DuffedUIConfigUILocalization.castbarcbicons = "啟用施放技能圖示"
	DuffedUIConfigUILocalization.castbarcblatency = "啟用施法條延遲時間顯示"
	DuffedUIConfigUILocalization.castbarspark = "啟用施法條閃爍"
	DuffedUIConfigUILocalization.castbarcolor = "設定施法條顏色"
	DuffedUIConfigUILocalization.castbarclasscolor = "啟用施法條按職業顏色著著色"
	DuffedUIConfigUILocalization.castbarcbticks = "啟用施法條取消技能施放提示音"

	-- misc
	DuffedUIConfigUILocalization.misc = "雜項"
	DuffedUIConfigUILocalization.misccombatanimation = "啟用進戰/脫戰動畫提示"
	DuffedUIConfigUILocalization.miscflightpoint = "啟用飛行點列表"
	DuffedUIConfigUILocalization.miscilvlcharacter = "啟用人物面板顯示裝備等級"
	DuffedUIConfigUILocalization.miscsComboenergybar = "啟用sCombo能量條外掛程式"
	DuffedUIConfigUILocalization.miscsesenable = "啟用天賦切換外掛程式"
	DuffedUIConfigUILocalization.miscsesenablegear = "啟用裝備設定按鈕（系統裝備設定）"
	DuffedUIConfigUILocalization.miscsesgearswap = "啟用切換天賦時自動切換裝備功能"
	DuffedUIConfigUILocalization.miscsesset1 = "為第一套天賦設置裝備序號 (必須是1-10之間的序號)"
	DuffedUIConfigUILocalization.miscsesset2 = "為第二套天賦設置裝備序號 (必須是1-10之間的序號)"
	DuffedUIConfigUILocalization.miscgold = "啟用聊天框體中獲取金錢名稱縮寫功能."
	DuffedUIConfigUILocalization.miscloc = "禁止動作條<角色失去控制>功能"
	DuffedUIConfigUILocalization.miscloc = "禁止動作條<角色失去控制>功能"
	DuffedUIConfigUILocalization.misclocation = "啟用/禁用頂部地理位置信息欄"
	DuffedUIConfigUILocalization.miscexp_rep = "顯示 聲望/經驗 面板於下方面板"
	DuffedUIConfigUILocalization.miscacm_screen = "啟用獲取成就自動截屏"
	DuffedUIConfigUILocalization.miscclickcast = "啟用點擊施放法術功能(Click2Cast)"

	-- skins
	DuffedUIConfigUILocalization.skins = "其他插件程式美化皮膚"
	DuffedUIConfigUILocalization.skinsenable = "啟用插件外掛程式美化皮膚"
	DuffedUIConfigUILocalization.skinsblizzardreskin = "美化暴雪預設介面使之搭配DuffedUI"
	DuffedUIConfigUILocalization.skinscalendarevent = "禁用行事曆事件的紋理材質"

	-- classtimer
	DuffedUIConfigUILocalization.classtimer = "職業法術計時條"
	DuffedUIConfigUILocalization.classtimerenable = "啟用職業法術計時條"
	DuffedUIConfigUILocalization.classtimerspark = "啟用閃爍"
	DuffedUIConfigUILocalization.classtimertargetdebuffs = "啟用目標Debuff計時條"
	DuffedUIConfigUILocalization.classtimerplayercolor = "設置玩家計時條顏色"
	DuffedUIConfigUILocalization.classtimertargetbuffcolor = "設置目標計時條Buff顏色"
	DuffedUIConfigUILocalization.classtimertargetdebuffcolor = "設置目標計時條Debuff顏色"
	DuffedUIConfigUILocalization.classtimertrinketcolor = "設置飾品計時條顏色"
	DuffedUIConfigUILocalization.classtimerheight = "設定職業計時條高度"
    DuffedUIConfigUILocalization.classtimerspacing = "設定職業計時條之間的間隙度"
    DuffedUIConfigUILocalization.classtimerseparator = "啟用施放法術分離"
    DuffedUIConfigUILocalization.classtimerseparatorcolor = "設定分離顏色"
	DuffedUIConfigUILocalization.classtimertargetdebuffsenable = "Enable / disable debuff bars"

	-- duffed
	DuffedUIConfigUILocalization.duffed = "Duffed"
	DuffedUIConfigUILocalization.duffedbossicons = "在地圖上啟用數位代替BOSS圖示"
	DuffedUIConfigUILocalization.duffeddrinkannouncement = "啟用吃喝通告(PVP)"
	DuffedUIConfigUILocalization.duffedsayinterrupt = "啟用打斷通告"
	DuffedUIConfigUILocalization.duffedannouncechannel = "設置通告頻道 (設定值為:|cffC41F3BSAY|r, |cffC41F3BPARTY|r, |cffC41F3BRAID|r or |cffC41F3BINSTANCE_CHAT|r)"
	DuffedUIConfigUILocalization.duffeddispelannouncement = "啟用驅散通告"
	DuffedUIConfigUILocalization.duffedspellannounce = "啟用光環增益狀態通告"

	-- drunes
	DuffedUIConfigUILocalization.runes = "|cffC41F3Bd|rRunes"
	DuffedUIConfigUILocalization.runesenable = "為DK職業啟用額外可選的符文計時條"
	DuffedUIConfigUILocalization.runesbarlength = "設定符文計時條長度"
	DuffedUIConfigUILocalization.runesbarthickness = "設置符文計時條寬度"
	DuffedUIConfigUILocalization.runesdisplayrpbar = "啟用符文能量條顯示於符文條下方"
	DuffedUIConfigUILocalization.runesdisplayrpbartext = "啟用符文能量文字顯示"
	DuffedUIConfigUILocalization.runesrpbarthickness = "設定符文能量條寬度"
	DuffedUIConfigUILocalization.runeshideooc = "非戰鬥中隱藏drunes符文插件界面"
	DuffedUIConfigUILocalization.runesgrowthdirection = "設定符文計時條排列方式(輸入 VERTICAL 為水平方式 or 輸入 HORIZONTAL 為垂直方式)"

	-- nameplate
	DuffedUIConfigUILocalization.nameplate = "姓名版"
	DuffedUIConfigUILocalization.nameplateenable = "開啟姓名版"
	DuffedUIConfigUILocalization.nameplateenhancethreat = "啟用仇恨著色模式,將會根據你的角色自動改變顏色"
	DuffedUIConfigUILocalization.nameplateshowhealth = "在姓名板上顯示生命值"
	DuffedUIConfigUILocalization.nameplatecombat = "僅在戰鬥中顯示姓名板"
	DuffedUIConfigUILocalization.nameplategoodcolor = "安全仇恨值顏色,取決於你是坦克還是治療者"
	DuffedUIConfigUILocalization.nameplatebadcolor = "危險仇恨值顏色,取決於你是治療還是輸出"
	DuffedUIConfigUILocalization.nameplatetransitioncolor = "失去/獲得仇恨值顏色"
	DuffedUIConfigUILocalization.nameplatedebuffs = "啟用姓名板debuff顯示"
	DuffedUIConfigUILocalization.nameplateheight = "設置姓名板高度 (默認 = 7)"
	DuffedUIConfigUILocalization.nameplatewidth = "設置姓名板款度 (默認 = 110)"
	DuffedUIConfigUILocalization.nameplateshowcastbarname = "顯示施法條名字"
	DuffedUIConfigUILocalization.nameplatenameabbrev = "顯示縮略名"
	DuffedUIConfigUILocalization.nameplateaurassize = "設置光環大小 (默認 = 20)"
	 
	-- merchant
	DuffedUIConfigUILocalization.merchant = "商人"
	DuffedUIConfigUILocalization.merchantsellgrays = "自動售賣灰色物品"
	DuffedUIConfigUILocalization.merchantautorepair = "自動修理物品"
	DuffedUIConfigUILocalization.merchantsellmisc = "自動販賣特定物品(非灰色等級的指定物品)"
	DuffedUIConfigUILocalization.merchantautoguildrepair = "啟用工會修理物品設定"
	 
	-- bags
	DuffedUIConfigUILocalization.bags = "背包"
	DuffedUIConfigUILocalization.bagsenable = "開啟背包整合"
	DuffedUIConfigUILocalization.bagsbpr = "設定背包每行顯示按鈕"
	DuffedUIConfigUILocalization.bagsmoveable = "使背包可移動"
	DuffedUIConfigUILocalization.bagsscale = "Set scale of bag & bank frames"
	DuffedUIConfigUILocalization.bagsspacing = "Set  spacing betweens bagslots"
	DuffedUIConfigUILocalization.bagsbuttonsize = " Set slotsize"
	 
	-- datatext
	DuffedUIConfigUILocalization.datatext = "文本資訊"
	DuffedUIConfigUILocalization.datatexttime24 = "使用24小時制"
	DuffedUIConfigUILocalization.datatextlocaltime = "使用本地時間取代伺服器時間"
	DuffedUIConfigUILocalization.datatextbattleground = "啟用戰場狀態"
	DuffedUIConfigUILocalization.datatextguild = "公會資訊 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatext_arp = "護甲穿透 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatextsystem = "記憶體佔用資訊 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatextbags = "背包 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatextfontsize = "文本字體大小"
	DuffedUIConfigUILocalization.datatextfps_ms = "延時和幀數(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextarmor = "護甲值 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatextavd = "免傷 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatextpower = "攻強/法傷(輸入0關閉)"
	DuffedUIConfigUILocalization.datatexthaste = "急速(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextfriends = "好友(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextwowtime = "時間(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextgold = "金幣(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextcrit = "爆擊 % (輸入0關閉)"
	DuffedUIConfigUILocalization.datatextdur = "耐久度(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextmicromenu = "微型功能表(輸入0關閉)"
	DuffedUIConfigUILocalization.datatexthit = "命中(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextmastery = "精通 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatexttalent = "顯示天賦 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatextcalltoarms = "地下城戰鬥的召喚 (輸入0關閉)"
	DuffedUIConfigUILocalization.datatextsmf = "系統(輸入0關閉)"
	DuffedUIConfigUILocalization.datatexthonorablekills = "榮譽擊殺統計(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextdodge = "閃躲率(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextparry = "招架率(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextblock = "格擋率(輸入0關閉)"
	DuffedUIConfigUILocalization.datatexthonor = "榮譽值(輸入0關閉)"
	DuffedUIConfigUILocalization.datatextprofession = "專業(輸入0關閉)"

	-- unit frames
	DuffedUIConfigUILocalization.unitframes = "單位框體"
	DuffedUIConfigUILocalization.unitframesenable = "啟用Duffed Ui頭像框架"
	DuffedUIConfigUILocalization.unitframeslayout = "設置人物頭像樣式 (layout數值為:1, 2 or 3, 默認 = 2)"
	DuffedUIConfigUILocalization.unitframespercent = "啟用生命百分比顯示於玩家&目標旁邊"
	DuffedUIConfigUILocalization.unitframeshealthbarcolor = "設定生命血條顏色"
	DuffedUIConfigUILocalization.unitframesdeficitcolor = "設定生命血量不足顏色"
	DuffedUIConfigUILocalization.unitframesColorGradient = "啟用生命條顏色漸變功能(隨血量變化)"
	DuffedUIConfigUILocalization.unitframesframewidth = "設定頭像框體寬度"
	DuffedUIConfigUILocalization.unitframestotandpetlines = "啟用寵物&目標的目標與頭像框體的連線效果(僅限於layout佈局1 & 2)"
	DuffedUIConfigUILocalization.unitframesportraitstyle = "設定頭像顯示風格(填寫 MODEL 或 ICON,僅限於layout佈局1&2)"
	DuffedUIConfigUILocalization.unitframeslargefocus = "啟用大型焦點目標框體(僅限於layout佈局1)"
	DuffedUIConfigUILocalization.unitframesbuffrows = "設定buff行數"
	DuffedUIConfigUILocalization.unitframesdebuffrows = "設定debuff行數"
	DuffedUIConfigUILocalization.unitframesvengeancebar = "啟用復仇條(坦克)代替仇恨條功能"
	DuffedUIConfigUILocalization.unitframespowerClasscolored = "啟用能量條職業顏色功能"
	DuffedUIConfigUILocalization.unitframesfocusdebuffs = "啟用焦點目標Debuff"
	DuffedUIConfigUILocalization.unitframessComboenable = "啟用sCombo連擊點Ui外掛程式"
	DuffedUIConfigUILocalization.unitframessComboenergybar = "啟用sCombo能量條Ui外掛程式"
	DuffedUIConfigUILocalization.unitframesenemyhcolor = "用敵對顏色為敵人框體著色(PVP玩家血條顏色)"
	DuffedUIConfigUILocalization.unitframesauratimer = "在光環上顯示時間"
	DuffedUIConfigUILocalization.unitframesauratextscale = "光環文字大小設置"
	DuffedUIConfigUILocalization.unitframestargetauras = "啟用目標光環"
	DuffedUIConfigUILocalization.unitframeslowThreshold = "低法力值警報 (所有的法系職業)"
	DuffedUIConfigUILocalization.unitframestargetpowerpvponly = "只顯示敵對目標的能量值"
	DuffedUIConfigUILocalization.unitframestotdebuffs = "啟用目標的目標的DEBUFF顯示 (僅限高解析度)"
	DuffedUIConfigUILocalization.unitframesshowtotalhpmp = "顯示總的生命/能量值"
	DuffedUIConfigUILocalization.unitframesshowsmooth = "啟用平滑狀態條"
	DuffedUIConfigUILocalization.unitframescharportrait = "為自身和目標啟用頭像顯示"
	DuffedUIConfigUILocalization.unitframesunicolor = "啟用單一的顏色主題(灰色的生命條)"
	DuffedUIConfigUILocalization.unitframescombatfeedback = "在玩家和目標框體上顯示戰鬥資訊"
	DuffedUIConfigUILocalization.unitframesplayeraggro = "在自身頭像上啟用仇恨顯示"
	DuffedUIConfigUILocalization.unitframeshealcomm = "啟用預估治療"
	DuffedUIConfigUILocalization.unitframesonlyselfdebuffs = "只在目標框體上顯示你釋放的DEBUFF"
	DuffedUIConfigUILocalization.unitframesshowfocustarget = "啟用焦點的目標框體"
	DuffedUIConfigUILocalization.unitframesshowstatuebar = "顯示狀態條"
	DuffedUIConfigUILocalization.unitframesbordercolor = "設置為默認的邊框顏色"
	DuffedUIConfigUILocalization.unitframesruneofpower = "啟用秘法符能能量條（法師）"
	DuffedUIConfigUILocalization.unitframesfader = "啟用頭像漸隱"
	DuffedUIConfigUILocalization.unitframesminalpha = "設定頭像漸隱最低透明度(默認 = 0.1)"
	DuffedUIConfigUILocalization.unitframesweakenedsoulbar = "啟用靈魂虛弱指示 (牧師)"
	DuffedUIConfigUILocalization.unitframesclassbar = "啟用職業條"
	DuffedUIConfigUILocalization.unitframesdruidmanabar = "熊、貓姿態下顯示魔法條（德魯伊）"
	DuffedUIConfigUILocalization.unitframesdruidmushroombar = "平衡或恢復天賦下啟用蘑菇條（德魯伊）"
	DuffedUIConfigUILocalization.unitframesfocusbutton = "Enable focus button on player / focus frame"
	DuffedUIConfigUILocalization.unitframestotdbsize = "Set size of debuffs for Target of Target"

	-- raid frames
	DuffedUIConfigUILocalization.raid = "團隊界面"
	DuffedUIConfigUILocalization.raidenable = "啟用團隊界面"
	DuffedUIConfigUILocalization.raidshowrange = "啟用小隊/團隊距離檢測"
	DuffedUIConfigUILocalization.raidraidalphaoor = "小隊/團隊超出距離透明值"
	DuffedUIConfigUILocalization.raidshowsymbols = "顯示小隊/團隊標記"
	DuffedUIConfigUILocalization.raidaggro = "在小隊/團隊中啟用仇恨顯示"
	DuffedUIConfigUILocalization.raidraidunitdebuffwatch = "啟用PVE光環檢測 (只能在GRIG模式下)"
	DuffedUIConfigUILocalization.raidgridhealthvertical = "在Grid模式中垂直顯示生命條"
	DuffedUIConfigUILocalization.raidgridscale = "Grid框體大小"
	DuffedUIConfigUILocalization.raidgridvertical = "在Grid中垂直顯示小隊"
	DuffedUIConfigUILocalization.raidshowraidpets = "Duffed團隊框架中啟用寵物框體"
	DuffedUIConfigUILocalization.raidshowgroupresurrect = "顯示(某人)被復活的圖示於團隊框架中"
	DuffedUIConfigUILocalization.raidshowplayerinparty = "在隊伍中顯示你自己"
	DuffedUIConfigUILocalization.raidgridonly = "治療模式下僅使用GRID樣式"
	DuffedUIConfigUILocalization.raidshowboss = "啟用BOSS框體"
	DuffedUIConfigUILocalization.raidarena = "開啟競技場單位框體"
	DuffedUIConfigUILocalization.raidmaintank = "啟用主坦克框體"
	DuffedUIConfigUILocalization.raidmainassist = "啟用主助理框架"
	DuffedUIConfigUILocalization.raidframewidth = "Set width of the unitframe"
	DuffedUIConfigUILocalization.raidframeheight = "Set height of the unitframe"
	DuffedUIConfigUILocalization.raidcolumnSpacing = "Columnspacing between unitframe"
	

	-- loot
	DuffedUIConfigUILocalization.loot = "拾取"
	DuffedUIConfigUILocalization.lootlootframe = "啟用拾取框"
	DuffedUIConfigUILocalization.lootautogreed = "滿級時啟用自動貪婪綠色物品"
	DuffedUIConfigUILocalization.lootrolllootframe = "啟用Roll點框體"
	 
	-- invite
	DuffedUIConfigUILocalization.invite = "邀請"
	DuffedUIConfigUILocalization.inviteautoaccept = "開啟自動接受邀請 (好友和公會成員)"
	 
	-- tooltip
	DuffedUIConfigUILocalization.tooltip = "滑鼠提示"
	DuffedUIConfigUILocalization.tooltipenable = "開啟滑鼠提示"
	DuffedUIConfigUILocalization.tooltiphidecombat = "戰鬥中隱藏滑鼠提示"
	DuffedUIConfigUILocalization.tooltiphidebuttons = "隱藏動作條滑鼠提示"
	DuffedUIConfigUILocalization.tooltiphideuf = "隱藏頭像框體滑鼠提示"
	DuffedUIConfigUILocalization.tooltipcursor = "開啟提示跟隨滑鼠指標"
	DuffedUIConfigUILocalization.tooltipids = "在物品提示上顯示法術/物品ID"
	DuffedUIConfigUILocalization.tooltipilvl = "啟用目標裝備等級統計顯示於滑鼠提示資訊上"
	DuffedUIConfigUILocalization.tooltipenablecaster = "Enable Castername for buffs / debuffs on tooltip"
	 
	-- error
	DuffedUIConfigUILocalization.error = "錯誤資訊"
	DuffedUIConfigUILocalization.errorenable = "隱藏螢幕中間的紅色錯誤提示資訊"
	 
	-- action bar
	DuffedUIConfigUILocalization.actionbar = "動作條"
	DuffedUIConfigUILocalization.actionbarhideshapeshift = "隱藏姿態或者圖騰欄"
	DuffedUIConfigUILocalization.actionbarshowgrid = "始終在動作條上顯示空按鈕"
	DuffedUIConfigUILocalization.actionbarenable = "啟用 DuffedUI 動作條"
	DuffedUIConfigUILocalization.actionbarrb = "啟用右側動作條滑鼠劃過顯示"
	DuffedUIConfigUILocalization.actionbarhotkey = "顯示快速鍵名稱"
	DuffedUIConfigUILocalization.actionbarssmo = "滑鼠劃過顯示姿態欄和圖騰欄"
	DuffedUIConfigUILocalization.actionbarrbn = "底部動作條數目 (1 或 2)"
	DuffedUIConfigUILocalization.actionbarrn = "右側動作條數目 (0, 1, 2 或 3)"
	DuffedUIConfigUILocalization.actionbarbuttonsize = "主動作條按鈕大小"
	DuffedUIConfigUILocalization.actionbarbuttonspacing = "動作條按鈕間距"
	DuffedUIConfigUILocalization.actionbarpetbuttonsize = "寵物或姿態欄按鈕大小"
	DuffedUIConfigUILocalization.actionbarownshdbar = "當暗影之舞時使用一個空的動作條來替代盜賊的潛行動作條（僅盜賊）"
	DuffedUIConfigUILocalization.actionbarownmetabar = "當惡魔形態時使用一個空的動作條來替代主動作條（僅術士）"
	DuffedUIConfigUILocalization.actionbarownwarstancebar = "切換姿態時使用一個空的動作條來替代主動作條（僅戰士）"
	DuffedUIConfigUILocalization.actionbarmacro = "在動作條上顯示巨集名稱"
	DuffedUIConfigUILocalization.actionbarbutton2 = "隱藏動作條中間的按鈕 (只有在動作條1與3沒有交換的情況下生效)"
	DuffedUIConfigUILocalization.actionbarrightbarsmouseover = "右動作條滑鼠劃過顯示"
	DuffedUIConfigUILocalization.actionbarswap = "動作條3和動作條1位置互換"
	DuffedUIConfigUILocalization.actionbarpetbaralwaysvisible = "寵物條永久可視"
	DuffedUIConfigUILocalization.actionbarshapeshiftborder = "啟用姿態條邊框"
	DuffedUIConfigUILocalization.actionbarshapeshiftmouseover = "姿態條滑鼠劃過顯示"
	DuffedUIConfigUILocalization.actionbarverticalshapeshift = "姿態條縱向顯示"
	DuffedUIConfigUILocalization.actionbarborderhighlight = "啟用 Tukui動作條技能高亮模式 (預設 = 關閉)"
	DuffedUIConfigUILocalization.actionbarlayout = "設定動作條佈局模式(預設佈局 = 1,填寫1或2)"
	DuffedUIConfigUILocalization.actionbarpetbarhorizontal = "設定寵物動作條橫向顯示模式"

	-- cooldowns
	DuffedUIConfigUILocalization.cooldown = "冷卻計時模組"
	DuffedUIConfigUILocalization.cooldownenable = "在技能按鈕上顯示冷卻時間"
	DuffedUIConfigUILocalization.cooldowntreshold = "在X秒以後以紅色顯示冷卻時間"

	-- raidcooldowns
	DuffedUIConfigUILocalization.rcd = "團隊技能冷卻"
	DuffedUIConfigUILocalization.rcdenable = "啟用團隊技能冷卻"
	DuffedUIConfigUILocalization.rcdraid = "在團隊中啟用團隊技能冷卻"
	DuffedUIConfigUILocalization.rcdparty = "在隊伍中啟用團隊技能冷卻"
	DuffedUIConfigUILocalization.rcdarena = "在競技場中啟用團隊技能冷卻"

	-- spellcooldowns
	DuffedUIConfigUILocalization.scd = "技能冷卻模組"
	DuffedUIConfigUILocalization.scdenable = "啟用技能冷卻外掛程式(介面中部冷卻提醒)"
	DuffedUIConfigUILocalization.scdsize = "設定圖示大小(預設= 36)"
	DuffedUIConfigUILocalization.scdspacing = "設定圖示間隔(預設 = 10)"
	DuffedUIConfigUILocalization.scdfade = "設定漸隱(設定值: 0 one color, 1 green to red, 2 red to green)"
	DuffedUIConfigUILocalization.scddisplay = "設定顯示模式(設定值: SPIRAL 或 STATUSBAR, 默認 = STATUSBAR)"
	DuffedUIConfigUILocalization.scddirection = "設定冷卻顯示方向(值: HORIZONTAL or VERTICAL, 默認 = HORIZONTAL)"
	DuffedUIConfigUILocalization.scdfsize = "設定字體大小"
	 
	-- chat
	DuffedUIConfigUILocalization.chat = "聊天"
	DuffedUIConfigUILocalization.chatenable = "啟用DuffedUI的聊天框架"
	DuffedUIConfigUILocalization.chatwhispersound = "在收到密語時播放提示音"
	DuffedUIConfigUILocalization.chatlbackground = "啟用聊天面板背景 (左)"
	DuffedUIConfigUILocalization.chatrbackground = "啟用聊天面板背景 (右)"
	DuffedUIConfigUILocalization.chatfading = "啟用聊天信息漸隱"
	DuffedUIConfigUILocalization.chattextright = "右下方聊天框文字向右對齊"

	-- buff
	DuffedUIConfigUILocalization.auras = "光環"
	DuffedUIConfigUILocalization.aurasplayer = "啟用 DuffedUI Buff/Debuff 框架"
	DuffedUIConfigUILocalization.aurasconsolidate = "啟用BUFF整合"
	DuffedUIConfigUILocalization.aurasflash = "當光環剩餘時間少於30秒時啟用閃爍動畫"
	DuffedUIConfigUILocalization.aurasclassictimer = "啟用經典光環計時樣式"
	DuffedUIConfigUILocalization.aurasbuffnotice = "啟用Buff缺失警告提醒"
	DuffedUIConfigUILocalization.auraswarning = "為Buff缺失警告提醒功能(BuffNotice)啟用報警音效"
	DuffedUIConfigUILocalization.aurasbufftracker = "啟用 Buff追蹤功能"
	DuffedUIConfigUILocalization.auraswrap = "設定(小地圖旁)單行Buff顯示數量(默認 = 18)"

	-- buttons
	DuffedUIConfigUILocalization.option_button_reset = "重置"
	DuffedUIConfigUILocalization.option_button_load = "應用設定"
	DuffedUIConfigUILocalization.option_button_close = "關閉"
	DuffedUIConfigUILocalization.option_setsavedsetttings = "為每個角色建立單獨的設定"
	DuffedUIConfigUILocalization.option_resetchar = "你確定要重置這個角色的設定到你的默認設定麼?"
	DuffedUIConfigUILocalization.option_resetall = "你確定要重置所有的設置為預設值麼?"
	DuffedUIConfigUILocalization.option_perchar = "你確定要啟用或者關閉“為單一角色設定”麼?"
	DuffedUIConfigUILocalization.option_makeselection = "在你繼續設置之前你必須要做出一個選擇。"
end